/**
 * MEDIA CORE. R2 listing, upload, thumbnails, metadata and delete mechanics.
 *
 * Shape 1 of media-module-architecture.md: this module knows nothing about what
 * cites an object. Content-agnostic BY CONSTRUCTION, not by convention, which
 * in practice means there is no import of anything post-shaped anywhere in this
 * file and no parameter that could carry one. "Who cites this key?" is asked
 * through the resolver seam in `resolvers.server.ts`, and the answer arrives as
 * data the core never inspects.
 *
 * That is the property that lets an album or a portfolio type register later
 * without this file changing.
 */

/** One page. Small enough to be a page rather than a dump of the bucket. */
export const MEDIA_PAGE_SIZE = 24;

/**
 * The prefix the library does NOT list.
 *
 * There is no positive prefix any more. Keys became content-addressed on
 * 2026-08-02, so an upload is a bare `<16 hex>.<ext>` at the root of the bucket
 * and the old `posts/` filter would have matched nothing at all. What remains is
 * an exclusion: OG cards are `r2-derived`, generated by `build:og`, and were
 * never library media.
 */
const DERIVED_PREFIX = "og/";

/**
 * Widths the thumbnail route will honour.
 *
 * A closed set, because the width lands in a cache key and an open one lets any
 * caller mint unlimited distinct transforms of the same object, each of which
 * is a billed unique transformation. Three sizes cover the grid thumbnail, the
 * picker tile and a 2x display of either.
 */
export const THUMB_WIDTHS = [160, 320, 640] as const;
export type ThumbWidth = (typeof THUMB_WIDTHS)[number];

export type MediaObject = {
  key: string;
  url: string;
  size: number;
  uploaded: string;
};

export type MediaPage = {
  objects: MediaObject[];
  /** Opaque R2 cursor for the next page, or null when this is the last one. */
  cursor: string | null;
  truncated: boolean;
};

/**
 * The URL that renders this object at a thumbnail width.
 *
 * URL-DERIVED, per ruling 3: the width is in the URL, the transform happens on
 * request from the single original in R2, and no variant is ever written back.
 * One object, every size derived from it.
 */
export function thumbUrl(key: string, width: ThumbWidth) {
  return `/media/${key}?w=${width}`;
}

/**
 * Lists one page of the bucket.
 *
 * **The ordering is now effectively arbitrary, and that is a KNOWN regression
 * with a scheduled fix, not an oversight.** R2 paginates in key order. This used
 * to be roughly chronological because keys began `posts/<year>/`; a
 * content-addressed key is a digest, so key order is now hash order, which
 * carries no meaning at all. Sorting within the page still happens and still
 * cannot fix ordering ACROSS pages, because that would mean listing the whole
 * bucket on every request, which is the dump pagination exists to avoid.
 *
 * This is exactly the ceiling the D1 index was ruled in to remove: sort by date,
 * filter to unused, search by filename are each a query, and none of them can be
 * built on a key-ordered iterator. Phase 3 repoints this at D1 and the
 * limitation goes with it. Recorded here rather than quietly tolerated.
 */
export async function listMedia(
  env: Env,
  options: { cursor?: string | null; limit?: number } = {},
): Promise<MediaPage> {
  const listed = await env.MEDIA.list({
    limit: options.limit ?? MEDIA_PAGE_SIZE,
    ...(options.cursor ? { cursor: options.cursor } : {}),
  });

  const objects = listed.objects
    .filter((object) => !object.key.startsWith(DERIVED_PREFIX))
    .map((object) => ({
      key: object.key,
      url: `/media/${object.key}`,
      size: object.size,
      uploaded:
        object.uploaded instanceof Date
          ? object.uploaded.toISOString()
          : String(object.uploaded ?? ""),
    }))
    .sort((a, b) => b.uploaded.localeCompare(a.uploaded));

  return {
    objects,
    // Returned rather than swallowed, the same rule the Ask prune learned the
    // hard way: a lister that silently shows page one is indistinguishable from
    // a bucket that has only one page in it.
    cursor: listed.truncated ? ((listed as { cursor?: string }).cursor ?? null) : null,
    truncated: listed.truncated,
  };
}

/** Intrinsic dimensions, read from the bytes rather than trusted from a client. */
export async function readDimensions(
  env: Env,
  key: string,
): Promise<{ width: number; height: number } | null> {
  const object = await env.MEDIA.get(key);
  if (!object) return null;
  try {
    const info = await env.IMAGES.info(object.body);
    // `info` is a union: an SVG reports no pixel dimensions, because it has
    // none. Recording 0 would be a measurement; recording nothing is the truth.
    if ("width" in info && "height" in info) {
      return { width: info.width, height: info.height };
    }
    return null;
  } catch {
    return null;
  }
}

/**
 * Deletes one object. MECHANICS ONLY.
 *
 * There is deliberately no reference check in here. This module cannot see
 * citations and must not appear to: a `deleteMedia` that sometimes refused
 * would invite a caller to treat it as the safety, and the safety belongs in
 * the action where the resolver's answer is available and where failing closed
 * can be enforced. This function does what its name says and nothing else.
 */
export async function deleteMediaObject(env: Env, key: string) {
  await env.MEDIA.delete(key);
}

/**
 * True when the key is one this module is willing to touch.
 *
 * It used to be a positive test against the `posts/` prefix. Content addressing
 * removed that anchor, so the test is now the SHAPE of a content key plus an
 * explicit refusal of the derived prefix. Anchored at both ends, so nothing with
 * a slash, a traversal segment or a leading `/` (which would be a static asset,
 * and static assets are not deletable through the UI) can pass.
 */
const CONTENT_KEY = /^[0-9a-f]{16}\.[a-z0-9]+$/;

export function isManagedKey(key: string) {
  return CONTENT_KEY.test(key) && !key.startsWith(DERIVED_PREFIX);
}
