-- Replace the llms.txt seed left by 0001_init.sql.
--
-- WHY THIS EXISTS. 0001 seeds settings['llms.txt'] with 247 bytes of copy
-- describing this site as belonging to a Professor of Virology. That subject
-- matter was retired on 2026-07-27 (dustinedwards/decisions-vol-1.md), and the
-- live row has been correct ever since, because `npm run sync:content` writes
-- it. The seed only surfaces on a FRESH database built from migrations, where
-- 0001 runs and nothing has synced yet.
--
-- 0001 is NOT edited and NOT deleted. It is an applied migration and it is also
-- the schema baseline: it creates posts, settings, posts_fts and its three
-- triggers, and all four Better Auth tables. `wrangler d1 export` is broken on
-- this database (fts5 virtual tables) so backups are per-table with
-- --no-schema, which means the migration files are the ONLY place the CREATE
-- TABLE statements exist. Deleting 0001 would leave a restore with data and
-- nothing to put it in.
--
-- So the seed is superseded here instead, which is what the repo's
-- add-a-new-numbered-file rule is for.
--
-- THIS VALUE IS A BASELINE, NOT THE CANONICAL COPY. The authority is
-- `npm run sync:content`, which rewrites this row from the live site. This is a
-- snapshot taken 2026-08-02 so a fresh build starts correct rather than wrong;
-- if it later sits one revision behind the live copy, that is expected and
-- harmless. Do not edit this file to chase it. `npm run check:llms` remains the
-- guard that catches the old seed if it ever reappears.
--
-- UPDATE rather than an upsert: 0001 always inserts the row, so it exists by
-- the time this runs.

UPDATE settings SET value = '# dustinedwards.info

Personal site of Dustin Edwards.

## About

Writing, projects, and notes.

## Blog

Posts are listed at /blog and can be filtered by tag at /blog?tag=<tag>.
Every post has a plain markdown twin at /blog/<slug>.md, which is the source
the page was rendered from. Requesting /blog/<slug> with an
Accept: text/markdown header returns the same markdown. The feed is at
/blog/rss.xml and /blog/feed.json.

## Search

/search?q=<query> searches the whole site and returns a normal HTML page.

The same URL returns JSON when requested with Accept: application/json. It is
the same query against the same index, not a separate API, and the response
varies on Accept. Parameters: q, type, tag, year, page. Operators inside q:
tag:<tag>, type:<type>, "quoted phrases", and a bare four-digit year, which is
read as a date filter rather than as text.

Results are section-grained: a hit carries the heading it was found under and a
url with that anchor, so a citation can point at the passage rather than the
page. Each result reports what it matched on (title, tag, body, or filter, the
last meaning the query was a bare year or tag with no text to match).

For programmatic use prefer the JSON form. It is keyword search over an FTS5
index: deterministic, the same query returning the same results, with no model
in the path and no per-request cost.

## Search over MCP

The same corpus is exposed as a Model Context Protocol endpoint, so an agent can
search this site as a tool without scraping it:

  https://2795d719-a4de-4558-9322-8fced66a48e6.search.ai.cloudflare.com/mcp

It needs no authentication and provides one tool, "search". Results carry the
same section-grained keys the rest of the site uses: blog/<slug>.md is a whole
post and blog/<slug>__<anchor>.md is one heading within it, which maps back to
/blog/<slug>#<anchor>.

This is semantic retrieval and it is not the same thing as the JSON endpoint
above. It finds passages that answer a question phrased in a sentence, and it
misses short exact tokens that the keyword index finds immediately. Neither
covers the other, so for a known term use the JSON search and for a question use
this.

Three ways in, then: a URL for people, JSON for programs, MCP for agents.

## Full text

/llms-full.txt carries every published post in markdown in one document.

## Contact

https://dustinedwards.info
'
WHERE key = 'llms.txt';
