// Ruling 115 decisions, chunk 1: scripts/check-browser.mjs blocks 0 to 107.
export default {
  "scripts/check-browser.mjs#1": ["CONTRACT","usage and observation boundary kept; audit story, tool choice and dev-server measurement moved","Gate: the site as a browser lays it out, not as markup.\n\n  npm run check:browser\n  npm run check:browser -- --keep    leave the preview server running\n\nChromium only. Public cases drive a preview build of this disk (the dev server\nserves the page unstyled), or the deployed site when `PUBLIC_ORIGIN` is set.\nAdmin cases always drive `ADMIN_ORIGIN`, because sessions live in production KV;\nabsent credentials skip, unusable ones fail. Nothing is submitted."],
  "scripts/check-browser.mjs#2": ["WHY","trimmed","The network profile the /blog layout shift was measured on."],
  "scripts/check-browser.mjs#3": ["WHY","trimmed","Imported, never restated (`check:invariants` section 25)."],
  "scripts/check-browser.mjs#4": ["WHY","placement reason kept; 2026-09-03 measurement moved","Needles a live command line must still match before this gate kills it. Declared\nhere because the port preflight needs them before any spawn."],
  "scripts/check-browser.mjs#5": ["WHY","purpose and gitignore reason kept; 2026-08-31 measurement moved","What this gate started, so the next run can clear what a hard kill left behind.\nGitignored, or `npm run ship` would refuse the dirty tree."],
  "scripts/check-browser.mjs#6": ["CONTRACT","two modes kept; narrative moved","Unset: public cases observe this disk. Set: they observe the deployed site."],
  "scripts/check-browser.mjs#7": ["WHY","already one line"],
  "scripts/check-browser.mjs#8": ["WHY","no-fake prohibition and cookie-name trap kept; three-session and 2026-08-21 story moved","The admin cookie, `name=value`, from `ADMIN_SESSION_COOKIE` or `.admin-session`. There is no\ntest-only auth bypass: the defects these cases catch live in the real authenticated render.\nNever infer the name from an `=`: base64 padding puts one in a bare token."],
  "scripts/check-browser.mjs#9": ["CONTRACT","trimmed","Reads the session file, or null. An unrecognised line is the cookie itself.\n\n@param {string} path"],
  "scripts/check-browser.mjs#11": ["CONTRACT","never-print-values rule kept","Turns a pair or a whole `Cookie:` header into one pair, or an error that names\ncookies and never prints a value.\n\n@param {string} raw\n@returns {{ pair: string, error: string }}"],
  "scripts/check-browser.mjs#12": ["WHY","ordering reason kept; plant story moved","Checked first: the placeholder is well formed and would read as an expired session."],
  "scripts/check-browser.mjs#13": ["WHY","already one line"],
  "scripts/check-browser.mjs#14": ["WHY","redaction reason kept; plant story moved","Print only name-shaped segments: a bare token parsed as a pair is its own name."],
  "scripts/check-browser.mjs#16": ["WHY","trimmed","Names the source read: a set `ADMIN_SESSION_COOKIE` overrides the file."],
  "scripts/check-browser.mjs#17": ["WHY","trimmed","The admin origin, not the preview: preview KV cannot hold a production session."],
  "scripts/check-browser.mjs#18": ["CONTRACT","states and never-print kept; dated narrative moved","The read-only smoke token, from `SMOKE_TOKEN_FILE` or `.smoke-token`; never printed.\nA named file that is missing, or an unusable one, fails rather than falling back."],
  "scripts/check-browser.mjs#19": ["WHY","already one line"],
  "scripts/check-browser.mjs#20": ["WHY","already one line"],
  "scripts/check-browser.mjs#21": ["WHY","trimmed","Smoke wins because it runs unattended; the cookie remains a full fallback."],
  "scripts/check-browser.mjs#22": ["WHY","jar-over-header reason kept; navigation counts moved","Uses the cookie jar: a pinned `Cookie` header fights Better Auth's refresh.\n\n@param {import(\"puppeteer\").Page} page\n@param {string} origin"],
  "scripts/check-browser.mjs#23": ["WHY","trimmed; counts moved","A pinned header is safe here: a bearer token has no refresh to fight.\n\n@param {import(\"puppeteer\").Page} page"],
  "scripts/check-browser.mjs#24": ["CONTRACT","already short"],
  "scripts/check-browser.mjs#25": ["CONTRACT","trimmed","`redirect: \"manual\"`: a followed 302 to /login reports 200.\n\n@param {string} origin"],
  "scripts/check-browser.mjs#26": ["WHY","trimmed","The status is kept: each smoke refusal status needs a different repair."],
  "scripts/check-browser.mjs#27": ["CONTRACT","already short"],
  "scripts/check-browser.mjs#28": ["WHY","trimmed","Not `skipped.length`: that cannot tell a rejected session from a completed run."],
  "scripts/check-browser.mjs#29": ["CONTRACT","trimmed","The pre-check's full result, so a failure can name a repair.\n\n@type {{ ok: boolean, status: number, error?: string }}"],
  "scripts/check-browser.mjs#31": ["CONTRACT","fail-soft reason kept; 2026-09-14 rename incident moved","Fails one case on a missing selector, where `page.click` would end the run.\n\n@param {any} target a Page or a Frame\n@param {string} selector\n@param {string} label what the click is for, used in the failure line\n@returns {Promise<boolean>} whether the click happened"],
  "scripts/check-browser.mjs#33": ["CONTRACT","trimmed","A measured fact that is neither a pass nor a failure.\n\n@param {string} what"],
  "scripts/check-browser.mjs#34": ["CONTRACT","section divider"],
  "scripts/check-browser.mjs#35": ["WHY","reporting and never-kill-a-stranger rules kept","Preflight: clear the last run's leftovers, reported even at zero. A pid whose\ncommand line no longer matches is dropped, never killed: pids are reused."],
  "scripts/check-browser.mjs#36": ["WHY","kill-only-on-needle rule kept; 2026-09-03 measurements and strictPort story moved","Preflight, second half: ask the OS who holds the port, which the registry may\nnot know. Kill only a `VITE_NEEDLES` match; anything else refuses the run."],
  "scripts/check-browser.mjs#37": ["WHY","trimmed to one line","An unreadable listing is reported, not treated as free or as fatal."],
  "scripts/check-browser.mjs#39": ["WHY","trimmed","`taskkill` returns before the socket is released, so re-probe until clear."],
  "scripts/check-browser.mjs#40": ["WHY","trimmed; 2026-08-31 measurement moved","Registered first: killing its wrappers orphans this process."],
  "scripts/check-browser.mjs#41": ["WHY","trimmed; timing moved","Builds rather than trusting build/, which may be stale."],
  "scripts/check-browser.mjs#42": ["WHY","trimmed","Enhancement bundles first: the app build imports them, and this gate runs alone."],
  "scripts/check-browser.mjs#43": ["WHY","trimmed","`cleanupChildren` is still in its temporal dead zone here."],
  "scripts/check-browser.mjs#44": ["WHY","trimmed","Said out loud, so a missing \"building\" line is not misread."],
  "scripts/check-browser.mjs#45": ["WHY","purpose and hand-written reason kept; item H2 narrative moved","Seeded mentions give the THEME_CACHED byte-identity case markup to cover.\nHand-written: the endpoint refuses the hostile row `safeHttpHref` must render."],
  "scripts/check-browser.mjs#46": ["CONTRACT","already one line"],
  "scripts/check-browser.mjs#47": ["WHY","already one line"],
  "scripts/check-browser.mjs#48": ["CONTRACT","already one line"],
  "scripts/check-browser.mjs#49": ["NUMBER","asserted by the seed count check"],
  "scripts/check-browser.mjs#50": ["WHY","trimmed","Delete then insert, so the count means this run wrote the rows."],
  "scripts/check-browser.mjs#51": ["WHY","trap kept; learning story moved","One quoted string: with `shell: true` on Windows an argv array is joined unquoted."],
  "scripts/check-browser.mjs#52": ["WHY","preview-door reason, hard rule 7 and --file reason kept; narrative moved","The draft math fixture is reached through a seeded `/preview/:token`, since\noffline markup cannot prove rendering (hard rule 7). `--file`, because the\nHTML's double quotes would break a cmd command string."],
  "scripts/check-browser.mjs#53": ["WHY","trimmed","Fixed, so a re-run overwrites one KV record. `isWellFormedToken` is length-exact."],
  "scripts/check-browser.mjs#54": ["WHY","already one line"],
  "scripts/check-browser.mjs#55": ["WHY","already one line"],
  "scripts/check-browser.mjs#57": ["WHY","trimmed","Fails rather than skips: `check:content` already requires the fixture."],
  "scripts/check-browser.mjs#58": ["WHY","already one line"],
  "scripts/check-browser.mjs#60": ["WHY","trimmed","`resolvePreview` re-checks post status, so a stale record cannot leak."],
  "scripts/check-browser.mjs#61": ["WHY","purpose kept; 2026-08-24 story moved","A ring buffer of server output, so a startup failure can show its cause."],
  "scripts/check-browser.mjs#64": ["WHY","trap kept; 2026-09-03 measurement moved","Without `--strictPort` vite binds the next port and the gate grades a stale server."],
  "scripts/check-browser.mjs#65": ["WHY","trimmed; 2026-08-31 measurement moved","This pid is the shell, which dies with the gate; survivors are recorded later."],
  "scripts/check-browser.mjs#66": ["WHY","trimmed","A dead server and a booting one look alike to a fetch, so exit ends the wait."],
  "scripts/check-browser.mjs#68": ["WHY","bound reasoning kept; dated samples and corrections moved","Polls until the server answers. The bound is generous: a dead server ends the\nwait at once, so only a live, slow one pays it."],
  "scripts/check-browser.mjs#69": ["WHY","already one line"],
  "scripts/check-browser.mjs#71": ["WHY","purpose kept; 2026-09-14 ruling narrative moved","What the readiness probe last saw, so a timeout names what it waited on."],
  "scripts/check-browser.mjs#73": ["WHY","already one line"],
  "scripts/check-browser.mjs#74": ["WHY","trimmed","A deployed origin is not booting: one attempt, status reported, no retry."],
  "scripts/check-browser.mjs#75": ["WHY","reason kept; 2026-09-06 measurement moved","Survivors are recorded on every poll, since a kill during startup is the case\nthe registry exists for. Throttled: reading the process table is expensive."],
  "scripts/check-browser.mjs#76": ["WHY","trimmed to one line","Answered and said no: a wrong probe path, not a slow boot."],
  "scripts/check-browser.mjs#77": ["CONTRACT","trimmed","ECONNREFUSED is still booting, a timeout is a wedge, anything else verbatim."],
  "scripts/check-browser.mjs#79": ["WHY","trimmed","Gone, so waiting cannot help; the caller prints its output."],
  "scripts/check-browser.mjs#80": ["CONTRACT","trimmed","The server's state and last output; an empty capture says so."],
  "scripts/check-browser.mjs#81": ["WHY","trimmed","The state first: it decides what to do next."],
  "scripts/check-browser.mjs#82": ["WHY","trimmed","No server was started, so diagnose the deployed origin."],
  "scripts/check-browser.mjs#83": ["CONTRACT","trimmed","Records `VITE_NEEDLES`-matching processes that outlive a killed gate. workerd and\nesbuild are reached by `taskkill /T` from vite."],
  "scripts/check-browser.mjs#84": ["WHY","trimmed; duplicate-count incident moved","Pids already written, held in memory because the registry is append-only."],
  "scripts/check-browser.mjs#85": ["WHY","trimmed","`/T`, because the spawned pid is a shell above vite."],
  "scripts/check-browser.mjs#86": ["CONTRACT","trimmed","Stops every child on an orderly exit: `browser.close()`, then a tree kill.\n\n@param {import(\"puppeteer\").Browser | undefined} openBrowser"],
  "scripts/check-browser.mjs#87": ["WHY","trimmed","With `--keep` the entries stay, and the next preflight frees the port."],
  "scripts/check-browser.mjs#88": ["WHY","trimmed","Declared before the signal handlers that close over it (temporal dead zone).\n\n@type {import(\"puppeteer\").Browser | undefined}"],
  "scripts/check-browser.mjs#89": ["WHY","trimmed","`taskkill /F` delivers no signal; the registry covers it. `process.exit`, because\nreturning resumes a gate whose children are gone."],
  "scripts/check-browser.mjs#91": ["WHY","already one line"],
  "scripts/check-browser.mjs#92": ["WHY","trap kept; plant measurement moved","Not `process.exit()`: with the probe's undici handle in flight, libuv aborts on\nWindows."],
  "scripts/check-browser.mjs#93": ["WHY","trimmed","The Puppeteer cache path, not \"chrome\", so cleanup never reaches a user's browser."],
  "scripts/check-browser.mjs#94": ["WHY","trimmed","Names which build the public cases observe."],
  "scripts/check-browser.mjs#95": ["CONTRACT","section divider"],
  "scripts/check-browser.mjs#96": ["WHY","trimmed","Scope first: an unstyled page would pass every layout assertion below."],
  "scripts/check-browser.mjs#97": ["WHY","intent kept; re-measurement history and counts moved","A crude per-route floor that catches a page with no stylesheet. Byte ceilings\nare `check:page-payload`'s."],
  "scripts/check-browser.mjs#98": ["CONTRACT","section divider"],
  "scripts/check-browser.mjs#99": ["WHY","prime and cache-bust reasons kept; 2026-08-26 timings moved","`/api/health` is hit first to exercise the snapshot write; the read is\ncache-busted because the home page is shared-cached."],
  "scripts/check-browser.mjs#100": ["CONTRACT","already short"],
  "scripts/check-browser.mjs#101": ["WHY","trimmed","Wall clock at the read, so an age becomes a fixed write time."],
  "scripts/check-browser.mjs#102": ["CONTRACT","trimmed","When the shown snapshot was written, on the local clock.\n\n@param {{age: number|null, readAtMs: number}} t"],
  "scripts/check-browser.mjs#103": ["WHY","discrimination and poll reasons kept; plant and 2026-08-28 story moved","Compares write times before and after: a leftover snapshot in persistent KV\npasses an absolute age check. Polled, because KV reads are edge-cached."],
  "scripts/check-browser.mjs#104": ["WHY","trimmed","The poll stops at the first newer write, so the budget is only a ceiling."],
  "scripts/check-browser.mjs#106": ["WHY","trimmed","Skipped with no first reading: an absent number would pass vacuously."],
  "scripts/check-browser.mjs#107": ["WHY","trap kept; incident moved","Back to /blog: every case below reuses this page."],
};
