// Ruling 115 decisions, chunk 10: scripts/verify-live.mjs blocks 0 to 159.
export default {
  "scripts/verify-live.mjs#0": ["CONTRACT", "usage, boundary and harness rules kept; theme-cookie incident moved", "Live verification against the deployed Worker. Not a gate: it needs a deploy.\n\n  node scripts/verify-live.mjs [origin]\n\nA deploy empties the cache, so run it twice (cold, then warm) after a caching change.\nA pass count that varies between runs points at the cache first.\n\nHarness rules: send a browser user-agent (Cloudflare 403s some clients) and\n`Cache-Control: no-cache`; scope every content assertion; never pin a content hash;\nstrip SSR's <!-- --> and decode its entities before matching."],
  "scripts/verify-live.mjs#1": ["WHY", "imported, never restated", "Imported, never restated."],
  "scripts/verify-live.mjs#2": ["WHY", "trimmed", "Imported so section 12b matches the index's own section leads."],
  "scripts/verify-live.mjs#3": ["WHY", "trimmed; owner kept", "Owner: the watchdog cron, bound by check:invariants section 25."],
  "scripts/verify-live.mjs#4": ["HISTORY", "refers to removed code", null],
  "scripts/verify-live.mjs#5": ["WHY", "trimmed", "Shared with the offline gate, so section 16 compares the same set."],
  "scripts/verify-live.mjs#6": ["WHY", "trimmed; incident moved", "Derived like the sync and uploader do; a literal key goes stale."],
  "scripts/verify-live.mjs#7": ["WHY", "trimmed", "Read, not restated. Not an import attribute: this tsconfig rejects it."],
  "scripts/verify-live.mjs#11": ["WHY", "already one line"],
  "scripts/verify-live.mjs#13": ["WHY", "trap kept; measurement moved", "React escapes `'` to `&#x27;`, so data-file prose needs decoding to match.\n\n@param {string} s"],
  "scripts/verify-live.mjs#14": ["WHY", "already one line"],
  "scripts/verify-live.mjs#15": ["CONTRACT", "section heading shortened", "1. Theme resolution, server rendered"],
  "scripts/verify-live.mjs#17": ["WHY", "shortened", "Legacy cookie, resolving to the default."],
  "scripts/verify-live.mjs#18": ["WHY", "trimmed", "Anti-flash: no script sets the attribute."],
  "scripts/verify-live.mjs#19": ["CONTRACT", "section heading shortened", "2. Theme persists across navigation"],
  "scripts/verify-live.mjs#20": ["CONTRACT", "section heading shortened", "3. The shipped stylesheets carry the v3 palette"],
  "scripts/verify-live.mjs#21": ["WHY", "two-plane assertion intent kept; split history moved", "Public and admin sheets are asserted apart, never as a union. `/login` links both."],
  "scripts/verify-live.mjs#22": ["WHY", "trimmed", "Scope first: two distinct sheets, or a collapsed split looks healthy."],
  "scripts/verify-live.mjs#23": ["WHY", "trimmed", "v3 tokens, from the doc, on the public sheet."],
  "scripts/verify-live.mjs#24": ["WHY", "already one line"],
  "scripts/verify-live.mjs#25": ["WHY", "trimmed", "Admin-only: reads the token, and has not leaked into the public sheet."],
  "scripts/verify-live.mjs#26": ["WHY", "scope rule kept; split history moved", "Search rules live on `/search`'s own sheets (its links minus `/`'s), proven non-empty."],
  "scripts/verify-live.mjs#27": ["WHY", "trimmed", "Site-wide law, so both sheets."],
  "scripts/verify-live.mjs#28": ["CONTRACT", "SCOPED-BY marker read by check:assertions; kept"],
  "scripts/verify-live.mjs#29": ["CONTRACT", "section heading shortened", "4. Header: the icon control and the stray slash"],
  "scripts/verify-live.mjs#30": ["WHY", "contract kept; dated history moved", "The no-JS wire never advertises the shortcut, which does not exist there."],
  "scripts/verify-live.mjs#31": ["WHY", "trimmed", "The description is outside the anchor, so assert the association."],
  "scripts/verify-live.mjs#32": ["WHY", "wire half kept; history moved", "One submit per theme, both writable, neither pressed. Painting is check:browser's."],
  "scripts/verify-live.mjs#33": ["CONTRACT", "section heading shortened", "5. The markdown twin is byte-identical to the repo"],
  "scripts/verify-live.mjs#34": ["WHY", "trap kept; measurement moved", "The artifact's body, not the repo file, which also carries frontmatter."],
  "scripts/verify-live.mjs#37": ["WHY", "chain kept; tautology story moved", "check:content binds artifact to file. Agents choose the twin by content-type."],
  "scripts/verify-live.mjs#38": ["CONTRACT", "section heading shortened", "6. Search still works, and marks are gold"],
  "scripts/verify-live.mjs#39": ["WHY", "trimmed", "Scoped: the zero state lists the same links."],
  "scripts/verify-live.mjs#40": ["CONTRACT", "section heading shortened", "7. Admin is still gated"],
  "scripts/verify-live.mjs#41": ["CONTRACT", "section heading shortened", "8. The orphaned static assets"],
  "scripts/verify-live.mjs#42": ["CONTRACT", "heading and cap rule kept; leak story moved", "9. Drafts reach none of the nine public surfaces. Ask bills, so its probes are capped."],
  "scripts/verify-live.mjs#46": ["WHY", "trimmed; ruling history moved", "The published corpus, across every page its count implies."],
  "scripts/verify-live.mjs#47": ["WHY", "intent kept; tautology story moved", "The last page in range has posts; the next has none."],
  "scripts/verify-live.mjs#50": ["HISTORY", "tense-bound narrative", null],
  "scripts/verify-live.mjs#51": ["CONTRACT", "SCOPED-BY marker; kept"],
  "scripts/verify-live.mjs#52": ["WHY", "trimmed", "SQLite leaves publishAt ties unordered, so a position is a range of pages."],
  "scripts/verify-live.mjs#56": ["WHY", "trimmed", "Every page, not page 1."],
  "scripts/verify-live.mjs#57": ["WHY", "trimmed", "Its own title is the strongest query."],
  "scripts/verify-live.mjs#58": ["CONTRACT", "key shape kept; first-version story moved", "A citation is `item.key` (`blog/<slug>[__<anchor>].md`), not a URL.\n\n@param {string} label @param {string} q\n@returns {Promise<{keys: string[], status: number} | null>} null if refused"],
  "scripts/verify-live.mjs#59": ["WHY", "date moved", "POST: Ask bills, and a GET is reachable by crawlers."],
  "scripts/verify-live.mjs#60": ["WHY", "trimmed", "A refusal is not evidence of absence."],
  "scripts/verify-live.mjs#62": ["WHY", "trimmed", "Positive control, so an empty draft probe means no leak. Repick it if it stops."],
  "scripts/verify-live.mjs#64": ["WHY", "intent kept; audit story moved", "Injection replay: no-answer text, zero chunks, and no cache hit on a repeat call."],
  "scripts/verify-live.mjs#66": ["NUMBER", "rate limit not asserted here; cap rule kept", "Billed, so capped, and the cap is printed."],
  "scripts/verify-live.mjs#67": ["CONTRACT", "section heading shortened", "10. The retired routes are bare 404s, and the kept files are not"],
  "scripts/verify-live.mjs#68": ["WHY", "prohibition kept; history moved", "Never a prefix rule: /publications/* and /phage-hunters/* are kept files."],
  "scripts/verify-live.mjs#69": ["CONTRACT", "section heading shortened", "11. The Roster page at the legacy URL"],
  "scripts/verify-live.mjs#70": ["HISTORY", "repeats the header rule", null],
  "scripts/verify-live.mjs#71": ["WHY", "trap kept; audit story moved", "Delimited: the nav renders `Roster` on every page."],
  "scripts/verify-live.mjs#72": ["WHY", "trimmed", "Per year, so a failure names it."],
  "scripts/verify-live.mjs#73": ["WHY", "trimmed; history moved", "Count what was found, so \"0 missing\" cannot mean \"0 examined\"."],
  "scripts/verify-live.mjs#74": ["WHY", "trimmed", "Linked from the homepage, so reachable."],
  "scripts/verify-live.mjs#75": ["CONTRACT", "section heading shortened", "12. The colophon"],
  "scripts/verify-live.mjs#76": ["HISTORY", "repeats the header rule", null],
  "scripts/verify-live.mjs#77": ["WHY", "trimmed", "Title and path deliberately differ."],
  "scripts/verify-live.mjs#78": ["WHY", "trimmed", "A positive count."],
  "scripts/verify-live.mjs#80": ["WHY", "trimmed; history moved", "Delimited: many feature names are ordinary sentences."],
  "scripts/verify-live.mjs#82": ["WHY", "trimmed", "From another page, so the site-wide footer carries it."],
  "scripts/verify-live.mjs#83": ["WHY", "trimmed", "Served from D1, so this catches a sync that never ran."],
  "scripts/verify-live.mjs#84": ["CONTRACT", "SCOPED-BY marker; kept"],
  "scripts/verify-live.mjs#85": ["WHY", "trimmed", "One template line, so one post suffices."],
  "scripts/verify-live.mjs#86": ["CONTRACT", "heading kept; commit history moved", "12b. The colophon is in the live search index, section-grained. No offline gate sees it."],
  "scripts/verify-live.mjs#87": ["WHY", "trimmed; measurement moved", "A section's slice, heading to heading; unscoped tokens match `<head>`.\n\n@param {string} html @param {string} id"],
  "scripts/verify-live.mjs#88": ["CONTRACT", "trimmed; history moved", "Authored apart from `colophonPageInput`; that module's header says why.\n\n@param {string} id\n@returns {string[]}"],
  "scripts/verify-live.mjs#89": ["WHY", "trap kept; measurement moved", "Unique to the colophon after porter stemming (`Vectorize` becomes `vector`)."],
  "scripts/verify-live.mjs#92": ["WHY", "already one line"],
  "scripts/verify-live.mjs#93": ["HISTORY", "restates the code", null],
  "scripts/verify-live.mjs#94": ["WHY", "trimmed", "A section hit's fragment exists; a dead one fails silently."],
  "scripts/verify-live.mjs#95": ["WHY", "trimmed", "Only `post` in the facet means the page sync never ran."],
  "scripts/verify-live.mjs#97": ["CONTRACT", "trimmed", "Every value a section's record carries is on that section of the page."],
  "scripts/verify-live.mjs#98": ["HISTORY", "restates the rule above", null],
  "scripts/verify-live.mjs#99": ["CONTRACT", "section heading shortened", "13. The cache, observed warm"],
  "scripts/verify-live.mjs#100": ["WHY", "trap kept; story moved", "Every other section runs cold, so this warms each entry and asks again.\nNot `get()`: its `no-cache` makes \"not a HIT\" pass vacuously (hard rule 10)."],
  "scripts/verify-live.mjs#101": ["HISTORY", "restates #100", null],
  "scripts/verify-live.mjs#105": ["WHY", "trimmed; history moved", "Each sets its own `headers`; the Worker default is asserted in section 14."],
  "scripts/verify-live.mjs#106": ["HISTORY", "restates the population rule below", null],
  "scripts/verify-live.mjs#107": ["WHY", "populations kept; history moved", "Cookieless readers HIT the default; cookied readers get their own theme."],
  "scripts/verify-live.mjs#108": ["WHY", "trimmed", "(a) Retried: an entry needs a few requests to settle."],
  "scripts/verify-live.mjs#109": ["WHY", "trimmed; inversion history moved", "(b) The theme is in the key, so the second cookied read must HIT."],
  "scripts/verify-live.mjs#110": ["WHY", "trimmed", "Asserted on the HIT."],
  "scripts/verify-live.mjs#111": ["WHY", "owner kept", "(c) is check:browser's (hard rule 8)."],
  "scripts/verify-live.mjs#112": ["WHY", "trimmed", "`Vary: Cookie` would fragment every entry."],
  "scripts/verify-live.mjs#113": ["HISTORY", "revert story", null],
  "scripts/verify-live.mjs#114": ["WHY", "intent kept; measurement moved", "Case B: an alternate representation must not collapse the cookie dimension."],
  "scripts/verify-live.mjs#117": ["WHY", "trimmed", "Control: proves the URL is shared-cached."],
  "scripts/verify-live.mjs#118": ["HISTORY", "restates the code", null],
  "scripts/verify-live.mjs#119": ["WHY", "trimmed", "llms.txt advertises both forms."],
  "scripts/verify-live.mjs#120": ["HISTORY", "restates the check", null],
  "scripts/verify-live.mjs#121": ["WHY", "prohibition kept; incident moved", "Derived, never literal: a pruned key 404s and reads as a cache failure."],
  "scripts/verify-live.mjs#123": ["CONTRACT", "heading and parse rule kept; history moved", "14. Security headers, on the wire, parsed from `workers/app.ts`, never restated.\nThe 302 has immutable headers, so it takes the rebuild branch."],
  "scripts/verify-live.mjs#124": ["WHY", "trimmed", "Comments first, or docblock prose parses."],
  "scripts/verify-live.mjs#126": ["HISTORY", "restated by the assertion", null],
  "scripts/verify-live.mjs#128": ["WHY", "trimmed", "The default arrives only on this 302; source is not wire (hard rule 7)."],
  "scripts/verify-live.mjs#129": ["WHY", "trimmed; reversal history moved", "CSP, enforced. A static nonce is visible only on the wire."],
  "scripts/verify-live.mjs#130": ["WHY", "trimmed; cache history moved", "A cache-busting query per probe forces two renders."],
  "scripts/verify-live.mjs#133": ["HISTORY", "incident", null],
  "scripts/verify-live.mjs#134": ["WHY", "trimmed; measurement and dates moved", "Pins the accepted shared-nonce window on a HIT; red if it changes."],
  "scripts/verify-live.mjs#135": ["CONTRACT", "heading and gap kept; measurement moved", "15. The draft preview route: only the unminted-token 404 is wire-assertable.\nThe 200 needs a live token, so it is verified locally, never here."],
  "scripts/verify-live.mjs#136": ["WHY", "trimmed", "Well formed: a malformed token is refused before lookup."],
  "scripts/verify-live.mjs#137": ["HISTORY", "restated by the needle", null],
  "scripts/verify-live.mjs#138": ["HISTORY", "restated by the message", null],
  "scripts/verify-live.mjs#139": ["CONTRACT", "SCOPED-BY rationale trimmed", "SCOPED-BY whole lines, so `/preview` cannot match a longer path."],
  "scripts/verify-live.mjs#140": ["CONTRACT", "SCOPED-BY marker; kept"],
  "scripts/verify-live.mjs#141": ["CONTRACT", "SCOPED-BY marker; kept"],
  "scripts/verify-live.mjs#142": ["CONTRACT", "section heading shortened", "16. The public script set on the wire is the enhancements alone"],
  "scripts/verify-live.mjs#143": ["WHY", "trimmed; dates moved", "A modulepreload means a public page hydrates. Stems come from source."],
  "scripts/verify-live.mjs#145": ["WHY", "trimmed", "Scope proven non-empty."],
  "scripts/verify-live.mjs#146": ["CONTRACT", "section heading shortened", "17. A post image on the wire is a link to its original"],
  "scripts/verify-live.mjs#147": ["WHY", "trimmed; measurement moved", "Only the deployed origin shows an R2 target. No image is reported, not failed."],
  "scripts/verify-live.mjs#151": ["HISTORY", "restates the regex", null],
  "scripts/verify-live.mjs#152": ["WHY", "trimmed", "`?w=` is the defect this replaces."],
  "scripts/verify-live.mjs#153": ["CONTRACT", "section heading shortened", "17. The watchdog is firing, read off the home page's health tile"],
  "scripts/verify-live.mjs#154": ["WHY", "mechanism and window kept; essay moved", "Each firing refreshes the snapshot the tile ages. Ship's poll does too, so this\nproves less just after a ship. A unique query forces a fresh render."],
  "scripts/verify-live.mjs#155": ["WHY", "trimmed", "Scope first."],
  "scripts/verify-live.mjs#156": ["WHY", "trimmed", "Two: one flaps; three is when the tile already says stale."],
  "scripts/verify-live.mjs#157": ["CONTRACT", "section heading shortened", "Report"],
  "scripts/verify-live.mjs#158": ["WHY", "floor rule kept; measurement history moved", "Floor on executed assertions: skipped loops look like zero failures. Measure it\nthrough a real run, never from call sites, and move it only deliberately."],
  "scripts/verify-live.mjs#159": ["WHY", "trimmed; draft story moved", "Failures print first; the floor never hides them."],
};
