// Ruling 115 decisions, chunk 11: app/routes/admin.media._index.tsx blocks 0 to 125.
export default {
  "app/routes/admin.media._index.tsx#0": ["CONTRACT","module purpose and no-script fallback kept; v1 redesign narrative moved","The media library: search, browse, copy an address, and manage one asset.\n\nWithout script the copy button is inert; the filename links to `?key=`, which shows the address."],
  "app/routes/admin.media._index.tsx#1": ["CONTRACT","vocabulary kept; deleted-array story moved","The filter vocabulary: `?role=` values, verbatim from the role column."],
  "app/routes/admin.media._index.tsx#2": ["WHY","cap reason kept, trimmed","About six rows fit under the search bar before the arrow keys scroll the highlight away."],
  "app/routes/admin.media._index.tsx#3": ["WHY","evidence mechanism kept; plant story moved","Shortcuts as data. `check:admin-ui` greps for each row's `evidence` token, so an unwired row fails."],
  "app/routes/admin.media._index.tsx#4": ["WHY","trimmed","Each lens with its question. `unattached` warns most: it reads as permission to delete."],
  "app/routes/admin.media._index.tsx#5": ["WHY","build-time import reason kept, trimmed","A build-time import: the scan needs a filesystem and the Worker has none."],
  "app/routes/admin.media._index.tsx#6": ["CONTRACT","trimmed","Set by the /admin middleware on `?timing=1`; when undefined, `timed` is a plain call."],
  "app/routes/admin.media._index.tsx#7": ["WHY","trimmed","The picker reads this loader, so it is the same listing, not a second one."],
  "app/routes/admin.media._index.tsx#8": ["WHY","one-definition reason kept; alternatives discussion moved","The palette uses the same `matchesQuery` as the GET form it degrades to."],
  "app/routes/admin.media._index.tsx#9": ["WHY","trimmed","Default to content; `?role=all` means everything, and an unknown value means the default."],
  "app/routes/admin.media._index.tsx#10": ["WHY","structural reason kept; incident moved","Parsed once by the module that builds every link, so no link can drop a parameter."],
  "app/routes/admin.media._index.tsx#11": ["WHY","already one line"],
  "app/routes/admin.media._index.tsx#12": ["WHY","trimmed","The reader's Display choices. The picker ignores them: it is a fixed insertion surface."],
  "app/routes/admin.media._index.tsx#13": ["WHY","trimmed","Unattached: no post cites it and no repository code places it. In SQL, for full pages."],
  "app/routes/admin.media._index.tsx#14": ["WHY","prohibition kept, trimmed","In SQL, never merged with `role`: a `?role=` must not widen what may be inserted."],
  "app/routes/admin.media._index.tsx#15": ["WHY","trimmed","No role filter in the trash view, whose job is finding anything thrown away."],
  "app/routes/admin.media._index.tsx#16": ["WHY","restated cap moved; exclusion reason kept","No usage, citations or twins: three more queries per keystroke for nothing a picker needs."],
  "app/routes/admin.media._index.tsx#17": ["WHY","two-source union reason kept, trimmed","Usage asked two ways, either can refuse: `media_refs` (rendered) and the markdown scan (superset)."],
  "app/routes/admin.media._index.tsx#18": ["WHY","placement prohibition kept; serial-await story moved","Starts here, not at the loader top: earlier branches return and would leave a promise unawaited."],
  "app/routes/admin.media._index.tsx#19": ["WHY","trimmed","Exact content identity only; see `mediaTwins`."],
  "app/routes/admin.media._index.tsx#20": ["WHY","unasserted row count moved","A parameter, not a route: static keys contain `/`. Read by key, so a bookmark works anywhere."],
  "app/routes/admin.media._index.tsx#21": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#22": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#23": ["CONTRACT","regex replacement story moved","The content hash, read off the key by `digestFromKey`. Static keys are paths and have none."],
  "app/routes/admin.media._index.tsx#24": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#25": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#26": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#27": ["WHY","trimmed","Suggested, never applied: a filename posing as alt hides a defect an empty field shows."],
  "app/routes/admin.media._index.tsx#28": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#29": ["WHY","trimmed","Built here so the component needs only loader data, which `check:admin-ui` renders."],
  "app/routes/admin.media._index.tsx#30": ["WHY","unasserted corpus numbers moved","After the read, so `mediaTwins` stays the one definition of twin; a page may run short."],
  "app/routes/admin.media._index.tsx#31": ["WHY","trimmed","Decided here: `check:admin-ui` stubs `core.server`, so a component calling it throws."],
  "app/routes/admin.media._index.tsx#32": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#33": ["WHY","already one line"],
  "app/routes/admin.media._index.tsx#34": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#35": ["WHY","trimmed","`usageStateOf` owns the precedence, so tile, row, lens and inspector cannot disagree."],
  "app/routes/admin.media._index.tsx#36": ["WHY","unasserted count and mockup story moved","Source files that place it, as repo-relative paths a reader can open."],
  "app/routes/admin.media._index.tsx#37": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#38": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#39": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#40": ["WHY","trimmed","Whole, so the component builds every link with `hrefWith(view, ...)`."],
  "app/routes/admin.media._index.tsx#41": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#42": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#43": ["CONTRACT","trimmed","Tags in use, with counts. Excludes trashed rows, so no chip leads to an empty grid."],
  "app/routes/admin.media._index.tsx#44": ["WHY","trimmed","One query sharing the filters' predicates; `duplicates` comes from `mediaTwins`."],
  "app/routes/admin.media._index.tsx#45": ["WHY","incident moved","The list the listing got, so the chip and the grid cannot disagree."],
  "app/routes/admin.media._index.tsx#46": ["HISTORY","removed-chip narrative",null],
  "app/routes/admin.media._index.tsx#47": ["WHY","limitation kept; rewrite story moved","The scan sees only literal paths and no external links, hence unattached, not unused."],
  "app/routes/admin.media._index.tsx#48": ["WHY","trimmed","Not timing serialization: the framework encodes turbo-stream, so a stringify would mislead."],
  "app/routes/admin.media._index.tsx#49": ["WHY","trimmed","No header unless asked, so the default response carries no timing data."],
  "app/routes/admin.media._index.tsx#50": ["WHY","trimmed","`setMediaTags` owns the storage form. No `isManagedKey` gate: this never writes the bucket."],
  "app/routes/admin.media._index.tsx#51": ["WHY","grammar and single-writer prohibition kept","Posts index grammar: one tag, skip rows in state, name both counts. Only `setMediaTags` writes."],
  "app/routes/admin.media._index.tsx#52": ["WHY","trimmed","One tag, normalised by its owner. Normalising to nothing is refused, not a clear."],
  "app/routes/admin.media._index.tsx#53": ["WHY","already short"],
  "app/routes/admin.media._index.tsx#54": ["WHY","prohibition kept; incident moved","An empty field does not clear; clearing needs `clear`, so an accident cannot wipe every tag."],
  "app/routes/admin.media._index.tsx#55": ["WHY","ruling citation and narration moved","Trash and restore touch neither R2 nor a public URL, and the messages say so."],
  "app/routes/admin.media._index.tsx#56": ["WHY","trimmed","Reversible, so a plain confirmation. Iterates `trashMediaRecord`; no bulk SQL writer."],
  "app/routes/admin.media._index.tsx#57": ["WHY","trimmed","Iterates the guarded delete per key, so `claimMediaKeyForDelete` still refuses a cited asset."],
  "app/routes/admin.media._index.tsx#58": ["WHY","enforcement reason kept; incident moved","Checked here: the confirm button renders enabled without script. Uses this request's count."],
  "app/routes/admin.media._index.tsx#59": ["WHY","already short"],
  "app/routes/admin.media._index.tsx#60": ["WHY","ruling number dropped","Saving alt rewrites no post: alt is contextual, so only future insertions pick it up."],
  "app/routes/admin.media._index.tsx#61": ["WHY","two-question distinction kept; 2026-08-02 incident moved","Row count says the rebuild ran; role split says `roleOf()` works. Report both, read from D1."],
  "app/routes/admin.media._index.tsx#62": ["WHY","trimmed; ruling date moved","A rebuild prunes rows whose source is gone. Count 1: the rows at risk are unknowable beforehand."],
  "app/routes/admin.media._index.tsx#63": ["WHY","trimmed","Alongside the row count, never instead of it: see above."],
  "app/routes/admin.media._index.tsx#64": ["WHY","already short"],
  "app/routes/admin.media._index.tsx#65": ["WHY","incident moved","Checked here, not in `onSubmit`, so it holds without script; an uncited object passes the rest."],
  "app/routes/admin.media._index.tsx#66": ["WHY","trimmed","Refused in the action, not by hiding a button: a deleted row would return on the next rebuild."],
  "app/routes/admin.media._index.tsx#67": ["WHY","trimmed","Server side on a fresh read: a post may have cited the object since the page rendered."],
  "app/routes/admin.media._index.tsx#68": ["WHY","ruling number dropped","Fail closed: a failed scan is not \"nothing cites it\"."],
  "app/routes/admin.media._index.tsx#69": ["WHY","trimmed","The refcount: content-addressed keys let posts share a blob, so any citation blocks the delete."],
  "app/routes/admin.media._index.tsx#70": ["WHY","race reasoning kept; finding id moved","One statement claims the row only if nothing cites it now. Row first: an orphan object backfills."],
  "app/routes/admin.media._index.tsx#71": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#72": ["WHY","trimmed","The first entry always exists; the empty title is unreachable."],
  "app/routes/admin.media._index.tsx#73": ["CONTRACT","measurement and ruling date moved","Display-only changes (`view`, `size`, `group`) skip the loader; a `sort` change revalidates."],
  "app/routes/admin.media._index.tsx#74": ["WHY","trimmed","A submission always revalidates, so no later edit can make a write invisible."],
  "app/routes/admin.media._index.tsx#75": ["WHY","seam contract and the ceiling kept (admin queue ruling 8); incident moved","Harness seam (admin queue ruling 8): an optional prop with a production default, never\nloaderData. Harness seams are capped at three."],
  "app/routes/admin.media._index.tsx#76": ["WHY","trimmed; the ceiling kept","The third and last harness seam: the bulk-trash confirmation, which a static render cannot open."],
  "app/routes/admin.media._index.tsx#77": ["WHY","already one line"],
  "app/routes/admin.media._index.tsx#78": ["WHY","trimmed","From the URL: `shouldRevalidate` skips the loader for these, so its copy is stale."],
  "app/routes/admin.media._index.tsx#79": ["WHY","measurement moved","From `useNavigation`, so a slow request does not invite a second press. Display changes excluded."],
  "app/routes/admin.media._index.tsx#80": ["WHY","trimmed","The only client state: transient, so never in the URL."],
  "app/routes/admin.media._index.tsx#81": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#82": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#83": ["WHY","trimmed","Shift-range anchor. A ref, so it never renders and cannot differ between server and client."],
  "app/routes/admin.media._index.tsx#84": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#85": ["WHY","already short"],
  "app/routes/admin.media._index.tsx#86": ["WHY","incident moved","`hrefWith` starts from the whole state, so no link can drop a parameter."],
  "app/routes/admin.media._index.tsx#87": ["CONTRACT","already one line"],
  "app/routes/admin.media._index.tsx#88": ["HISTORY","describes the previous subtitle",null],
  "app/routes/admin.media._index.tsx#89": ["WHY","trimmed","A count line: the size of what the reader is about to search."],
  "app/routes/admin.media._index.tsx#90": ["WHY","layout story moved","Actions sit on the heading of the thing they act on."],
  "app/routes/admin.media._index.tsx#91": ["CONTRACT","trimmed","The hidden `intent` alone selects the upload redirect branch. Images only."],
  "app/routes/admin.media._index.tsx#92": ["WHY","trimmed","One button: the label is the affordance."],
  "app/routes/admin.media._index.tsx#93": ["WHY","duplicate of the comment above, trimmed","The input stays a real input and the keyboard path."],
  "app/routes/admin.media._index.tsx#94": ["WHY","trimmed","Intent on the button, so `check:admin-ui` pins the token, not a bare field name."],
  "app/routes/admin.media._index.tsx#95": ["WHY","trimmed","A repair; its form is unchanged, which `check:admin-ui` compares."],
  "app/routes/admin.media._index.tsx#96": ["WHY","trimmed","A plain GET form: the URL is the state and it works without script."],
  "app/routes/admin.media._index.tsx#97": ["WHY","stale Cmd+K note moved","No label or button: the placeholder carries the library's count and Enter submits."],
  "app/routes/admin.media._index.tsx#98": ["WHY","trimmed","Other axes ride as hidden fields, or searching would drop the lens and folder."],
  "app/routes/admin.media._index.tsx#99": ["WHY","ruling narrative moved","aria-hidden: the binding is listed in the shortcuts popover."],
  "app/routes/admin.media._index.tsx#100": ["WHY","trimmed","Attaches to the input by id and renders nothing on the server, so the form still navigates."],
  "app/routes/admin.media._index.tsx#101": ["WHY","trimmed","`roleOf()` derives role, so the hint says no editor exists."],
  "app/routes/admin.media._index.tsx#102": ["WHY","replacement story moved","Lenses ask what folder headings cannot. Role stays reachable as `?role=`."],
  "app/routes/admin.media._index.tsx#103": ["WHY","trimmed","Only on a non-zero count; decorative, so hidden."],
  "app/routes/admin.media._index.tsx#104": ["WHY","trimmed","Trash is a state, like the other lenses."],
  "app/routes/admin.media._index.tsx#105": ["WHY","trimmed","Tags narrow the view; settings live in Display. Rendered only when tags exist."],
  "app/routes/admin.media._index.tsx#106": ["WHY","trimmed","Every control is a link; `<details>` gives the platform's open, close and Escape."],
  "app/routes/admin.media._index.tsx#107": ["WHY","move story removed; prohibition kept","No `name`, so outside the bulk form. Never the bare word \"all\": it reaches only rows shown."],
  "app/routes/admin.media._index.tsx#108": ["WHY","bug narrative moved","Through `sortHref`, so each sort key carries its direction."],
  "app/routes/admin.media._index.tsx#109": ["WHY","trimmed","A link: the default view has an address."],
  "app/routes/admin.media._index.tsx#110": ["WHY","trimmed","`<details>`, so it needs no script. Rows derive from `MEDIA_SHORTCUTS`."],
  "app/routes/admin.media._index.tsx#111": ["WHY","history; JSX comment cannot be deleted","Trash lives in the lens row."],
  "app/routes/admin.media._index.tsx#112": ["WHY","session narration moved","Each lens states its boundary before the reader acts. `Show everything` is a link."],
  "app/routes/admin.media._index.tsx#113": ["WHY","trimmed","Shown whenever the bin is open, even when empty."],
  "app/routes/admin.media._index.tsx#114": ["WHY","trimmed","Many objects at once, so the bulk-delete friction: type the count."],
  "app/routes/admin.media._index.tsx#115": ["WHY","incident moved","A link, not `prompt()`, so the confirmation holds without script."],
  "app/routes/admin.media._index.tsx#116": ["CONTRACT","trimmed","Server-rendered from `?confirm=empty-trash`; the action checks the typed count."],
  "app/routes/admin.media._index.tsx#117": ["WHY","trimmed","Usage is what the renderer emitted, so a route-referenced asset reads as uncited."],
  "app/routes/admin.media._index.tsx#118": ["WHY","history; JSX comment cannot be deleted","The head's count line states the total."],
  "app/routes/admin.media._index.tsx#119": ["WHY","coincidence story moved","Unconditional: the caveat stands between a reader and deleting a served file."],
  "app/routes/admin.media._index.tsx#120": ["WHY","trimmed","When usage cannot be trusted, say so rather than invite a delete."],
  "app/routes/admin.media._index.tsx#121": ["WHY","cursor history moved","Page numbers in the URL, carrying filter and search, so paging keeps the view."],
  "app/routes/admin.media._index.tsx#122": ["WHY","trimmed","Both islands render nothing on the server."],
  "app/routes/admin.media._index.tsx#123": ["WHY","trimmed","Client state: it acts on the selection, which a URL cannot carry."],
  "app/routes/admin.media._index.tsx#124": ["WHY","trimmed","Opened by the action refusing an unconfirmed delete. Cancel is a link, so it needs no script."],
  "app/routes/admin.media._index.tsx#125": ["WHY","trimmed","Opened by the action refusing an unconfirmed rebuild."],
};
