// Ruling 115 decisions, chunk 12: app/db/index.ts blocks 0 to 123.
export default {
  "app/db/index.ts#0": ["CONTRACT", "trimmed", "Public visibility: published, publish_at unset or past. Every public read applies it."],
  "app/db/index.ts#1": ["WHY", "finding id and incident date moved", "Visible subset of these slugs. Ask's cache replay checks it: KV invalidation lags."],
  "app/db/index.ts#2": ["WHY", "section header trimmed", "Blog readers. Every one composes publiclyVisible()."],
  "app/db/index.ts#3": ["CONTRACT", "already short"],
  "app/db/index.ts#4": ["WHY", "reader list and normalisation essay trimmed", "One tag predicate so index, archive and feeds agree. A join would multiply rows."],
  "app/db/index.ts#5": ["CONTRACT", "trimmed", "One tag by slug, or null when no publicly visible post carries it (the archive 404s)."],
  "app/db/index.ts#6": ["CONTRACT", "already short"],
  "app/db/index.ts#7": ["CONTRACT", "type annotation"],
  "app/db/index.ts#8": ["CONTRACT", "trimmed", "Paginated blog index, optionally filtered to one tag, filtered in SQL."],
  "app/db/index.ts#9": ["CONTRACT", "already short"],
  "app/db/index.ts#10": ["WHY", "trimmed", "Filtered in the query, so the shipped HTML is already narrowed."],
  "app/db/index.ts#11": ["WHY", "trimmed", "Via `carriesTag`, shared with the tag archive and its feeds."],
  "app/db/index.ts#12": ["WHY", "latency measurements and rewrite story moved; subquery and tie-break traps kept", "One round trip. The page is a subquery the tag join wraps; joining first would LIMIT\njoined rows. `id DESC` breaks ties, or posts sharing `publish_at` interleave by tag."],
  "app/db/index.ts#13": ["WHY", "trimmed", "Named one by one: drizzle will not select a subquery as a nested object."],
  "app/db/index.ts#14": ["WHY", "incident narrative moved", "Aliased: `posts.slug` and `tags.slug` collide in drizzle's by-name row mapping."],
  "app/db/index.ts#15": ["WHY", "trimmed", "LEFT, so a post with no tags keeps its row."],
  "app/db/index.ts#16": ["WHY", "trimmed", "Both post keys before the tag key, or ties interleave rows of different posts."],
  "app/db/index.ts#17": ["WHY", "trimmed", "COUNT(*) without GROUP BY always returns one row."],
  "app/db/index.ts#18": ["WHY", "trimmed", "One entry per post; the Map keeps the ORDER BY's post and tag order."],
  "app/db/index.ts#19": ["WHY", "already short"],
  "app/db/index.ts#20": ["WHY", "2026-09-10 defect and ruling 57 story moved; hard rule citations kept", "The featured post leads, then the newest others; with nothing featured the newest leads.\nUnlabelled, so not hard rule 13's substituted value. Hard rule 1: composes `isBlogPost()`."],
  "app/db/index.ts#21": ["CONTRACT", "already short"],
  "app/db/index.ts#22": ["WHY", "trimmed", "`cards` others, not `cards - 1`: the extra row leads when nothing is featured."],
  "app/db/index.ts#23": ["WHY", "trimmed", "Which list leads is `startHere`'s rule, shared with `check:microformats`."],
  "app/db/index.ts#24": ["CONTRACT", "trimmed", "Publication years with a post count, newest first, grouped in SQL."],
  "app/db/index.ts#25": ["CONTRACT", "already short"],
  "app/db/index.ts#26": ["CONTRACT", "trimmed", "Series with a publicly visible post, and its count, via `isBlogPost()`."],
  "app/db/index.ts#27": ["WHY", "unasserted count moved", "Series by URL slug, or null; scans `listBlogSeries`. Ambiguous slugs are refused."],
  "app/db/index.ts#28": ["WHY", "trimmed", "One series as cards, oldest part first. Separate so post pages skip the tag join."],
  "app/db/index.ts#29": ["CONTRACT", "already short"],
  "app/db/index.ts#30": ["CONTRACT", "already short"],
  "app/db/index.ts#31": ["WHY", "trimmed", "Neighbours use the same visibility gate, so prev/next cannot reach a draft."],
  "app/db/index.ts#32": ["WHY", "visibility exemption kept, explanation cut", "One draft by slug for a preview link, else null. Exempt from `publiclyVisible()` in\n`VISIBILITY_EXEMPT`: matches `status = 'draft'` only, with the slug from a valid token."],
  "app/db/index.ts#33": ["WHY", "trimmed", "No neighbours: a draft has no place in the visible sequence."],
  "app/db/index.ts#34": ["WHY", "exemption kept; old wording story moved", "All posts for admin, drafts included; exempt from publiclyVisible(), admin only."],
  "app/db/index.ts#35": ["WHY", "deleted-stub story moved; gate visibility, exemption and trash rules kept", "Admin nav counts. Query builder so invariants section 6 sees `.from(posts)`; a named\nvisibility exemption, admin only. Media via `notTrashed()` to match the media page."],
  "app/db/index.ts#36": ["WHY", "trimmed", "So the admin list shows which post is featured."],
  "app/db/index.ts#37": ["WHY", "artifact history moved", "Corpus for `withRelated`, drafts included: it filters candidates itself."],
  "app/db/index.ts#38": ["WHY", "trimmed", "For each neighbour's description in a saved related list; not scored."],
  "app/db/index.ts#39": ["WHY", "artifact arc and boundary note moved; draft rule kept", "Markdown and covers for the citation scan, drafts included: they still block deletion."],
  "app/db/index.ts#40": ["CONTRACT", "trimmed", "Operator list_posts projection, drafts included."],
  "app/db/index.ts#41": ["CONTRACT", "already short"],
  "app/db/index.ts#42": ["WHY", "trimmed", "All post tags, drafts included, for the admin filter; `listBlogTags` hides drafts."],
  "app/db/index.ts#43": ["WHY", "trimmed", "Media annotations. No citations stored here; deletion safety comes from a live scan."],
  "app/db/index.ts#44": ["CONTRACT", "already short"],
  "app/db/index.ts#45": ["CONTRACT", "already short"],
  "app/db/index.ts#46": ["WHY", "old narrower definition story moved", "Unattached: no post or repository code cites it. Shared by the filter and chip count.\n@param templateKeys keys repository code references, from the build artifact"],
  "app/db/index.ts#47": ["WHY", "trimmed", "`NOT IN ()` is a syntax error in SQLite, so an empty list omits the clause."],
  "app/db/index.ts#48": ["WHY", "trimmed", "Free-text filter. `coalesce`: `lower(NULL) LIKE` is NULL and would drop the row."],
  "app/db/index.ts#49": ["WHY", "unasserted counts moved; reconciliation prohibition kept", "Not trashed. Reconciliation readers must skip it, or `check:media` restores the rows."],
  "app/db/index.ts#50": ["NUMBER", "asserted by the constant below", "Large file threshold, stated once for the lens, its count and its label."],
  "app/db/index.ts#51": ["CONTRACT", "trimmed", "ORDER BY for a listing, minus the caller's tie-break.\n@param options the listing options, read for sort, dir and trashed"],
  "app/db/index.ts#52": ["WHY", "trimmed", "Trash view: most recently trashed first, whatever the sort says."],
  "app/db/index.ts#53": ["WHY", "unasserted count moved", "Falls back to the key, or the NULL names would sort as one block."],
  "app/db/index.ts#54": ["WHY", "ruling narrative and R2 comparison moved", "One library page, newest first; `key` keeps offset pagination stable."],
  "app/db/index.ts#55": ["CONTRACT", "already short"],
  "app/db/index.ts#56": ["CONTRACT", "trimmed", "A quality lens: 'unattached' | 'duplicates' | 'no-alt' | 'large'. Else no filter."],
  "app/db/index.ts#57": ["WHY", "trimmed", "Keys repository code references. A parameter: scripts import `app/db` unbundled."],
  "app/db/index.ts#58": ["CONTRACT", "already short"],
  "app/db/index.ts#59": ["CONTRACT", "already short"],
  "app/db/index.ts#60": ["WHY", "trimmed", "Trashed rows only. A flag, not a `role`: trash is orthogonal to role."],
  "app/db/index.ts#61": ["WHY", "live-error story and unasserted count moved", "`role`, not `storage`: logos, favicons and diagram halves must never be inserted."],
  "app/db/index.ts#62": ["WHY", "already short"],
  "app/db/index.ts#63": ["WHY", "trimmed", "A branch, never optional, or trashed assets reappear in the picker."],
  "app/db/index.ts#64": ["WHY", "trimmed", "Pipeline citations only; the card's resolver scan stays the authority."],
  "app/db/index.ts#65": ["WHY", "trimmed", "In SQL because this listing paginates: a post-filter would search one page."],
  "app/db/index.ts#66": ["WHY", "trimmed", "Needle from `exactTagNeedle`; null means no filter, never a match-all `%,,%`."],
  "app/db/index.ts#67": ["WHY", "trimmed", "`duplicates` is not SQL: the route filters it via `mediaTwins`."],
  "app/db/index.ts#68": ["HISTORY", "superseded narrative repeated by the next block", null],
  "app/db/index.ts#69": ["WHY", "trimmed", "Role rank is the default sort only. `key ASC` keeps offset pagination stable."],
  "app/db/index.ts#70": ["WHY", "trimmed", "One extra row answers \"is there another page\" without a COUNT."],
  "app/db/index.ts#71": ["CONTRACT", "already short"],
  "app/db/index.ts#72": ["WHY", "trimmed", "Trashed rows are out, so this matches the grid."],
  "app/db/index.ts#73": ["WHY", "trimmed", "By role. Separate from `mediaCounts` so a broken `roleOf()` shows."],
  "app/db/index.ts#74": ["WHY", "trimmed", "Trashed rows are out, so the role chips add up to the grid."],
  "app/db/index.ts#75": ["WHY", "trash-not-delete and refcount rule kept, explanation cut", "Twins by the key's content hash, exact only. The page offers trash, not delete.\nStatic rows are excluded: their keys are paths."],
  "app/db/index.ts#76": ["HISTORY", "old regex defect story", null],
  "app/db/index.ts#77": ["CONTRACT", "already short"],
  "app/db/index.ts#78": ["WHY", "Unused chip story moved", "All lens counts in one query, on the filters' own predicates. Caller adds `duplicates`."],
  "app/db/index.ts#79": ["WHY", "divergence story moved", "Through `uncited()`, never a copy, so count and filter cannot diverge."],
  "app/db/index.ts#80": ["WHY", "trimmed", "Rows in the trash. Not a pseudo-role: trash is orthogonal to role."],
  "app/db/index.ts#81": ["WHY", "trimmed", "Trashes an asset; R2 untouched. A repeat keeps the first timestamp. Returns if moved."],
  "app/db/index.ts#82": ["CONTRACT", "already short"],
  "app/db/index.ts#83": ["CONTRACT", "already short"],
  "app/db/index.ts#84": ["WHY", "trimmed", "The only tag writer; `serialiseTags` owns the stored form."],
  "app/db/index.ts#85": ["WHY", "unasserted row count moved", "Tag counts, in JS since tags share one delimited column. Trashed rows excluded."],
  "app/db/index.ts#86": ["CONTRACT", "trimmed", "One row by key, for the detail view, which a URL can reach from any page."],
  "app/db/index.ts#87": ["WHY", "trimmed", "Writes derived columns only, named, never spread. Never delete-then-insert: alt,\ncaption and focal point are recoverable from nothing."],
  "app/db/index.ts#88": ["WHY", "queue consumer story moved", "Written when present, never blanked by a caller that cannot measure one."],
  "app/db/index.ts#89": ["WHY", "race story moved", "Written when present, never blanked by a caller with no name."],
  "app/db/index.ts#90": ["CONTRACT", "trimmed", "Creates or updates one object's annotation; the row may not exist yet."],
  "app/db/index.ts#91": ["WHY", "already short"],
  "app/db/index.ts#92": ["WHY", "trimmed", "Drops the row once the object is gone, never to make it go: R2 wins."],
  "app/db/index.ts#93": ["WHY", "finding id and r2_key incident moved; atomicity, order and query-builder rules kept", "Claims a key for deletion in one statement, so no citation lands between the\n`NOT EXISTS` check and the removal. False means refuse. Row before object: R2 wins.\nQuery builder, so column names come from the schema."],
  "app/db/index.ts#94": ["CONTRACT", "already short"],
  "app/db/index.ts#95": ["WHY", "fail-open story moved", "media_refs: written by the pipeline at render, never by a scan."],
  "app/db/index.ts#96": ["CONTRACT", "already short"],
  "app/db/index.ts#97": ["WHY", "trimmed", "Columns both feeds carry, owned once. `id` is for the tag join, stripped after."],
  "app/db/index.ts#98": ["WHY", "trimmed", "Visible posts with markdown, newest first; limited in SQL because bodies are heavy."],
  "app/db/index.ts#99": ["CONTRACT", "already short"],
  "app/db/index.ts#100": ["WHY", "trimmed", "Narrowed in the query: slicing afterwards would cap before narrowing."],
  "app/db/index.ts#101": ["WHY", "trimmed", "By part for a series, oldest first; `id` breaks ties."],
  "app/db/index.ts#102": ["WHY", "trimmed", "Same posts with rendered HTML, for RSS. A sibling, not a union-returning flag."],
  "app/db/index.ts#103": ["CONTRACT", "already short"],
  "app/db/index.ts#104": ["WHY", "duplicate of the full-text reader", "Narrowed in the query, as above."],
  "app/db/index.ts#105": ["WHY", "duplicate of the full-text reader", "Series order, as above."],
  "app/db/index.ts#106": ["CONTRACT", "already short"],
  "app/db/index.ts#107": ["WHY", "item id and gate explanation trimmed", "Webmentions. Section 6 does not see this table; `webmentionTarget` applies visibility."],
  "app/db/index.ts#108": ["WHY", "trimmed", "Statuses the global cap counts, stated once so the cap and the sweep agree."],
  "app/db/index.ts#109": ["WHY", "trimmed", "Can a stranger mention this slug? Composes `isBlogPost()` so drafts cannot be probed.\nReturns a boolean, never the row."],
  "app/db/index.ts#110": ["WHY", "trimmed", "Open mentions; the endpoint refuses at the ceiling."],
  "app/db/index.ts#111": ["WHY", "trimmed", "Writes or resets one (source, target) row, clearing any decision; returns its id.\n`received_at` is set here: the default applies on insert only."],
  "app/db/index.ts#112": ["WHY", "trimmed; hard rule 13 kept", "Unreachable. Not zero, a valid-looking rowid (hard rule 13's shape)."],
  "app/db/index.ts#113": ["CONTRACT", "already short"],
  "app/db/index.ts#114": ["WHY", "trimmed", "Only a row still `unverified` takes a verdict, so a stale fetch cannot overwrite a reset."],
  "app/db/index.ts#115": ["WHY", "gate investigation narrative moved; both hard rule 1 citations kept", "Approved mentions, newest first. The EXISTS on `posts` puts this in section 6's scan,\nso an unpublished post's mentions stay hidden. Hard rule 1 (hard rule 1's second paragraph)."],
  "app/db/index.ts#116": ["CONTRACT", "trimmed", "Every mention, unfiltered, for the admin moderation queue."],
  "app/db/index.ts#117": ["WHY", "trimmed", "Decidable: `unverified` has no evidence and `failed` has evidence against."],
  "app/db/index.ts#118": ["WHY", "trimmed", "Approve or reject one mention. Reversible, so decided rows stay decidable."],
  "app/db/index.ts#119": ["WHY", "trimmed", "Returns the slug from the write so `purgePost` names the moved row; null purges nothing."],
  "app/db/index.ts#120": ["WHY", "trimmed", "Rows the sweep would remove now, on `sweepWebmentions`'s predicates."],
  "app/db/index.ts#121": ["CONTRACT", "already short"],
  "app/db/index.ts#122": ["WHY", "already short"],
  "app/db/index.ts#123": ["WHY", "trimmed", "Retention sweep (windows: webmention/retention.mjs), one statement per window.\nOpen statuses never expire: the global cap counts them."],
};
