// Ruling 115 decisions, chunk 13: scripts/ship.mjs blocks 0 to 95.
export default {
  "scripts/ship.mjs#0": ["CONTRACT", "usage, ordering rules and fail-closed contract kept; incident and prompt history moved", "One command that ships: gates, deploy, prove it, sync.\n\n  npm run ship\n\nDeploy before sync, so `llms.txt` never advertises unserved pages. `check:content` before\nsync, because `sync-content.mjs` runs no gate. Every step fails closed. A missing Version ID\nor sync line exits nonzero. `verify-live` stays separate: its probes are billed."],
  "scripts/ship.mjs#1": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#2": ["WHY", "gitignore reasons shortened", "Gitignored: an untracked log would make the next ship refuse a dirty tree, and the log\ncarries account-scoped ids."],
  "scripts/ship.mjs#3": ["WHY", "age-not-count reason kept in one line", "Pruned by age, never by count: ship's write rate varies, so a count is no fixed duration."],
  "scripts/ship.mjs#4": ["CONTRACT", "re-exec mechanism and boundary kept; origin story moved", "Re-execs ship with piped stdio and tees every chunk to the terminal and the log.\nChildren run with inherited stdio, so wrapping `console` would miss their output.\nRecords what was printed only; it proves nothing about the running Worker.\n\n@returns {Promise<number>} the child's exit code"],
  "scripts/ship.mjs#5": ["WHY", "already short"],
  "scripts/ship.mjs#8": ["WHY", "already short"],
  "scripts/ship.mjs#9": ["WHY", "placement reason shortened", "Printed last and only on failure, where a reader scrolling back finds it first."],
  "scripts/ship.mjs#10": ["WHY", "import-not-literal reason kept; history moved", "Imported from `app/lib/seo.ts`, never restated: a stale copy would poll the wrong host."],
  "scripts/ship.mjs#11": ["WHY", "gate binding kept", "`check:policy` asserts this endpoint and that the step runs between deploy and sync."],
  "scripts/ship.mjs#13": ["CONTRACT", "trimmed", "Refuse, naming the step and the remedy, and exit.\n\n@param {string} why @param {string} remedy\n@returns {never}"],
  "scripts/ship.mjs#15": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#16": ["WHY", "token-before-build rule and secrecy kept", "Checked before the build, so a missing token costs no deploy. Never an argument or printed.\nThe length floor matches `auth.server.ts`."],
  "scripts/ship.mjs#17": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#18": ["WHY", "pull and orphan prohibitions kept; 2026-09-10 incident moved", "Pull `--ff-only`: a merge commit has no CI run. Refuse while another run holds build/client,\nmatched by command line, never by name (all are `node`). Never killed: whose run is unknown."],
  "scripts/ship.mjs#19": ["WHY", "needle owner kept", "Needles live in `child-processes.mjs` so the test imports the list ship uses."],
  "scripts/ship.mjs#20": ["WHY", "shortened", "Cannot verify is not clear: say so rather than pass silently."],
  "scripts/ship.mjs#21": ["WHY", "shortened", "Checked again after the pull: a failed pull can leave files, and this is what gets built."],
  "scripts/ship.mjs#22": ["WHY", "full-sha trap kept", "Full sha: `head_sha=` returns nothing for an abbreviated one."],
  "scripts/ship.mjs#23": ["HISTORY", "deleted-step narrative", null],
  "scripts/ship.mjs#24": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#25": ["WHY", "path-not-deploy safety argument kept; ruling narrative and timings moved", "Green CI for this sha skips the local tier. This read picks a path, never a deploy:\nnon-green takes the local path, and the read at step 4 decides."],
  "scripts/ship.mjs#26": ["WHY", "token requirement kept; measurement moved", "The repo is private, so an unauthenticated read answers 404. The token comes from\n`gh auth token`; without it the CI step refuses."],
  "scripts/ship.mjs#27": ["CONTRACT", "hard rule 10 citation kept", "One read of GitHub's verdict on HEAD. Returns rather than refuses because the two callers\nwant opposite things; a `shouldRefuse` flag is the shape hard rule 10 names.\n\n@returns {Promise<{ verdict: { ok: boolean, why: string, remedy: string } | null, error: string }>}"],
  "scripts/ship.mjs#28": ["WHY", "retry rationale kept; incident moved", "A read, so `retryRead` may retry a transient; the final failure still reaches the catch\nso each caller decides."],
  "scripts/ship.mjs#29": ["WHY", "already short"],
  "scripts/ship.mjs#30": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#31": ["WHY", "refuse-not-apply rule kept; ship window 5 story moved", "No migration may be pending when a deploy goes out. It refuses and never applies: ship cannot\ntell an additive migration from a destructive one. Pending or unreadable both refuse."],
  "scripts/ship.mjs#32": ["WHY", "retry-only-unreadable mechanism kept; incident moved", "`readMigrationList` never throws, so the wrapper throws on `unreadable` only. `pending`\nis a real answer and is not retried."],
  "scripts/ship.mjs#33": ["WHY", "already short"],
  "scripts/ship.mjs#36": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#37": ["WHY", "shortened", "Gitignored and imported statically by routes, so it is built before the app build."],
  "scripts/ship.mjs#38": ["WHY", "shortened", "Gitignored and imported by `about.tsx`; reads stack.json, so it runs after build:stack."],
  "scripts/ship.mjs#39": ["WHY", "silent-404 trap kept; count removed", "Nothing imports the twins, so the build passes without them and `llms.txt` would\nadvertise 404s."],
  "scripts/ship.mjs#40": ["WHY", "already short"],
  "scripts/ship.mjs#41": ["WHY", "shortened", "This build feeds only `check:page-payload`; `npm run deploy` builds what ships."],
  "scripts/ship.mjs#42": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#43": ["HISTORY", "ruling narration; log lines say it", null],
  "scripts/ship.mjs#44": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#45": ["WHY", "fail-closed table and no-override kept; audit history moved", "No run, a run in progress, any non-success, or an unreachable API refuses. No `--force`:\nit would be used on the day the check was right."],
  "scripts/ship.mjs#46": ["WHY", "fresh-read rule kept", "Read fresh on every path, never reused from the early read, so no deploy is authorised by\na stale verdict."],
  "scripts/ship.mjs#47": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#48": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#49": ["WHY", "already short"],
  "scripts/ship.mjs#50": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#51": ["WHY", "ordering and body-read reasons kept; narrative moved", "A 200 from `/colophon` is not health. Runs after the poll so the new build answers, and\nbefore the sync, the first write. `ok` is read from the body; a 429 is reported apart."],
  "scripts/ship.mjs#54": ["WHY", "already short"],
  "scripts/ship.mjs#55": ["WHY", "shortened", "A failing deferred check is printed, not refused; it is asserted after its repair step."],
  "scripts/ship.mjs#56": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#57": ["WHY", "order and miss-not-refusal kept", "After readiness, so the watchdog is never pointed at an unproven build. A failure is a miss,\nnot a refusal: the site deploy has landed, and ship exits nonzero at the end."],
  "scripts/ship.mjs#58": ["CONTRACT", "already short"],
  "scripts/ship.mjs#59": ["WHY", "shortened", "No version ID in the output means the deploy is unproven, even on exit 0."],
  "scripts/ship.mjs#60": ["WHY", "shortened", "Read back from wrangler: a configured cron is not a registered one. A miss, not a refusal."],
  "scripts/ship.mjs#61": ["WHY", "order and miss rule kept; measurement moved", "After readiness, like the watchdog. URLs derive from `SITE_ORIGIN`. A failure is a miss."],
  "scripts/ship.mjs#62": ["CONTRACT", "already short"],
  "scripts/ship.mjs#63": ["WHY", "shortened", "The change count is read, never inferred from exit 0."],
  "scripts/ship.mjs#64": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#65": ["WHY", "shortened", "Rebuilt so the sync reads this ship's build, not whatever a previous run left."],
  "scripts/ship.mjs#66": ["CONTRACT", "already short"],
  "scripts/ship.mjs#67": ["WHY", "discriminator kept", "Render drift finishes every write and stands as a miss; any other nonzero refuses.\nTold apart by the drift line's count, since the exit code carries one bit."],
  "scripts/ship.mjs#68": ["WHY", "confirming-sync mechanism kept; ruling story moved", "First-run drift is usually the old Worker's poll writing an old-renderer hash. A second\nsync reads zero unless the converge write did not take, so only confirmed drift fails."],
  "scripts/ship.mjs#69": ["WHY", "shortened", "The counts line is the proof. `COUNT(*)` on an FTS index reads through to its content table."],
  "scripts/ship.mjs#70": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#71": ["WHY", "order and miss rule kept; measurements moved", "`sync:content` does not rebuild AI Search. It uploads through the deployed Worker, so a miss\nleaves the deploy standing."],
  "scripts/ship.mjs#72": ["CONTRACT", "already short"],
  "scripts/ship.mjs#73": ["CONTRACT", "shortened", "True when convergence came during the poll window, so the write-back counts are not reported."],
  "scripts/ship.mjs#74": ["CONTRACT", "shared-helper contract kept; history moved", "One authenticated operator call, shared by the Ask and media steps. Returns a miss string\nrather than throwing, because every failure here happens after the deploy has landed.\n\n@param {string} tool\n@returns {Promise<{ report: any, miss: string }>}"],
  "scripts/ship.mjs#77": ["WHY", "already short"],
  "scripts/ship.mjs#78": ["WHY", "already short"],
  "scripts/ship.mjs#79": ["WHY", "read-only poll and double bound kept; measurement moved", "AI Search is eventually consistent, so drift is re-read before it is a miss. The re-read is\n`/api/health`, which writes nothing; `sync_ask` would repair what it measures. Bounded by\ncount and deadline."],
  "scripts/ship.mjs#80": ["CONTRACT", "already short"],
  "scripts/ship.mjs#81": ["WHY", "already short"],
  "scripts/ship.mjs#83": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#84": ["WHY", "order and no-poll reason kept; history moved", "After the deploy, since the rebuild reads the serving build. No poll: D1 reads its own writes."],
  "scripts/ship.mjs#85": ["CONTRACT", "already short"],
  "scripts/ship.mjs#86": ["WHY", "already short"],
  "scripts/ship.mjs#87": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#88": ["WHY", "deferral meaning kept; ruling narrative moved", "Deferred checks are asserted here, after their repair: refusing before the sync would\ndeadlock. A failure here means the sync did not converge. A miss, not a refusal."],
  "scripts/ship.mjs#89": ["CONTRACT", "already short"],
  "scripts/ship.mjs#90": ["WHY", "shortened", "One read for all: more requests risk the per-IP limiter's 429."],
  "scripts/ship.mjs#93": ["WHY", "fts-equality exclusion kept; session note moved", "Only deferred rows are consulted; the rest were gated at readiness. `fts-equality` still\ngates at readiness: deferring another check needs a ruling."],
  "scripts/ship.mjs#94": ["CONTRACT", "section divider"],
  "scripts/ship.mjs#95": ["WHY", "all-misses and no-rollback kept", "Nonzero on any miss, after the record. Every miss is named: the faults are independent."],
};
