// Ruling 115 decisions, chunk 14: scripts/check-contrast.mjs blocks 0 to 130.
const F = "scripts/check-contrast.mjs#";
export default {
  [F + 0]: ["CONTRACT", "two-source contract and boundary kept; opacity enumeration and dates moved", "Gate over the shipped colour tokens.\n\n  npm run check:contrast\n\nHexes come from the stylesheet; pairs and thresholds from design-tokens.md, as names, so\nan edited hex fails. WCAG 2.x fails a run; APCA is advisory. Renders nothing."],
  [F + 1]: ["WHY", "already a short why"],
  [F + 2]: ["WHY", "shared-arithmetic why kept; move narrative dropped", "Shared with /playground so both compute ratios by one rule. Only arithmetic is shared."],
  [F + 3]: ["WHY", "file-discovery distinction kept, shortened", "File discovery only; palette parsing stays here, independent of `tokens.mjs`."],
  [F + 4]: ["CONTRACT", "section heading shortened", "Tokens, from the shipped stylesheet"],
  [F + 5]: ["WHY", "trap kept; first-run incident moved", "Strip comments first: the token block's comment names its selectors."],
  [F + 6]: ["WHY", "trap kept; checkout incident moved", "CRLF first: a Windows clone gets CRLF and multi-line matches fail."],
  [F + 7]: ["CONTRACT", "already short"],
  [F + 9]: ["WHY", "why kept, shortened", "Every declaration, in order: a mixed fill ships its hex, then its `color-mix` recipe.\n@type {Record<string, string[]>}"],
  [F + 10]: ["WHY", "already short"],
  [F + 11]: ["CONTRACT", "already short"],
  [F + 13]: ["WHY", "canary trap kept; incident moved", "Canary: the first selector match wins; `--paper` is only in the palette blocks."],
  [F + 15]: ["CONTRACT", "heading shortened", "Assertions"],
  [F + 18]: ["CONTRACT", "already short"],
  [F + 19]: ["WHY", "trap kept, shortened", "Name parity: a token missing from dark keeps its light value there."],
  [F + 20]: ["WHY", "already short"],
  [F + 21]: ["WHY", "rule kept; history of the earlier rule moved", "Each token must resolve through same-block `var()` to a literal hex."],
  [F + 22]: ["CONTRACT", "already short"],
  [F + 24]: ["WHY", "already short"],
  [F + 26]: ["WHY", "why kept, shortened", "A mixed fill's recipe must still produce its hex, one unit per channel."],
  [F + 30]: ["CONTRACT", "heading shortened", "APCA, checked against the published vectors"],
  [F + 31]: ["WHY", "source and sign-convention why kept; upstream detail moved", "apca-w3 0.1.9 keystone vectors, both polarities, so the sign is tested."],
  [F + 32]: ["WHY", "already short"],
  [F + 33]: ["CONTRACT", "heading shortened", "The matrix, from design-tokens.md, as names"],
  [F + 34]: ["WHY", "why kept; measurements moved", "No --fill-* on --bg row: a fill always carries text."],
  [F + 35]: ["WHY", "trailing one-liner"],
  [F + 36]: ["WHY", "trailing one-liner"],
  [F + 37]: ["WHY", "prohibition kept; date moved", "No disabled floor: WCAG exempts inactive components."],
  [F + 38]: ["CONTRACT", "type tag kept"],
  [F + 39]: ["CONTRACT", "row group label"],
  [F + 40]: ["WHY", "shortened", "CodeMirror syntax colours, on --bg and the active line's --surface."],
  [F + 41]: ["WHY", "session reference dropped", "The settings drawer: inputs on --surface inside the popover step."],
  [F + 42]: ["WHY", "why kept; measurements moved", "No --text-disabled on --surface-popover row: it fails there, nothing ships it."],
  [F + 43]: ["WHY", "exemption why kept; ruling narrative moved", "No disabled row: WCAG exempts inactive controls. See NON_PARTICIPATING."],
  [F + 44]: ["CONTRACT", "row group label"],
  [F + 45]: ["WHY", "prohibition kept; measurements and incident moved", "No --border on --surface-popover row: it fails there, so the popover step takes\n--border-strong."],
  [F + 46]: ["CONTRACT", "row group label"],
  [F + 47]: ["WHY", "already short"],
  [F + 48]: ["WHY", "project note dropped", "The admin identity block hovers on the shell surface, not the page."],
  [F + 49]: ["WHY", "already short"],
  [F + 50]: ["WHY", "why kept; retirement note moved", "Chrome text is measured against the chrome, not the page."],
  [F + 51]: ["WHY", "already short"],
  [F + 52]: ["WHY", "why kept, shortened", "Inverted pair: WCAG is symmetric, APCA is not."],
  [F + 53]: ["WHY", "opaque-band why kept; measurements moved", "The caption band is opaque, so the ratio ignores the picture."],
  [F + 54]: ["WHY", "exemption kept; measurements moved", "No --border-strong on --surface-chrome row: a seam has no 3:1 obligation."],
  [F + 55]: ["CONTRACT", "row group label"],
  [F + 56]: ["WHY", "already short"],
  [F + 57]: ["CONTRACT", "row group label"],
  [F + 58]: ["WHY", "already short"],
  [F + 59]: ["CONTRACT", "row group label"],
  [F + 60]: ["CONTRACT", "row group label"],
  [F + 61]: ["CONTRACT", "row group label"],
  [F + 62]: ["WHY", "shortened", "Destructive, on every surface it lands on and its own tint."],
  [F + 63]: ["CONTRACT", "heading kept; ruling and build narrative moved", "Paper, glass, light: pairs from the handoffs, as names"],
  [F + 64]: ["WHY", "already short"],
  [F + 65]: ["WHY", "shortened", "The placeholder must sit below the value that replaces it."],
  [F + 66]: ["WHY", "already short"],
  [F + 67]: ["WHY", "step reference dropped", "A followed link inside an alert tint."],
  [F + 68]: ["WHY", "prohibition kept; deletion narrative moved", "No bar rows: a pair against a surface nothing paints is not coverage (rule 10's class)."],
  [F + 69]: ["WHY", "why kept; measurement moved", "No --dust row on paper: it cannot identify a control; --line-strong does."],
  [F + 70]: ["CONTRACT", "row group label"],
  [F + 71]: ["WHY", "already short"],
  [F + 72]: ["WHY", "why kept; ruling and measurements moved", "Axis and grid take --fig-dust-400: an axis carries meaning, so 1.4.11 applies."],
  [F + 74]: ["WHY", "already short"],
  [F + 75]: ["CONTRACT", "heading shortened", "Resolution: a token used and never declared"],
  [F + 76]: ["WHY", "trap and exemption rule kept; incidents moved", "An undeclared `var()` drops silently, and every pass above walks declarations.\nDECLARED_ELSEWHERE lists tokens set outside CSS, and polices itself."],
  [F + 77]: ["CONTRACT", "type tag kept"],
  [F + 78]: ["WHY", "scope and strip why kept; measurements moved", "All source stylesheets, stripped: app.css prose names the Shiki tokens."],
  [F + 79]: ["WHY", "both-sides scope why kept; stale measurements moved", "Scope, both sides: an empty set on either side fails for the wrong reason."],
  [F + 80]: ["WHY", "already short"],
  [F + 81]: ["CONTRACT", "heading shortened", "Participation: every declared token is measured by some pair"],
  [F + 82]: ["WHY", "why kept; incident moved", "Parity proves a token declared, not measured. Exemptions police themselves."],
  [F + 83]: ["CONTRACT", "type tag kept"],
  [F + 84]: ["WHY", "shortened", "Paper, glass, light tokens with no contrast obligation."],
  [F + 85]: ["WHY", "why kept, shortened", "Unused ramp steps: interiors may sit below 3:1, only edges may not."],
  [F + 87]: ["WHY", "why kept, shortened", "Transitive: a slot declared as `var(--ramp)` measures the ramp step."],
  [F + 88]: ["NUMBER", "asserted floor 53 kept", "Floored at the doc's 53 purpose-named tokens per mode, so an empty parse fails."],
  [F + 89]: ["CONTRACT", "heading shortened", "prefers-contrast: more"],
  [F + 90]: ["CONTRACT", "why shortened; tags kept", "The high-contrast tier is held to the same matrix, so it cannot lower a value.\n@param {string} label\n@param {string} selector"],
  [F + 93]: ["WHY", "already short"],
  [F + 94]: ["WHY", "already short"],
  [F + 95]: ["WHY", "already short"],
  [F + 96]: ["CONTRACT", "heading shortened", "Shiki syntax tokens against the code surfaces"],
  [F + 97]: ["HISTORY", "prior-verification narrative; next block states the contract", null],
  [F + 98]: ["CONTRACT", "shortened; tag kept", "Paired rules are measured on their own background; the rest on both code surfaces.\n@param {any} theme"],
  [F + 101]: ["WHY", "fail-closed exemption kept; upstream measurements moved", "VCS scopes are reported, not counted, only while `diff` is not in LANGUAGES."],
  [F + 104]: ["WHY", "already short"],
  [F + 105]: ["WHY", "already short"],
  [F + 106]: ["CONTRACT", "heading shortened", "The built stylesheet, when present"],
  [F + 107]: ["CONTRACT", "already short"],
  [F + 108]: ["WHY", "why kept; narrowing incident moved", "Newest of every source stylesheet, from `stylesheetPaths()`, not app.css alone."],
  [F + 109]: ["WHY", "why kept; audit measurement moved", "Stale fails, absent does not: editing a source is what makes the build stale."],
  [F + 110]: ["WHY", "already short"],
  [F + 111]: ["WHY", "trap kept; first-run incident moved", "Compare normalised values: Lightning CSS shortens #ffffff to #fff."],
  [F + 114]: ["WHY", "trap kept, shortened", "Slots ship as `var()`, minified without the space after the colon."],
  [F + 115]: ["CONTRACT", "heading shortened", "Report"],
  [F + 116]: ["WHY", "already short"],
  [F + 117]: ["WHY", "why kept, shortened", "Signed Lc: the sign is the polarity. Ranked by magnitude."],
  [F + 118]: ["HISTORY", "floor measurement narrative; later block owns the floor", null],
  [F + 119]: ["CONTRACT", "heading shortened", "Partial opacity on text is refused"],
  [F + 120]: ["WHY", "reveal-pair and every-member rules kept; narrative moved", "Refuses 0 < opacity < 1 unless listed (0 and 1 are a reveal pair). A group is exempt only\nwhen every member matches.\n@type {Array<{ test: RegExp, why: string }>}"],
  [F + 121]: ["WHY", "hard rule 10 citation kept", "Anchored at the end, per hard rule 10: a bare `backdrop` matches `.backdrop-blur`."],
  [F + 122]: ["CONTRACT", "already short"],
  [F + 125]: ["WHY", "shortened", "Scope floor: a regex that stopped matching reports what a clean sweep reports."],
  [F + 126]: ["WHY", "shortened", "An exemption no partial opacity uses is stale and fails."],
  [F + 128]: ["CONTRACT", "heading shortened", "theme-color meta tags copy two tokens"],
  [F + 129]: ["WHY", "why kept, shortened", "root.tsx copies the background hexes. Matched by media query, as a swap is invisible."],
  [F + 130]: ["NUMBER", "asserted floors kept; re-measurement log moved", "Floors: counts from running the gate with build/ present and absent, one under\ncheck:floors' tolerance. Only CI reaches the absent branch."],
};
