// Ruling 115 decisions, chunk 15: scripts/check-all.mjs blocks 0 to 94.
export default {
  "scripts/check-all.mjs#0": ["CONTRACT","usage, boundary and run-everything contract kept; the incident and the gate-count story moved","Runs every gate and reports one table: `npm run check` (offline) or `npm run check:all`.\nIt sees exit codes only, runs every gate even after a failure, and derives the list from\npackage.json so a new gate cannot be forgotten."],
  "scripts/check-all.mjs#1": ["WHY","read-before-truncate and union whys kept; the 2026-09 kill measurements moved","The previous run's samples are read before truncation: after an OS kill they are the only\nrecord of what it held."],
  "scripts/check-all.mjs#2": ["NUMBER","value asserted by the code below; the method stays, the dated 35 to 40 history moved","Fails closed below this. Moves up only to the count a run printed, never to a sum."],
  "scripts/check-all.mjs#3": ["WHY","shortened to one line","check:floors reads the other gates' output, so it is not spawned like them."],
  "scripts/check-all.mjs#4": ["WHY","the dedupe trap kept, trimmed","check:head's stdout carries floor lines measured on a checkout, which would win the dedupe.\n@type {Record<string, string>}"],
  "scripts/check-all.mjs#5": ["CONTRACT","contract kept; the 2026-08-20 measurement moved","Gates a clean checkout cannot run, each with its reason.\n@type {Record<string, string>}"],
  "scripts/check-all.mjs#6": ["WHY","why check:config cannot pass in a checkout, trimmed; verbatim output moved","Bootstrap copies the example, so real equals example and the gate fails in any checkout."],
  "scripts/check-all.mjs#7": ["WHY","why no local D1 is provisioned, trimmed; verbatim error moved","Provisioning a CI D1 would invent the state the backup path is checked against."],
  "scripts/check-all.mjs#8": ["WHY","vacuity reason kept, trimmed","Vacuous in CI: there is only HEAD to compare disk against."],
  "scripts/check-all.mjs#9": ["WHY","the tier call and its ground kept; the 2026-08 falsified reason, ruling dates and timings moved","Public cases need gitignored local D1 content. Kept off ship: a slow preview boot on a loaded\nmachine would fail a ship for a reason that is not the site."],
  "scripts/check-all.mjs#10": ["WHY","why CI does not build the client, trimmed","A CI client build would measure a build nothing deploys."],
  "scripts/check-all.mjs#11": ["CONTRACT","tier contract kept, trimmed","Every discovered gate must be tiered here or the runner refuses to start.\n@type {Record<string, \"offline\" | \"network\" | undefined>}"],
  "scripts/check-all.mjs#12": ["WHY","offline tiering, delegation and ordering whys kept; the 2026-08-20 incident moved","The typecheck is a gate, tiered offline so check:head typechecks an extracted HEAD. It\ndelegates to `npm run typecheck`, which package.json defines."],
  "scripts/check-all.mjs#13": ["WHY","shortened to one line","Network: a decisions volume is a Capsid document."],
  "scripts/check-all.mjs#14": ["WHY","offline reason and the pipeline boundary kept, trimmed","Offline. The network half, `pubs-pipeline`, is never a gate: it would fail on Crossref's bad day."],
  "scripts/check-all.mjs#15": ["WHY","shortened to one line","Offline: reads font binaries and their stylesheets."],
  "scripts/check-all.mjs#16": ["WHY","what it reads kept; the drift incident moved (ruling 111 cited)","Reads its inputs off disk, so `--ci` runs it (ruling 111)."],
  "scripts/check-all.mjs#17": ["WHY","tier caveat and diff-scoring why kept; audit count moved","Scores the diff, not the tree: on the tree its findings here are false positives."],
  "scripts/check-all.mjs#18": ["WHY","network reason and purpose kept, trimmed (ruling 109 cited)","Network: the `updated_at` it compares lives in Capsid (ruling 109)."],
  "scripts/check-all.mjs#19": ["WHY","why it can be offline and its build dependency kept, trimmed","Offline because it renders rather than fetches; it needs the stack.json the preflight builds."],
  "scripts/check-all.mjs#20": ["WHY","shortened to one line","Offline: reads scripts/ as source and runs no wrangler command."],
  "scripts/check-all.mjs#21": ["CONTRACT","boundary kept, trimmed","Sees an axis dropped, not wrong SQL."],
  "scripts/check-all.mjs#22": ["CONTRACT","boundary kept, trimmed","Certifies the last local build, stale or not."],
  "scripts/check-all.mjs#23": ["CONTRACT","already three lines; kept"],
  "scripts/check-all.mjs#24": ["WHY","why it runs in CI kept; date moved","In CI: a guard's scope change fails silently and permissively."],
  "scripts/check-all.mjs#25": ["WHY","in-CI reason kept; incident date moved","In CI: a hook that stops parsing takes the guards with it."],
  "scripts/check-all.mjs#26": ["WHY","in-CI reason kept, trimmed","In CI it reads only the tracked half of the settings, and says so."],
  "scripts/check-all.mjs#27": ["WHY","why it is slow and why check:head excludes it, trimmed","Runs the counting gates to read their floors; check:head excludes it."],
  "scripts/check-all.mjs#28": ["CONTRACT","one line; kept"],
  "scripts/check-all.mjs#29": ["CONTRACT","one line; kept"],
  "scripts/check-all.mjs#30": ["CONTRACT","two lines; kept"],
  "scripts/check-all.mjs#31": ["CONTRACT","boundary kept, trimmed","Cannot see a secret inlined into a client chunk."],
  "scripts/check-all.mjs#32": ["CONTRACT","boundary kept, trimmed","Live database drift is check:invariants --remote."],
  "scripts/check-all.mjs#33": ["CONTRACT","boundary kept, trimmed","Sees uncommitted work and line endings, never the deployed build."],
  "scripts/check-all.mjs#34": ["CONTRACT","already three lines; kept"],
  "scripts/check-all.mjs#35": ["CONTRACT","subject, boundary and the enforced offline guard kept; first-run story moved","Runs the Worker's modules in workerd against local bindings. `test/worker/setup.ts` makes any\noutbound fetch throw, so offline is enforced."],
  "scripts/check-all.mjs#36": ["CONTRACT","already three lines; kept"],
  "scripts/check-all.mjs#37": ["CONTRACT","one line; kept"],
  "scripts/check-all.mjs#38": ["CONTRACT","two lines; kept"],
  "scripts/check-all.mjs#39": ["WHY","shortened to one line","No meaningful offline mode: `--local` reads an empty bucket. Network, always."],
  "scripts/check-all.mjs#40": ["WHY","the two reasons it is not offline and the consequence kept; timing and recommendation moved","Network: the preview server's AI_SEARCH binding reaches a real instance. Ship does not run\nit, so layout defects can ship."],
  "scripts/check-all.mjs#41": ["WHY","vacuity reason kept, trimmed","`--local` would read an empty bucket and report a clean sweep."],
  "scripts/check-all.mjs#42": ["WHY","network reason kept, trimmed","An offline mode could only report that it did not look."],
  "scripts/check-all.mjs#43": ["WHY","why no local form, and why it is weekly, trimmed","A local form would compare two empty databases. Weekly, because it is the slowest gate."],
  "scripts/check-all.mjs#44": ["CONTRACT","already short; kept"],
  "scripts/check-all.mjs#45": ["CONTRACT","already three lines; kept"],
  "scripts/check-all.mjs#46": ["WHY","what --remote adds kept; the fifteen-day incident moved","`--remote` adds the cron triggers registered on the platform."],
  "scripts/check-all.mjs#47": ["CONTRACT","one line; kept"],
  "scripts/check-all.mjs#48": ["CONTRACT","one line; kept"],
  "scripts/check-all.mjs#49": ["WHY","one-derivation and self-invocation whys kept; the colophon story moved","Shared with build-stack.mjs; excluding the runners stops this one invoking itself."],
  "scripts/check-all.mjs#51": ["WHY","the errored-gate rule, its test and its licence kept; incidents and the first-attempt story moved (hard rule 12 citation kept)","A gate that could not run is not a gate that failed. The test is both streams empty: every\ngate here prints on a pass, and an exit-code list missed a real cascade after passing its\nplant (hard rule 12). An errored gate is still not `ok`."],
  "scripts/check-all.mjs#52": ["WHY","shortened to one line","The reason reports the disposition; it never decides it."],
  "scripts/check-all.mjs#53": ["WHY","why the status is a field, trimmed","A number, so the classifier does not parse the reason sentence."],
  "scripts/check-all.mjs#54": ["CONTRACT","null-is-not-zero contract kept, trimmed","Filled in by the caller. Null means not sampled, not zero.\n@type {number | null}"],
  "scripts/check-all.mjs#56": ["WHY","the four conditions and what it does not claim kept; the 2026-09-15 measurements moved (hard rule 10 citation kept)","Environment failure: one machine fact, not N repo facts. All four must hold: both streams\nempty (the only condition that keeps a real failure out), an NTSTATUS-range status, under one\nsecond, and more than one gate with that status. It changes the exit code (2), never the\nverdict. A classifier that calls everything the machine is hard rule 10's unfailable class."],
  "scripts/check-all.mjs#57": ["CONTRACT","shortened to one line","Known on this host; anything else prints as bare hex.\n@type {Record<number, string>}"],
  "scripts/check-all.mjs#59": ["CONTRACT","type contract; kept"],
  "scripts/check-all.mjs#64": ["WHY","one line; kept"],
  "scripts/check-all.mjs#65": ["WHY","order why kept; the ruling 39a history moved","Built first: `build:content` reads stack.json. Not a gate."],
  "scripts/check-all.mjs#66": ["WHY","build-before-read and loud-refusal whys kept, trimmed","Built before any gate reads it (posts.json is gitignored), and refused here: a broken build\nis not a red gate."],
  "scripts/check-all.mjs#67": ["WHY","why the twins are built first, trimmed","Gitignored; check:publications compares it against a fresh generation."],
  "scripts/check-all.mjs#68": ["WHY","why the bundles are built first, trimmed","Gitignored; the app build's `?url` imports need them."],
  "scripts/check-all.mjs#69": ["WHY","derived-exclusion direction kept, trimmed","Derived, so a new gate is in CI unless argued out."],
  "scripts/check-all.mjs#70": ["WHY","already short; kept"],
  "scripts/check-all.mjs#71": ["WHY","preflight purpose and the by-pid prohibition kept; the 2026-09-09 measurement moved","Preflight: tree-kill what the previous run left alive. By pid, never by name: a name match\nfor `node` or `chrome` reaches Dustin's own editor and browser."],
  "scripts/check-all.mjs#72": ["WHY","one-read liveness why kept; the 47-kill incident moved","One process table read: a `taskkill` per dead pid makes later gates fail to start."],
  "scripts/check-all.mjs#73": ["WHY","already short; kept"],
  "scripts/check-all.mjs#74": ["CONTRACT","what it covers and what it cannot, trimmed","Kills this run's tree on exit and signals; an OS kill is covered by the next preflight."],
  "scripts/check-all.mjs#75": ["WHY","two lines; kept"],
  "scripts/check-all.mjs#77": ["WHY","why check:floors is fed rather than spawned, trimmed; the timing moved","Runs last and reads the captured output instead of re-running the tier."],
  "scripts/check-all.mjs#78": ["WHY","the marker, its citation and the partial-map why kept, trimmed","JUSTIFIED SUBSTITUTION (hard rule 13). Partial on purpose: absence means no extra args."],
  "scripts/check-all.mjs#79": ["WHY","two lines; kept"],
  "scripts/check-all.mjs#80": ["WHY","window-closing why kept, trimmed","Closes after the gate returns, so its dying children count against it."],
  "scripts/check-all.mjs#81": ["WHY","why gates are passed and only passes are fed, trimmed","Fed only passing gates' output; `gates` is passed separately because a silent gate leaves no\ntrace in the text."],
  "scripts/check-all.mjs#82": ["WHY","two lines; kept"],
  "scripts/check-all.mjs#83": ["WHY","two lines; kept"],
  "scripts/check-all.mjs#84": ["WHY","shortened to one line","Failing output in full, after the run, where it is read."],
  "scripts/check-all.mjs#85": ["WHY","shortened to one line","Correlated first, so one machine event is not buried under its own banners."],
  "scripts/check-all.mjs#86": ["WHY","trimmed to the rule","Errored gates get their own block; a correlated event is listed once under its banner."],
  "scripts/check-all.mjs#87": ["WHY","unfailable-branch why kept, trimmed (hard rule 10 citation kept)","An errored gate has no output by definition; a branch for it could not fire (hard rule 10)."],
  "scripts/check-all.mjs#88": ["WHY","two lines; kept"],
  "scripts/check-all.mjs#89": ["WHY","trimmed","Peak memory and the gate holding it are what an out-of-memory kill needs."],
  "scripts/check-all.mjs#91": ["WHY","shortened to one line","An errored run exits nonzero: a ship must never read \"0 failed\" off it."],
  "scripts/check-all.mjs#92": ["WHY","exitCode-not-exit and the explicit cleanUp why kept; the 2026-09-13 investigation moved","Exit code set, not taken: process.exit() can cut the report short. cleanUp() is explicit\nbecause the live sampler would keep the exit handler from ever running."],
  "scripts/check-all.mjs#93": ["WHY","shortened to one line","Two is the machine, one is the repo; a real failure outranks an environment event."],
  "scripts/check-all.mjs#94": ["WHY","guard purpose and the pathToFileURL trap kept, trimmed","Main guard, so check:floors can import `TIERS`. `pathToFileURL`, because a hand-built\n`file://C:\\...` URL never equals import.meta.url on Windows."],
};
