// Ruling 115 decisions, chunk 2: scripts/check-browser.mjs blocks 108 to 259.
export default {
  "scripts/check-browser.mjs#108": ["CONTRACT", "section marker shortened", "0b. a public document depends on the theme alone"],
  "scripts/check-browser.mjs#109": ["WHY", "cache-key precondition and run-mode limits kept; measurements moved", "Keying the public cache on path plus theme is sound only if public bytes depend on\nthe theme alone. The nonce is masked: it differs per request by design."],
  "scripts/check-browser.mjs#110": ["CONTRACT", "short; subject set bound to source", "Every route exporting the shared cache headers; checked against the source below."],
  "scripts/check-browser.mjs#111": ["WHY", "tag choice kept, shortened", "The most-carried tag, so one post being retagged cannot remove the case."],
  "scripts/check-browser.mjs#112": ["HISTORY", "efc0dab drift narrative", null],
  "scripts/check-browser.mjs#113": ["WHY", "canonical slash kept, shortened", "The trailing slash is canonical; the slashless form redirects."],
  "scripts/check-browser.mjs#114": ["WHY", "exemption reason kept; tutorial cut", "Shared-cached HTML with no corpus URL; a 404 would compare two error pages."],
  "scripts/check-browser.mjs#115": ["WHY", "comment-stripping trap kept, shortened", "`preview.$token.tsx` names the constant only in prose, so comments are stripped first."],
  "scripts/check-browser.mjs#116": ["WHY", "exemption grounds kept; dated join history moved", "Shared-cached but not HTML: no `<html data-theme>` for a theme to reach."],
  "scripts/check-browser.mjs#117": ["CONTRACT", "mask intent kept; measurement moved", "What differs between two renders by design: nonce, report endpoint, health age.\n\n@param {string} html"],
  "scripts/check-browser.mjs#118": ["WHY", "why here and not maskTheme kept; incident moved", "The age sentence differs between same-cookie renders (KV edge cache plus clock), so\nit is masked here and not in `maskTheme`. The health-tile case asserts the age."],
  "scripts/check-browser.mjs#120": ["CONTRACT", "already short"],
  "scripts/check-browser.mjs#123": ["CONTRACT", "enumeration intent kept, shortened", "What the theme may change; after masking, the documents must be identical."],
  "scripts/check-browser.mjs#125": ["WHY", "why the meta is masked kept; date moved", "The color-scheme meta carries the theme by design; its own case asserts the value."],
  "scripts/check-browser.mjs#126": ["HISTORY", "aria-pressed removal narrative", null],
  "scripts/check-browser.mjs#127": ["WHY", "hard rule 8 citation kept; reasoning shortened", "The age sentence is not here: hard rule 8 scopes this to what the theme may change."],
  "scripts/check-browser.mjs#128": ["WHY", "shortened", "The footer assertions below need a rendered page."],
  "scripts/check-browser.mjs#129": ["CONTRACT", "section marker shortened", "consistent help: the privacy link on every public page"],
  "scripts/check-browser.mjs#130": ["WHY", "3.2.6 order requirement kept, shortened", "WCAG 2.2 3.2.6: order is asserted as well as presence."],
  "scripts/check-browser.mjs#131": ["WHY", "shortened", "Without this, both assertions below pass on a site that stopped rendering the theme."],
  "scripts/check-browser.mjs#132": ["WHY", "same-document and scope-first kept", "The document just compared, not a new fetch. Section presence is asserted first."],
  "scripts/check-browser.mjs#133": ["WHY", "already short"],
  "scripts/check-browser.mjs#134": ["CONTRACT", "section marker shortened", "the cache itself is verify-live's"],
  "scripts/check-browser.mjs#135": ["WHY", "why skipped kept; port history moved", "Miniflare does not implement Workers Cache; `verify-live` owns the cache assertions."],
  "scripts/check-browser.mjs#136": ["CONTRACT", "section marker shortened", "negotiated routing, which needs no cache"],
  "scripts/check-browser.mjs#137": ["WHY", "scope limit kept; incident moved", "Routing only, which needs no cache; `verify-live` measurement (a) owns the cache half."],
  "scripts/check-browser.mjs#138": ["WHY", "shortened", "`no-store` keeps the platform from storing it under the HTML reader's key."],
  "scripts/check-browser.mjs#139": ["CONTRACT", "section marker shortened", "the browser learns the colour scheme before CSS"],
  "scripts/check-browser.mjs#140": ["WHY", "cause and why-not-pixels kept; measurements moved", "Without a color-scheme meta the browser paints a light canvas between pages. Screencast\nand screenshots cannot see that frame, so the document property is asserted."],
  "scripts/check-browser.mjs#141": ["CONTRACT", "why both-values kept, shortened", "No choice resolves to `light dark`, so the machine decides."],
  "scripts/check-browser.mjs#142": ["WHY", "legacy cookie kept; date moved", "Legacy `theme=system` cookies must resolve as no cookie."],
  "scripts/check-browser.mjs#145": ["WHY", "position rationale kept, shortened", "Before the first stylesheet, not at a fixed index: React 19 orders the metas."],
  "scripts/check-browser.mjs#146": ["WHY", "rule 17 pairing kept, shortened", "The meta and the stylesheet state one fact (rule 17), so they are checked to agree."],
  "scripts/check-browser.mjs#147": ["CONTRACT", "section marker shortened", "a public navigation runs no view transition"],
  "scripts/check-browser.mjs#148": ["WHY", "cause and two-half assertion kept; measurements moved", "Chrome's root crossfade blinks full-document navigations, so the ViewTransition must\nbe null. `pagereveal` must also fire, or an unattached listener would pass."],
  "scripts/check-browser.mjs#149": ["WHY", "binding choice kept; first-version story moved", "An exposed binding, reinstalled per document, rather than sessionStorage."],
  "scripts/check-browser.mjs#153": ["WHY", "trap kept; attempt narrative moved", "An activated prerender is a separate target the probe never ran in."],
  "scripts/check-browser.mjs#154": ["WHY", "breakpoint trap kept; incident moved", "The header nav is hidden below 64rem, and a hidden link clicks at (0,0)."],
  "scripts/check-browser.mjs#155": ["HISTORY", "hover rationale narrative", null],
  "scripts/check-browser.mjs#156": ["WHY", "zero-box trap and fallback kept; defect report moved", "A hidden element's zero box clicks the document corner, so it fails. Falls back to\nthe overflow menu's copy; fails if neither is laid out."],
  "scripts/check-browser.mjs#158": ["WHY", "already short"],
  "scripts/check-browser.mjs#159": ["WHY", "already short"],
  "scripts/check-browser.mjs#160": ["CONTRACT", "section marker shortened", "speculation rules, as Chrome parses them"],
  "scripts/check-browser.mjs#161": ["WHY", "never assert activation kept; measurements moved", "Chrome refuses to prerender under CDP, so `activationStart` is always 0: never assert\nit. The candidate list is Chrome's own reading of the rules."],
  "scripts/check-browser.mjs#165": ["WHY", "already short"],
  "scripts/check-browser.mjs#167": ["WHY", "already short"],
  "scripts/check-browser.mjs#171": ["WHY", "shortened", "`/colophon` is reached from the footer."],
  "scripts/check-browser.mjs#173": ["WHY", "shortened", "Link counts are proven non-empty first."],
  "scripts/check-browser.mjs#175": ["WHY", "stripComments trap kept; measurement moved", "Do not spell the glob here: `stripComments` reads a slash-star in a string as a\ncomment opener, hiding `ok()` calls from `check:invariants` section 17."],
  "scripts/check-browser.mjs#178": ["WHY", "reason kept; incident moved", "The cases below read the current page and expect /blog."],
  "scripts/check-browser.mjs#179": ["CONTRACT", "section marker shortened", "no layout shift while the font arrives"],
  "scripts/check-browser.mjs#180": ["WHY", "placement, throttle and null-observer kept; measurements moved", "Throttled, or a local font arrives in time and CLS can never fail. A missing observer\nreturns null, which fails."],
  "scripts/check-browser.mjs#183": ["WHY", "already short"],
  "scripts/check-browser.mjs#185": ["CONTRACT", "section marker shortened", "1. the search field and the column"],
  "scripts/check-browser.mjs#186": ["WHY", "alignment-not-literal kept; measurement moved", "Aligned with a sibling, not the literal 48rem app.css owns."],
  "scripts/check-browser.mjs#188": ["CONTRACT", "section marker shortened", "2. the skip link target"],
  "scripts/check-browser.mjs#189": ["WHY", "shortened", "A skip link with no target is a keyboard trap."],
  "scripts/check-browser.mjs#190": ["CONTRACT", "section marker shortened", "3. aria-current is not on Blog on a post"],
  "scripts/check-browser.mjs#191": ["WHY", "shortened", "`NavLink` without `end` marks Blog current on every `/blog/*` page."],
  "scripts/check-browser.mjs#192": ["CONTRACT", "section marker shortened", "4. no horizontal scroll at 320px"],
  "scripts/check-browser.mjs#193": ["WHY", "why every page and named element kept; measurement moved", "Every page, since shared chrome can overflow. The failure names the element."],
  "scripts/check-browser.mjs#194": ["WHY", "shortened; date moved", "`/playground` boxes scroll by design; the page must not."],
  "scripts/check-browser.mjs#195": ["WHY", "already short"],
  "scripts/check-browser.mjs#196": ["CONTRACT", "section marker shortened", "4a. maths must not drag the document"],
  "scripts/check-browser.mjs#197": ["WHY", "paired control and hard rule 4 kept, shortened", "Paired controls: the box must really overflow and the sheet be linked. A mathless\npost links no sheet, which is hard rule 4's half on the wire."],
  "scripts/check-browser.mjs#198": ["WHY", "shortened", "Every refusal is the same 404, so the door is asserted open first."],
  "scripts/check-browser.mjs#199": ["WHY", "hoisting trap kept; incident moved", "React 19 `precedence` hoists the sheet above the color-scheme meta."],
  "scripts/check-browser.mjs#200": ["WHY", "already short"],
  "scripts/check-browser.mjs#201": ["WHY", "shortened", "KaTeX declares no colour, so it must compute to the `.prose` colour."],
  "scripts/check-browser.mjs#202": ["WHY", "workaround kept; version measurement moved", "Through CDP: puppeteer's `emulateMediaFeatures` rejects `forced-colors`."],
  "scripts/check-browser.mjs#203": ["CONTRACT", "section marker shortened", "control: a mathless post links nothing extra"],
  "scripts/check-browser.mjs#204": ["CONTRACT", "section marker shortened", "4b. the playground demos answer on the wire"],
  "scripts/check-browser.mjs#205": ["WHY", "Hard rule 7 kept, shortened", "check:features cannot see the transport (Hard rule 7), such as the Worker's WASM\ninstantiator. Expectations come from the manifest."],
  "scripts/check-browser.mjs#206": ["CONTRACT", "already short"],
  "scripts/check-browser.mjs#207": ["WHY", "shortened", "The page must be the playground with every declared section."],
  "scripts/check-browser.mjs#210": ["CONTRACT", "section marker shortened", "the key grammar, on the wire"],
  "scripts/check-browser.mjs#212": ["WHY", "shortened", "A caught throw that renders nothing looks like a working page."],
  "scripts/check-browser.mjs#214": ["CONTRACT", "section marker shortened", "the theme resolver, on the wire"],
  "scripts/check-browser.mjs#215": ["WHY", "shortened", "\"system\" appears in prose; \"omitted\" appears only in this row."],
  "scripts/check-browser.mjs#216": ["CONTRACT", "section marker shortened", "the markdown pipeline, on the wire"],
  "scripts/check-browser.mjs#217": ["WHY", "shortened", "workerd refuses `WebAssembly.instantiate()` on raw bytes; only a Worker sees this."],
  "scripts/check-browser.mjs#218": ["WHY", "shortened", "Shiki's token spans are absent when the WASM module failed."],
  "scripts/check-browser.mjs#219": ["WHY", "shortened", "Checked on the DOM's own links."],
  "scripts/check-browser.mjs#221": ["CONTRACT", "section marker shortened", "5. the login skip link"],
  "scripts/check-browser.mjs#222": ["CONTRACT", "section marker shortened", "5b. the enhancements run, and nothing else ships"],
  "scripts/check-browser.mjs#223": ["WHY", "rule 9 half, Ask exclusion and console check kept; date moved", "Rule 9's \"fast with it\" half, which fails silently. The Ask stream is not driven\nbecause it bills. Console errors are asserted empty at the end, where CSP refusals show."],
  "scripts/check-browser.mjs#226": ["WHY", "shortened", "Stems from app/enhance/, since build/client may be another build's."],
  "scripts/check-browser.mjs#227": ["WHY", "shortened", "Found by walking the listing, since a pinned slug goes stale."],
  "scripts/check-browser.mjs#228": ["CONTRACT", "both directions kept; size history moved", "The blog bundle loads on a post and not on the index.\n\n@param {string} stem"],
  "scripts/check-browser.mjs#231": ["WHY", "already short"],
  "scripts/check-browser.mjs#232": ["WHY", "already short"],
  "scripts/check-browser.mjs#233": ["CONTRACT", "section marker shortened", "WCAG 2.2 1.4.13, on a post with footnotes"],
  "scripts/check-browser.mjs#234": ["WHY", "why a browser gate and found-post kept; defect story moved", "Hoverable, dismissible, persistent (WCAG 1.4.13). The post is found, not named."],
  "scripts/check-browser.mjs#235": ["WHY", "already short"],
  "scripts/check-browser.mjs#236": ["WHY", "shortened", "Straight to the bubble's centre; a gap step would test the grace period."],
  "scripts/check-browser.mjs#237": ["WHY", "already short"],
  "scripts/check-browser.mjs#238": ["WHY", "already short"],
  "scripts/check-browser.mjs#239": ["CONTRACT", "section marker shortened", "WCAG 2.2 4.1.3, the copy controls announce"],
  "scripts/check-browser.mjs#240": ["WHY", "observable limit kept; defect story moved", "Asserted on the `role=\"status\"` region; speech is not observable."],
  "scripts/check-browser.mjs#241": ["WHY", "trap kept; narrative moved", "The cases below navigate for themselves."],
  "scripts/check-browser.mjs#242": ["WHY", "already short"],
  "scripts/check-browser.mjs#243": ["WHY", "trap kept; plant story moved", "A dead bundle lets the form navigate; the destroyed-context throw is the finding."],
  "scripts/check-browser.mjs#244": ["WHY", "shortened", "The hidden twin must be `display: none`, not `.sr-only`, measured via `offsetParent`."],
  "scripts/check-browser.mjs#247": ["WHY", "already short"],
  "scripts/check-browser.mjs#249": ["WHY", "serialization trap kept; incident moved", "A DOMRect serializes as an empty object, so return plain numbers."],
  "scripts/check-browser.mjs#253": ["WHY", "shortened", "Clicked by what is visible; by value could pick the hidden button."],
  "scripts/check-browser.mjs#254": ["WHY", "shortened", "Top level, so no return; dependent cases are skipped by name."],
  "scripts/check-browser.mjs#258": ["WHY", "shortened", "The visible button now offers light: the cascade re-resolved."],
  "scripts/check-browser.mjs#259": ["WHY", "rule 9 fallback and fragment limit kept; history moved", "Rule 9's fallback, with JavaScript disabled. Only the path is asserted: `Referer`\nnever carries a fragment."],
};
