// Ruling 115 decisions, chunk 3: scripts/check-browser.mjs blocks 260 to 340.
export default {
  "scripts/check-browser.mjs#260": ["WHY", "trimmed", "Clear the theme cookie the scripted case left, so this page loads as a first-time reader's."],
  "scripts/check-browser.mjs#262": ["WHY", "mechanism kept; crash incident moved", "Click the button just read as visible, never by position: the shared cookie jar may have\nhidden the first one, and puppeteer throws on a hidden element."],
  "scripts/check-browser.mjs#263": ["WHY", "trimmed", "Reported, not asserted: the fragment is unreachable by construction, so a failure here\nwould be permanent and say nothing about the code."],
  "scripts/check-browser.mjs#264": ["CONTRACT", "intent kept; retired-shortcut history moved", "The palette: clicking the trigger opens it. The hint is server-rendered `hidden` and\nunhidden only once the listener exists."],
  "scripts/check-browser.mjs#265": ["WHY", "trap kept; date moved", "The hint must exist and be unhidden (a missing hint makes `!hidden` true), and the anchor's\n`aria-describedby` must resolve to it, or no screen reader reads it."],
  "scripts/check-browser.mjs#266": ["WHY", "mechanism kept; retired-key history moved", "The title must name the live key. `-K` rather than the whole chord, because the modifier is\nCommand on a Mac and Control elsewhere."],
  "scripts/check-browser.mjs#267": ["WHY", "prohibition and hard rule citation kept; six-week story moved", "The announced text must name the same key; length alone is hard rule 10's unfailable\ncondition."],
  "scripts/check-browser.mjs#268": ["WHY", "mechanism kept; before-and-after story moved", "The palette bundle is fetched only on the first gesture. Counted from the resource timeline,\nnot the DOM, because a fetch is what rule 4 grades; matched loosely past the content hash."],
  "scripts/check-browser.mjs#269": ["WHY", "trimmed; ruling history moved", "Clicked, not typed: the click is the gesture every reader has."],
  "scripts/check-browser.mjs#270": ["WHY", "trimmed", "Polled, not slept: opening costs a network round trip for the bundle, so a fixed wait races."],
  "scripts/check-browser.mjs#271": ["WHY", "already short"],
  "scripts/check-browser.mjs#272": ["WHY", "mechanism kept", "The dialog arrives styled: its CSS loads on demand, and an unstyled `<dialog open>` still\npasses the open check. Compared against the `--border` token, never a literal."],
  "scripts/check-browser.mjs#273": ["WHY", "intent kept; 2026-09-13 incident moved", "The query survives the gesture: type a real query, submit it, and the resulting URL must\ncarry it. A control that lands on a bare /search fails here."],
  "scripts/check-browser.mjs#274": ["WHY", "trap kept; incident moved", "Typed through a handle, not `page.type`, which throws on a missing field and voids the run."],
  "scripts/check-browser.mjs#275": ["WHY", "already short"],
  "scripts/check-browser.mjs#276": ["WHY", "already short"],
  "scripts/check-browser.mjs#277": ["WHY", "unasserted cold-query measurement moved", "The debounce and a cold D1 query both outlast a fixed wait; poll instead."],
  "scripts/check-browser.mjs#278": ["WHY", "both halves and the raw-comparison trap kept; narration cut", "The image link, both states. Without script the image's parent is an anchor whose href\nserves an image (a 200 with an image type, not a well-formed string). With script the\noverlay shows the anchor's href, compared raw, attribute to attribute: `currentSrc` is\nabsolute, so the raw form discriminates on any image."],
  "scripts/check-browser.mjs#279": ["WHY", "mechanism and boundary kept; crawl history moved", "The subject comes from the on-disk artifact, over the whole corpus, not a capped crawl. A\ndeployed origin may lack a named post, so a candidate without the anchor skips, not fails."],
  "scripts/check-browser.mjs#283": ["WHY", "dated content measurement moved", "No body image in the corpus is a content fact, not a defect, so this skips loudly."],
  "scripts/check-browser.mjs#284": ["WHY", "already short"],
  "scripts/check-browser.mjs#285": ["WHY", "mechanism kept; before-state history moved", "A real modal dialog, asserted through `matches(\"dialog:modal\")`, which only `showModal()`\nsatisfies: attributes on a div are a claim, modality is a behaviour."],
  "scripts/check-browser.mjs#286": ["WHY", "already short"],
  "scripts/check-browser.mjs#287": ["CONTRACT", "trimmed", "The script set per page: enhancement bundles only, no framework, no modulepreload. The wire\nhalf of check:page-payload."],
  "scripts/check-browser.mjs#288": ["CONTRACT", "section header, capitals dropped", "------------------------------- 6. the admin plane, opt-in, deployed only"],
  "scripts/check-browser.mjs#289": ["WHY", "scope warning kept; outage story moved", "Catches markup that renders while a component never mounts. These cases observe\nADMIN_ORIGIN, a deployed Worker; every other case observes the preview build."],
  "scripts/check-browser.mjs#290": ["CONTRACT", "three states kept; narration cut", "Only an absent credential is a skip. A supplied but unusable one fails, with a message\nnaming the repair:\n\n  malformed  the cookie cannot be used; fix the format.\n  no origin  a session was supplied and there is nowhere to send it.\n  rejected   the server said no, usually an expired session; refill the file."],
  "scripts/check-browser.mjs#291": ["HISTORY", "vol 15 story and floor history; the ok() message states the refusal", null],
  "scripts/check-browser.mjs#292": ["WHY", "trimmed", "State which credential ran: the smoke token is read-only, so its green says nothing about\nwrites; the cookie is Dustin, so its green says nothing about CI."],
  "scripts/check-browser.mjs#295": ["CONTRACT", "section header"],
  "scripts/check-browser.mjs#296": ["WHY", "trimmed", "The shell (sidebar and topbar) is the assertion, not the title, which survives an empty\nbody. The login page is named, because a bounced session renders a complete page."],
  "scripts/check-browser.mjs#297": ["WHY", "scope reason kept; ruling 21 date moved", "Asserts only that the route renders in the shell and fits, not its structure: this observes\na deployed Worker, and structure is check:admin-ui's, which renders the working tree."],
  "scripts/check-browser.mjs#298": ["CONTRACT", "section header"],
  "scripts/check-browser.mjs#299": ["WHY", "mechanism kept; split history moved", "The mark's base fill (app.css) and header override (styles/public-chrome.css) sit in two\nfiles; both are asserted as resolved colour against the token, never a hex, because\n@import order decides which wins."],
  "scripts/check-browser.mjs#301": ["CONTRACT", "section header, capitals dropped", "----------------------------------------- 6c. the mount class"],
  "scripts/check-browser.mjs#302": ["CONTRACT", "section header; history word cut", "------------------------------------- 6d. the media interactions ---"],
  "scripts/check-browser.mjs#303": ["WHY", "read-only prohibition kept; split story moved", "Four interactions on /admin/media that check:admin-ui cannot see, since it renders without\nscripts or styles. Nothing here submits, under either credential: the cookie path runs as\nDustin. Unreachable confirmations are on the remaining-human list below."],
  "scripts/check-browser.mjs#304": ["CONTRACT", "section header"],
  "scripts/check-browser.mjs#305": ["WHY", "trimmed", "Sorted by size, not the default, so a header that hardcodes its active column fails."],
  "scripts/check-browser.mjs#306": ["WHY", "trap kept; wrong-first-draft story moved", "Every sortable cell is an anchor, so sorting has an address. Not every href carries `sort=`:\n`hrefWith` omits a parameter equal to its default."],
  "scripts/check-browser.mjs#307": ["WHY", "trimmed", "`aria-sort=\"none\"` on the others tells a screen reader they can be sorted."],
  "scripts/check-browser.mjs#308": ["CONTRACT", "section header"],
  "scripts/check-browser.mjs#309": ["WHY", "trimmed", "The key comes off the page, never a fixture: the bucket owns it and may delete it."],
  "scripts/check-browser.mjs#310": ["CONTRACT", "section header"],
  "scripts/check-browser.mjs#311": ["WHY", "trimmed", "Selection is client state, so this is a real click. The size is the half worth asserting:\na sum over the wrong subset still renders a plausible number."],
  "scripts/check-browser.mjs#312": ["WHY", "already short"],
  "scripts/check-browser.mjs#313": ["WHY", "already short"],
  "scripts/check-browser.mjs#314": ["CONTRACT", "section header"],
  "scripts/check-browser.mjs#315": ["WHY", "prohibition and mechanism kept; sub-headings cut", "The empty-trash ladder, the one confirmation a GET reaches; the others open from\n`actionData` and need a POST. The required string is read off the page, not computed. It\nnever submits: the enabled state is the assertion. An empty trash is a reported skip."],
  "scripts/check-browser.mjs#316": ["WHY", "already short"],
  "scripts/check-browser.mjs#318": ["WHY", "already short"],
  "scripts/check-browser.mjs#319": ["CONTRACT", "section header"],
  "scripts/check-browser.mjs#320": ["WHY", "sampling reason kept; measurements and repair narrative moved", "The admin plane at the widths the public pages are gated at. Several widths, because the\noverflow is linear in the viewport; 1280 catches a fix that collapses desktop. Do not narrow\nthis to pass on a partial fix."],
  "scripts/check-browser.mjs#321": ["WHY", "scope reason kept; dated re-read moved", "`/admin/*` loads a second sheet, `app/admin.css`, and a layout measurement on an unstyled page\nmeasures browser defaults. A rule count proves bytes arrived; the computed style proves the\ncascade applied them."],
  "scripts/check-browser.mjs#322": ["NUMBER", "widths appear in the list below; dates moved", "582 is the measured floor, on the fold boundary; 375 is the common phone width."],
  "scripts/check-browser.mjs#323": ["WHY", "trimmed; ruling reference moved", "The mentions queue puts chips, an excerpt and three buttons on one line."],
  "scripts/check-browser.mjs#324": ["WHY", "already short"],
  "scripts/check-browser.mjs#325": ["WHY", "trimmed", "The bar itself fits: an ancestor with `overflow: hidden` would clip its children while the\ndocument does not scroll."],
  "scripts/check-browser.mjs#326": ["WHY", "three mechanisms kept; found-defect story moved", "The fold keeps every action: narrow may add controls but never lose one. Compared by\naccessible name, since a swap holds a count steady. Opened via the `open` property, as a\nscriptless `<summary>` click does, because rule 9 is about the markup."],
  "scripts/check-browser.mjs#327": ["CONTRACT", "already short"],
  "scripts/check-browser.mjs#330": ["WHY", "already short"],
  "scripts/check-browser.mjs#331": ["WHY", "already short"],
  "scripts/check-browser.mjs#332": ["WHY", "already short"],
  "scripts/check-browser.mjs#333": ["WHY", "floor purpose kept; measurements moved", "Executed-count floor, one per mode, measured by running the gate, never summed. A browser gate\nhas many ways to examine nothing: a 404, a stale selector, an error page."],
  "scripts/check-browser.mjs#334": ["HISTORY", "dated re-measurement log; floors are asserted in code below", null],
  "scripts/check-browser.mjs#335": ["WHY", "trimmed", "Only if something was measured: an unreachable subject would print `0 checks, 0 failures`,\nwhich reads as a pass. The exit code is already 1."],
  "scripts/check-browser.mjs#336": ["NUMBER", "floors asserted below; dated measurements moved", "Two floors, one per mode, because CI runs both: the preview and the deployed site. Each floor sits\n`max(3, ceil(count * 0.05))` under a run; check:floors never sees this network-tier gate,\nso re-measure when touching this file."],
  "scripts/check-browser.mjs#337": ["WHY", "trimmed", "Name what was not covered on the last line, the one that gets read."],
  "scripts/check-browser.mjs#338": ["WHY", "prohibition kept", "What still needs a human, printed every run. Widening the read-only credential to reach the\nby-construction items would grant the authority the design withholds; they stay human."],
  "scripts/check-browser.mjs#339": ["WHY", "trap and hard rule citation kept; date moved", "The breach is folded into `failures`, which the exit code is computed from; setting\n`process.exitCode` alone is overwritten by the assignment below."],
  "scripts/check-browser.mjs#340": ["WHY", "trimmed; ruling citation moved", "The floor name carries the mode, so each reading is judged against its own floor."],
};
