// Ruling 115 decisions, chunk 4: scripts/check-invariants.mjs blocks 0 to 142.
const F = "scripts/check-invariants.mjs#";
export default {
  [F + "0"]: ["CONTRACT", "usage and boundary kept; section list, B002 and r2_key incident moved", "Gate over rules stated twice, in different languages or runtimes, that cannot merge.\n\n  npm run check:invariants\n  npm run check:invariants -- --remote    adds the live database\n\nIt catches divergence between the two copies, not whether the rule is right.\nSection 2 carries hard rule 1; section 4 carries hard rule 11.\nEvery section asserts its fixture and scan are non-empty."],
  [F + "1"]: ["CONTRACT", "purpose and limit kept; hoisting and first-draft story moved", "Blanks whole-line `#` comments so an assertion cannot match YAML prose.\nTrailing `#` is left alone: a naive pass would cut strings.\n\n@param {string} src\n@returns {string}"],
  [F + "2"]: ["WHY", "trap kept, shortened", "Strings are blanked too: this file quotes the patterns it hunts."],
  [F + "5"]: ["WHY", "section divider shortened", "helpers"],
  [F + "6"]: ["CONTRACT", "already short"],
  [F + "7"]: ["WHY", "exclusion reason kept, shortened", "Gitignored build output, excluded by full path so a source `dist` elsewhere is walked."],
  [F + "10"]: ["WHY", "already a short trap"],
  [F + "11"]: ["WHY", "mechanism kept, shortened", "CommonJS, so one Proxy stub satisfies any named import at runtime."],
  [F + "12"]: ["WHY", "section divider shortened", "1. no second bucketFor"],
  [F + "13"]: ["CONTRACT", "shape and non-match kept", "A conditional choosing `.OG` or `.MEDIA`. Walking both buckets is not this shape."],
  [F + "14"]: ["WHY", "section divider shortened", "2. publiclyVisible vs visibilityClause"],
  [F + "15"]: ["CONTRACT", "fixture intent and clock trap kept; first-version story moved", "Every post state, drafts included. `NOW` comes from `publiclyVisible()`'s own params,\nbecause the two halves read the clock differently."],
  [F + "17"]: ["WHY", "shortened", "The drizzle half renders to SQL without a database."],
  [F + "18"]: ["WHY", "binding mechanism kept, shortened", "A `timestamp` binds as epoch seconds; a Date is normalised in case that changes."],
  [F + "20"]: ["WHY", "already short"],
  [F + "22"]: ["WHY", "shortened", "A predicate admitting everything or nothing proves nothing."],
  [F + "23"]: ["WHY", "section divider shortened", "3. the two resolveImage paths"],
  [F + "24"]: ["CONTRACT", "scope and placeholder rule kept; B002 narrative moved", "Only `/media/` srcs are pure functions of the key. Neither resolver may give them a\nplaceholder; the proxy env below throws on any binding read."],
  [F + "25"]: ["WHY", "shortened", "A key without dimensions must fail on both sides."],
  [F + "26"]: ["WHY", "shortened", "Throws if a resolver reaches a binding for a `/media/` src."],
  [F + "28"]: ["WHY", "shortened", "Same size with different placeholders is still two documents."],
  [F + "30"]: ["WHY", "shortened", "Agreement is not correctness: both inventing a placeholder fails."],
  [F + "32"]: ["WHY", "rule kept; earlier-version story moved", "A count, never an unconditional verdict."],
  [F + "33"]: ["WHY", "section divider shortened", "4. the column schema, three ways"],
  [F + "34"]: ["CONTRACT", "three sources and derivation kept; r2_key incident moved", "Hard rule 11: columns from schema.ts, the migrations on an empty database, and live D1.\nAll derived, no column list here. Virtual, shadow and `sqlite_%` tables are excluded."],
  [F + "35"]: ["CONTRACT", "owner pointer kept; lift date moved", "@param {{name: string, sql: string | null}[]} tables"],
  [F + "37"]: ["WHY", "already short"],
  [F + "39"]: ["WHY", "subsection divider shortened", "source 1: schema.ts, through drizzle"],
  [F + "42"]: ["WHY", "subsection divider shortened", "source 2: the migrations"],
  [F + "47"]: ["WHY", "subsection divider shortened", "schema.ts vs migrations"],
  [F + "48"]: ["WHY", "subsection divider shortened", "the indexes"],
  [F + "49"]: ["WHY", "scope and exclusions kept; added date and headings moved", "Hard rule 11 for indexes: names and ordered columns. Partial predicates, collations and\ndirections are skipped, drizzle cannot express them. Implicit indexes go by `origin`."],
  [F + "55"]: ["WHY", "already short"],
  [F + "57"]: ["WHY", "shortened", "An empty side makes every comparison below pass vacuously."],
  [F + "59"]: ["WHY", "exposure kept; section 5 deletion history moved", "Unmodelled tables have no column check; printed as an exposure."],
  [F + "60"]: ["WHY", "subsection divider shortened", "source 3: live database"],
  [F + "61"]: ["WHY", "Windows traps kept; round-trip timing moved", "One quoted `--command`: on Windows args arrays split, `shell: false` cannot run `.cmd`,\nand `--file` returns one result set under `--json`."],
  [F + "62"]: ["WHY", "throw trap kept; review story moved", "`spawnSync` returns on failure, so the status is thrown or `retryRead` never retries."],
  [F + "65"]: ["WHY", "section divider shortened", "4a. search_docs is never queried through drizzle"],
  [F + "66"]: ["WHY", "ban, reason and exit kept; dates and headings moved", "Hard rule 1 for `search_docs` is section 8's raw-SQL scan; section 6 knows only `posts`.\nSo `searchDocs` in a query position is banned. To allow one, teach section 6 first."],
  [F + "68"]: ["WHY", "scope reason kept; unasserted measurement and draft story moved", "An empty walk reports the same as a clean repo."],
  [F + "69"]: ["WHY", "shortened", "Prove the needle can fire."],
  [F + "70"]: ["WHY", "retired section divider shortened", "5. removed"],
  [F + "71"]: ["WHY", "gap and remaining matcher kept; measurements and ruling moved", "Removed: its literal matcher desyncs on regex literals. No gate checks raw-SQL column names.\nSections 7 and 8 guard hard rules 2 and 1."],
  [F + "72"]: ["WHY", "section divider shortened", "6. every posts reader composes the predicate"],
  [F + "73"]: ["WHY", "chokepoint, exemption shape and write scope kept; measurements moved", "Hard rule 1 at the caller: every `.from(posts)` is in `app/db/index.ts`, and each function\nthere composes the predicate unless exempt by function name. Writes are out of scope."],
  [F + "74"]: ["CONTRACT", "shortened", "Allowed to read `posts` without the predicate, each with a reason."],
  [F + "75"]: ["CONTRACT", "contract kept; 2026-08-11 sweep moved", "Local names for `posts`, aliases included, so an alias cannot hide a hard rule 1 reader.\n\n@param {string} code comment-stripped source\n@returns {string[]} local binding names"],
  [F + "76"]: ["WHY", "trap kept; first-draft story moved", "The path may be empty: strings are already blanked."],
  [F + "77"]: ["WHY", "already short"],
  [F + "78"]: ["CONTRACT", "already short"],
  [F + "80"]: ["WHY", "already short"],
  [F + "81"]: ["WHY", "prohibition kept; measurement moved", "Not `joinConcatenatedLiterals`: it breaks the column-0 braces."],
  [F + "82"]: ["WHY", "shortened", "An empty alternation matches every `.from()`."],
  [F + "83"]: ["CONTRACT", "contract and CRLF trap kept; incident moved", "Column-0 `function` to column-0 `}`. CRLF first, or no body ever closes.\n\n@param {string} source comment-stripped source"],
  [F + "84"]: ["WHY", "scoping rule kept; discovery moved", "Exempt by file and function, never by file."],
  [F + "85"]: ["CONTRACT", "already short"],
  [F + "86"]: ["WHY", "already short"],
  [F + "87"]: ["WHY", "shortened", "Every query must land in an extracted body; asserted below."],
  [F + "88"]: ["WHY", "floor rationale kept; dated measurements moved", "Floors catch a broken matcher, not one legitimate removal."],
  [F + "89"]: ["WHY", "shortened", "A stale exemption is unaudited permission."],
  [F + "90"]: ["WHY", "section divider shortened", "7. no DELETE FROM or COUNT(*) on an FTS index"],
  [F + "91"]: ["WHY", "both traps kept; measurements and headings moved", "Hard rule 2: `DELETE FROM` corrupts an fts5 index, and `COUNT(*)` reads the content table so\nit cannot see drift. The rest of hard rule 2 is gated elsewhere. The index list is derived."],
  [F + "93"]: ["WHY", "tripwire reason kept", "A fourth index means re-measure; zero means the classifier broke."],
  [F + "94"]: ["WHY", "replacement reason kept; plant and measurements moved", "Scans whole source, not extracted literals, which desync on regex literals and hid a\nhard rule 2 violation. Occurrence is all this needs."],
  [F + "97"]: ["WHY", "guard reason kept; discovery moved", "Empty, DELETE_FTS would match every `DELETE FROM`."],
  [F + "98"]: ["WHY", "shortened", "This file names what it forbids."],
  [F + "99"]: ["WHY", "shortened", "Scope: SQL-ish matches."],
  [F + "100"]: ["WHY", "guard reason kept; plant moved", "An empty alternation matches everything."],
  [F + "101"]: ["WHY", "shortened", "Show the match, not the file head."],
  [F + "103"]: ["WHY", "trap kept; discovery moved", "Matches, not literals: concatenation merges several into one."],
  [F + "104"]: ["WHY", "scope reason kept; measurements moved", "A broken walk reports zero violations. Hard rule 10."],
  [F + "105"]: ["WHY", "intent kept; enumeration history moved", "The FTS drift checks must not disappear."],
  [F + "106"]: ["WHY", "section divider shortened", "8. every search_docs reader composes the predicate"],
  [F + "107"]: ["WHY", "gap and two levels kept; audit story moved", "Hard rule 1 for raw-SQL `search_docs` reads, which section 6 cannot see: directly via\n`visibilityClause(...)` or via `filters.clause`, whose builder is asserted too."],
  [F + "108"]: ["WHY", "classification traps kept", "Per literal: `DELETE FROM search_docs` contains `FROM search_docs`; `runIndex` uses `JOIN`."],
  [F + "109"]: ["CONTRACT", "already short"],
  [F + "111"]: ["WHY", "granularity reason kept; first-version story moved", "Per query, not per function: `zeroState` runs two."],
  [F + "112"]: ["WHY", "shortened", "Resolve `prepare(sql)` to its assignment, or the main readers are missed."],
  [F + "113"]: ["WHY", "bounded-risk tripwire kept; measurements moved", "`LITERALS` is blind to regex literals, so it is safe only while no `prepare()` argument\nholds one. Asserted here."],
  [F + "114"]: ["WHY", "scope reason kept; stale count moved", "Tight: a small set cannot absorb slack."],
  [F + "115"]: ["CONTRACT", "shortened", "Named, so a new reader cannot match by accident.\n\n@type {Record<string, string>}"],
  [F + "116"]: ["WHY", "shortened", "An exemption no longer needed fails."],
  [F + "117"]: ["WHY", "already short"],
  [F + "118"]: ["WHY", "section divider shortened", "9. trash hides from the library, not from R2"],
  [F + "119"]: ["WHY", "both failure directions kept, shortened", "Runs `notTrashed()` on the real migrations. Too narrow shows trash in the library; too\nwide makes `check:media` backfill the row."],
  [F + "120"]: ["WHY", "shortened", "Two brand rows, so a broken role count reads 2, not nothing."],
  [F + "125"]: ["WHY", "shortened", "Anti-vacuity first."],
  [F + "126"]: ["WHY", "shortened", "Or `check:media` undoes the trash."],
  [F + "127"]: ["WHY", "shortened", "Restore, as a round trip on the column."],
  [F + "128"]: ["WHY", "already short"],
  [F + "129"]: ["WHY", "shortened", "The only place the migration runs."],
  [F + "133"]: ["WHY", "guard and assertion boundaries kept", "The delete claim keeps its `NOT EXISTS` guard. The behavioural half runs a model of it."],
  [F + "136"]: ["WHY", "reason kept; plant story moved", "Bulk deletes must call the guard; `check:admin-ui` stubs `.server` and cannot see it."],
  [F + "137"]: ["WHY", "rule kept; plant and media_refs story moved", "Bulk tagging must call `serialiseTags`, the one tag writer."],
  [F + "138"]: ["WHY", "hard rule citation kept; removal narrative moved", "No direct `tags` write assertion: its firing could not be shown (hard rule 10)."],
  [F + "139"]: ["WHY", "section divider shortened", "report"],
  [F + "140"]: ["WHY", "numbering rule kept; deletion story moved", "Section 10 is retired; its number is not reused."],
  [F + "141"]: ["WHY", "section divider shortened", "11. the drift badge reads a cache"],
  [F + "142"]: ["WHY", "properties kept; latency measurements and incident moved", "On a cache hit `askDriftCount` returns before any index reference; asserted on source\norder, which an instrument cannot bypass. Every index mutator drops the cached count."],
};
