// Ruling 115 decisions, chunk 5: scripts/check-invariants.mjs blocks 143 to 252.
export default {
  "scripts/check-invariants.mjs#145": ["WHY", "scope-first reason kept; tutorial cut", "Scope first: every assertion below passes on an empty extraction."],
  "scripts/check-invariants.mjs#146": ["WHY", "trimmed", "Order, not presence; both are asserted present before positions are compared."],
  "scripts/check-invariants.mjs#147": ["WHY", "prohibition kept; measured incident moved", "The late write goes on `ctx.waitUntil`, never floating: Workers may cancel work after the\nresponse. Both directions, so a floating `void listing` beside it also fails."],
  "scripts/check-invariants.mjs#148": ["WHY", "trap kept; three-week incident moved", "A failed upload's key still joins `live`: the prune deletes owned keys not in `live`, so\nomitting it would delete the good indexed copy."],
  "scripts/check-invariants.mjs#149": ["WHY", "mechanism kept; first-version story moved", "Position is not reachability: a `continue` in the catch keeps the text order and skips\n`live.add`, so the assertion reads what lies between the two."],
  "scripts/check-invariants.mjs#150": ["WHY", "prohibition and hard rule 12 kept; heredoc story moved", "No backslash here: an escaped boundary can reach disk as a backspace byte (hard rule 12)."],
  "scripts/check-invariants.mjs#151": ["WHY", "trimmed to one line", "The loader only: `askStatusContext` is still set by middleware and read by /admin/posts."],
  "scripts/check-invariants.mjs#152": ["WHY", "trimmed", "A mutator that keeps the cached count leaves the badge stale until the TTL."],
  "scripts/check-invariants.mjs#153": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#154": ["CONTRACT", "rule and scope kept; regression history moved", "`root.tsx` renders the skip link on every route, so any route rendering its own `<main>`\nmust give it `id=\"main\"`. Source only; check:browser measures reachability."],
  "scripts/check-invariants.mjs#156": ["WHY", "scope reason kept; incident count moved", "Scope: an empty walk or an over-eager stripper also reports no offenders."],
  "scripts/check-invariants.mjs#157": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#158": ["CONTRACT", "rule, builders and exemption policy kept; 2026-08-20 measurement moved", "Public meta comes from `pageMeta` or `postSocial`, because hand-copied literals drift.\nAdmin and the named exemptions are noindex; exemptions are names, never a pattern."],
  "scripts/check-invariants.mjs#159": ["CONTRACT", "already short"],
  "scripts/check-invariants.mjs#161": ["WHY", "scope reason kept; incident count moved", "Scope: an empty walk also reports nothing hand-rolled."],
  "scripts/check-invariants.mjs#162": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#163": ["CONTRACT", "decidable rule and why-not-derive kept; 2026-08-20 finding moved", "`STATIC_PATHS` mirrors `routes.ts`. Every route before `// Auth` that is `.tsx` with no\n`:param` must be in it or in `SITEMAP_EXEMPT`, or the page is silently unlisted."],
  "scripts/check-invariants.mjs#164": ["CONTRACT", "already short"],
  "scripts/check-invariants.mjs#165": ["WHY", "trimmed", "Public block only. The `// Auth` marker is a comment, so it is found on the raw source."],
  "scripts/check-invariants.mjs#167": ["WHY", "trimmed", "Scope: an empty parse reports nothing missing; a lost `// Auth` marker is how it shrinks."],
  "scripts/check-invariants.mjs#168": ["WHY", "binding kept; 2026-08-28 measurement moved", "No writer can produce a `kind = 'page'` row, which is why the sitemap has no branch for one.\nA writer that starts inserting one fails here instead of publishing an unlisted page."],
  "scripts/check-invariants.mjs#169": ["WHY", "mechanism and hard rule 10 kept; first-draft story and counts moved", "Presence and absence, not a read of VALUES, which `sync-content.mjs` builds from fragments.\nThe CHECK constraint (section 4) admits only 'page' or 'post'.\nHard rule 10: the INSERT needle is anchored, or it also matches `posts_fts`."],
  "scripts/check-invariants.mjs#171": ["WHY", "scope reason kept; unasserted count moved", "Scope: a needle that stopped matching reports no offending writer."],
  "scripts/check-invariants.mjs#172": ["WHY", "trimmed", "No slack: one statement per writer, so a vanished writer must fail."],
  "scripts/check-invariants.mjs#173": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#174": ["CONTRACT", "assertion and stated gap kept with citations; audit history moved", "Every `hard rule N` citation must resolve to a `### N.` heading in CLAUDE.md. Paraphrases\n(of hard rule 3, hard rule 9, hard rule 10, hard rule 15) are not checked."],
  "scripts/check-invariants.mjs#175": ["WHY", "trimmed", "Normalized for matching so CRLF cannot hide a needle; raw for the size on disk."],
  "scripts/check-invariants.mjs#176": ["WHY", "truncation reason kept; absorption history and dropped-check list moved", "The harness silently truncates CLAUDE.md, which would hide the hard rules from a session."],
  "scripts/check-invariants.mjs#177": ["WHY", "trimmed", "Scope: with no headings `ordinal` is -1 and the check below fails for the wrong reason."],
  "scripts/check-invariants.mjs#178": ["WHY", "needle trap kept", "Matched on \"append-only\": the sentence recording the unfreeze contains \"frozen\"."],
  "scripts/check-invariants.mjs#179": ["CONTRACT", "already short"],
  "scripts/check-invariants.mjs#180": ["WHY", "trimmed", "Scope: an empty `defined` set would report every citation as a broken comment."],
  "scripts/check-invariants.mjs#181": ["WHY", "floor reasoning and both hard rule 10 citations kept; raise history moved", "A floor, since numbering is append-only; one below the defined count is hard rule 10's\nover-wide threshold, in the gate that binds hard rule 10."],
  "scripts/check-invariants.mjs#183": ["WHY", "list-needle reason and citation kept; discovery story moved", "Reads lists (\"Hard rules 7, 10 and 12\"), bounded to digits, commas and \"and\"."],
  "scripts/check-invariants.mjs#184": ["WHY", "trimmed", "Root documents are in scope and named, because `sourceFiles` walks only code."],
  "scripts/check-invariants.mjs#185": ["CONTRACT", "already short"],
  "scripts/check-invariants.mjs#186": ["NUMBER", "floors asserted in code; measurements and plant story moved", "Floors come from running this walk, never from counting files on disk."],
  "scripts/check-invariants.mjs#187": ["WHY", "reason and hard rule 10 kept; first-draft story moved", "The scanned floor cannot see the root documents drop out (hard rule 10's over-wide\nthreshold). CLAUDE.md defines rules and cites none, so only VERIFICATION.md must cite."],
  "scripts/check-invariants.mjs#188": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#189": ["CONTRACT", "contract and both-directions reason kept; rule 6 history and per-rule survey moved", "Rules 4, 6, 13 and 14 make falsifiable claims about the tree. Each is asserted both ways:\nthe claim is still written, and the code still has the property."],
  "scripts/check-invariants.mjs#190": ["CONTRACT", "already short"],
  "scripts/check-invariants.mjs#192": ["WHY", "trimmed", "Scope first: a broken extractor would read as four rule defects."],
  "scripts/check-invariants.mjs#196": ["CONTRACT", "subsection header"],
  "scripts/check-invariants.mjs#197": ["CONTRACT", "subsection header"],
  "scripts/check-invariants.mjs#198": ["WHY", "rule and shape reason kept; old-login story moved", "`/login` is public, so rule 9 applies: a posting form with a submit, and an action to\nreceive it."],
  "scripts/check-invariants.mjs#199": ["CONTRACT", "subsection header"],
  "scripts/check-invariants.mjs#200": ["WHY", "reason kept; plant story moved", "Counts occurrences, not files: a second construction in the same file is the defect\nrule 6 describes."],
  "scripts/check-invariants.mjs#201": ["CONTRACT", "subsection header"],
  "scripts/check-invariants.mjs#202": ["WHY", "exclusion reason and prohibition kept; first-run story moved", "This file's message contains the marker, so it is excluded by exact path, never a pattern."],
  "scripts/check-invariants.mjs#203": ["CONTRACT", "subsection header"],
  "scripts/check-invariants.mjs#204": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#205": ["CONTRACT", "derivation and boundary kept; move history moved", "CI runs the derived `check:ci` tier, never a hand list that forgets the next gate, and reads\nNode from `.nvmrc`. It reads a file: it cannot see that CI ran."],
  "scripts/check-invariants.mjs#206": ["HISTORY", "first-draft plant story; the why moves to the next line, the limit lives at module scope", null],
  "scripts/check-invariants.mjs#207": ["WHY", "dated note replaced by the why from the block above", "Comments are stripped before matching (`stripHashComments`): a step's comment names `npm ci`."],
  "scripts/check-invariants.mjs#208": ["WHY", "trimmed", "Scope: the file must be non-trivial before any match means anything."],
  "scripts/check-invariants.mjs#209": ["WHY", "binding and floor-not-pin kept; 2026-08-23 drift and audit story moved", "The engines floor equals the `.nvmrc` pin CI runs; a floor, so patch releases install."],
  "scripts/check-invariants.mjs#210": ["CONTRACT", "subsection header"],
  "scripts/check-invariants.mjs#211": ["CONTRACT", "three properties and boundary kept; incident reference moved", "The only alert that reaches a human unprompted: it must exist, poll the health route, and\npin its checkout by sha. It cannot see a run fire."],
  "scripts/check-invariants.mjs#212": ["WHY", "trimmed", "Both ways: no `uses:` line may end in a version tag, since a pinned action beside a floating\none passes the positive check."],
  "scripts/check-invariants.mjs#213": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#214": ["CONTRACT", "class, both rules and boundary kept; audit history and measurements moved", "Helper-signature drift: with two argument orders, a copied call puts a truthy string in the\ncondition slot and never fails. One signature per helper, and no string conditions."],
  "scripts/check-invariants.mjs#215": ["WHY", "trimmed", "Fails closed on a broken directory read; floored under the count, which moves."],
  "scripts/check-invariants.mjs#217": ["WHY", "trimmed to one line", "Scope: no definitions means the matcher stopped matching."],
  "scripts/check-invariants.mjs#218": ["CONTRACT", "already short"],
  "scripts/check-invariants.mjs#220": ["CONTRACT", "already short"],
  "scripts/check-invariants.mjs#221": ["WHY", "trailing note, already short"],
  "scripts/check-invariants.mjs#223": ["NUMBER", "floor asserted in code; three re-measurement narratives moved", "Scope: no calls reads like no string conditions. Floored about 13 percent under a count\ntaken by running this gate."],
  "scripts/check-invariants.mjs#224": ["WHY", "reason kept; date moved", "Printed so the floor above can be re-measured without editing the gate."],
  "scripts/check-invariants.mjs#225": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#226": ["CONTRACT", "binding and boundary kept; consolidation history moved", "No step can drop out of `CUTOVER.md`, and its `SITE_ORIGIN` must match `app/lib/seo.ts`.\nIt cannot tell whether any step was performed."],
  "scripts/check-invariants.mjs#227": ["WHY", "trimmed", "Scope: a stub would read as every step missing."],
  "scripts/check-invariants.mjs#228": ["WHY", "trimmed", "Named, not counted, so one item cannot be swapped for another."],
  "scripts/check-invariants.mjs#230": ["WHY", "anchoring reason and hard rule 10 kept; plant and audit story moved", "The HSTS revisit step. Needles are anchored (hard rule 10's unanchored-needle class), and\n`preload` must sit within the HSTS step because the word has other uses here."],
  "scripts/check-invariants.mjs#231": ["WHY", "trimmed", "The binding: the origin the code uses against the one the checklist names."],
  "scripts/check-invariants.mjs#232": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#233": ["CONTRACT", "assertions, sha exclusion and boundary kept", "FAILURES.md is useful because it is short. Cited paths resolve; commit shas do not, because\nCI clones at depth 1."],
  "scripts/check-invariants.mjs#234": ["WHY", "trimmed", "Scope: an empty file parses to zero shapes and every per-shape check passes."],
  "scripts/check-invariants.mjs#236": ["NUMBER", "limits asserted in code; 2026-08-21 measurement moved", "The ceiling is the point: ordinary additions fit, a page that tells stories does not."],
  "scripts/check-invariants.mjs#237": ["WHY", "trimmed", "An uncited shape is a claim a reader cannot check."],
  "scripts/check-invariants.mjs#239": ["WHY", "prefix rule kept; first-run story moved", "A `capsid:` prefix is required, never inferred, so a deleted repo path cannot pass as one."],
  "scripts/check-invariants.mjs#240": ["WHY", "trimmed", "Asserted: a lesson nobody meets is not recorded."],
  "scripts/check-invariants.mjs#241": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#242": ["CONTRACT", "assertion and limit kept; 2026-08-21 measurement moved", "Every admin route exporting a `loader` calls `timed(` or is in `NO_TIMING_NEEDED`.\nIt counts a call, not coverage."],
  "scripts/check-invariants.mjs#243": ["CONTRACT", "JSDoc type, already short"],
  "scripts/check-invariants.mjs#244": ["WHY", "trimmed", "Scope: a glob that stopped matching reports every loader instrumented."],
  "scripts/check-invariants.mjs#246": ["WHY", "trimmed", "Exemptions are checked both ways: a vanished file, or one that calls `timed()`, is stale."],
  "scripts/check-invariants.mjs#247": ["HISTORY", "detached floor re-measurement log; the floor and its why live at the end of the file", null],
  "scripts/check-invariants.mjs#248": ["CONTRACT", "section header"],
  "scripts/check-invariants.mjs#249": ["WHY", "order property and scoping kept; audit reference moved", "`savePost` commits before it writes D1: a D1 write first could describe a post on no commit,\nwhile a D1 failure after is repairable. A reorder looks like a tidy, so it fails here."],
  "scripts/check-invariants.mjs#250": ["WHY", "trimmed to one line", "Brace matching, so the body cannot spill into the functions below it."],
  "scripts/check-invariants.mjs#251": ["WHY", "trimmed", "The other direction: no new D1 write may appear before the commit."],
  "scripts/check-invariants.mjs#252": ["WHY", "one-owner reason and both directions kept; 2026-08-25 history moved", "`mediaRefKey` owns the dedup key: a printable separator merges refs, and the delete guard\ncan then drop a cited blob. Both ways: helper called, no template join."],
};
