// Ruling 115 decisions, chunk 6: scripts/check-invariants.mjs blocks 253 to 343.
export default {
  "scripts/check-invariants.mjs#253": ["CONTRACT","section heading"],
  "scripts/check-invariants.mjs#254": ["CONTRACT","two-halves contract kept; argument trimmed","The home page's proof tiles report measurements and never state them (rule 17).\nTwo halves, since either alone passes a defect: each source is read, and the tile markup\ncarries no numeric literal. Comments are stripped because this file's prose is full of digits."],
  "scripts/check-invariants.mjs#255": ["WHY","invariant kept; 2026-08-26 needle move and timings moved","The verdict is read through `readHealthTile`; the loader must never run the suite, which\nis what made the home page slow. The negative half keeps that true."],
  "scripts/check-invariants.mjs#256": ["WHY","invariant kept; ruling 57 needle history moved","The count comes from a query composing `publiclyVisible()`, never a literal or a page length.\nBoth binding names pass: the property is the source, not the variable name."],
  "scripts/check-invariants.mjs#257": ["WHY","trap kept, trimmed","Bounded by the section element, not a character window, which reads a neighbour's compliance."],
  "scripts/check-invariants.mjs#258": ["WHY","needle intent kept, trimmed","A number as rendered text or as a whole attribute value is the defect.\nDigits inside identifiers like `h2` or `sha256` are ignored."],
  "scripts/check-invariants.mjs#259": ["CONTRACT","composition contract kept; artifact arc history moved","`renderAndWrite` -> `syncPostToD1` is the only live writer of a post's derived rows, so its\nbatch composition is asserted: a dropped spread silently stops posts entering search.\nSource scan, comments stripped: it sees a spread absent, not one present and wrong."],
  "scripts/check-invariants.mjs#260": ["CONTRACT","scope and blind spots kept; dated arc narrative moved","An unhydrated route renders once on the server, so a client hook in its tree is dead code.\nIts module graph may not import state or lifecycle hooks from \"react\" nor client hooks from\n\"react-router\"; render-time hooks are allowed.\nReads import clauses only (`import type` ignored); a namespace or renamed hook is invisible.\nThe unhydrated set is derived: route files minus `hydrate: true` and the admin children."],
  "scripts/check-invariants.mjs#261": ["CONTRACT","short doc comment"],
  "scripts/check-invariants.mjs#263": ["CONTRACT","short doc comment"],
  "scripts/check-invariants.mjs#264": ["WHY","one-line why"],
  "scripts/check-invariants.mjs#265": ["CONTRACT","type with meaning"],
  "scripts/check-invariants.mjs#269": ["CONTRACT","binding contract kept; 2026-08-29 subject move and measurement moved","`HEALTH_POLL_INTERVAL_SECONDS` restates the watchdog's cron (a Worker cannot read another's\nconfig), so the two are compared (rule 17). The cron is parsed: equivalent forms must agree.\nReads the tracked example; `check:config` binds it to the real config.\nA mismatch makes the home tile call a live snapshot stale, or a dead one fresh."],
  "scripts/check-invariants.mjs#270": ["WHY","trap kept, trimmed","Parsed as JSONC: a regex would match the prose comments that discuss the cron."],
  "scripts/check-invariants.mjs#273": ["CONTRACT","doc trimmed","The cron's period in seconds, or null when it is not a fixed period.\nAccepts a step or an evenly spaced list; anything else fails."],
  "scripts/check-invariants.mjs#277": ["WHY","one-line why"],
  "scripts/check-invariants.mjs#278": ["WHY","trimmed","Evaluated so `15 * 60` and `900` agree; the needle admits only digits, spaces and `*`."],
  "scripts/check-invariants.mjs#279": ["WHY","intent kept; commit narrative moved","The snapshot module's prose must name the watchdog, so its pointer cannot outlive a move."],
  "scripts/check-invariants.mjs#280": ["WHY","prohibition kept, trimmed","health.yml must poll slower than the watchdog: the same schedule doubles load on a\nrate-limited endpoint for no coverage. Asserts the direction, not health.yml's value."],
  "scripts/check-invariants.mjs#281": ["WHY","trimmed","Derived, so a literal that agrees today cannot replace the binding."],
  "scripts/check-invariants.mjs#282": ["WHY","trimmed","One writer: nothing on the home page may start a health run."],
  "scripts/check-invariants.mjs#283": ["CONTRACT","both-directions contract kept; consolidation story moved","CLAUDE.md's binding names are bound to `wrangler.jsonc.example` in both directions: a stale\nname sends a session to a binding that is undefined at runtime.\nReads the tracked example because `wrangler.jsonc` is gitignored; `check:config` binds the two."],
  "scripts/check-invariants.mjs#284": ["WHY","anchor reason kept, trimmed","Names from the indented line after the `getEnv` sentence, so prose cannot widen the set."],
  "scripts/check-invariants.mjs#285": ["WHY","trimmed","An empty set makes every later assertion true."],
  "scripts/check-invariants.mjs#286": ["WHY","trimmed","Derived from the config, so a new kind of binding needs no edit here."],
  "scripts/check-invariants.mjs#287": ["WHY","method and hard rule 10 citations kept; dated re-measurements moved","A stale floor cannot fail (hard rule 10). Re-measure by running both branches, never by\narithmetic: each carried token is two assertions, so the count moves both ways."],
  "scripts/check-invariants.mjs#288": ["HISTORY","dated re-measurement log",null],
  "scripts/check-invariants.mjs#289": ["HISTORY","dated measurement and incident",null],
  "scripts/check-invariants.mjs#290": ["HISTORY","dated re-measurement",null],
  "scripts/check-invariants.mjs#291": ["CONTRACT","both-directions contract and needle kept; prompt and RECOVERY.md history moved","The runbook's rotation table names every secret in `REQUIRED_SECRETS`, both directions: a\nmissing row costs an outage, an extra row sends someone to set a value nothing reads.\nThe owner is `app/lib/secrets.mjs`; wrangler config holds no secrets.\nThe needle is a backticked cell, never a bare mention (Hard rule 10)."],
  "scripts/check-invariants.mjs#292": ["CONTRACT","one-line"],
  "scripts/check-invariants.mjs#293": ["WHY","trimmed","The reverse reads only the rotation table; the page backticks other identifiers in prose."],
  "scripts/check-invariants.mjs#294": ["CONTRACT","scope and instrument split kept; audit story moved","Every JSX `<img` under `app/` states its intrinsic size, or it is a layout shift.\n`test/cover-dimensions.test.mjs` owns the function; this owns that the markup still uses it.\nComments are stripped so prose about `<img>` cannot satisfy the scan."],
  "scripts/check-invariants.mjs#295": ["WHY","trimmed","`app/enhance/` is out: it builds DOM with `createElement`, so it has no JSX `<img`."],
  "scripts/check-invariants.mjs#296": ["WHY","derived-exemption rule and hard rule 5 kept; first-draft story moved","The exemption is read from the stylesheet, not a name list (hard rule 5's mirror\nanti-pattern): a class rule declaring both `width` and `height` reserves the box.\nBoth, never one: width alone leaves height to the intrinsic ratio.\n@type {Map<string, string>} class name -> the declaration block"],
  "scripts/check-invariants.mjs#297": ["WHY","trimmed","First declaration wins; a later one may be another selector context\nand must not satisfy the test."],
  "scripts/check-invariants.mjs#302": ["WHY","trimmed","Non-greedy to the first `>`: a JSX `<img` has no children and no literal `>` in its values."],
  "scripts/check-invariants.mjs#303": ["WHY","trimmed","The `coverDimensions` spread counts, by name only, so `{...rest}` cannot satisfy it."],
  "scripts/check-invariants.mjs#304": ["WHY","already short"],
  "scripts/check-invariants.mjs#305": ["WHY","trimmed; measurement date moved","Floored: a regex that stopped matching reports what a clean sweep reports."],
  "scripts/check-invariants.mjs#306": ["CONTRACT","rule and scope kept; three incidents moved","No raw control byte or invisible character in a tracked text file: a shell-expanded escape\nreaches disk as one byte and still looks right (hard rule 10). An intended one is written as an escape,\nso a raw byte is a defect anywhere and no language parsing is needed.\nCounts below 0x20 except tab, LF and CR; 0x7F; the BOM and the zero-width family.\nTracked files only; binaries skipped by extension."],
  "scripts/check-invariants.mjs#307": ["CONTRACT","one-line"],
  "scripts/check-invariants.mjs#308": ["CONTRACT","one-line"],
  "scripts/check-invariants.mjs#309": ["WHY","already short prohibition"],
  "scripts/check-invariants.mjs#311": ["WHY","trimmed","Both halves floored: an empty glob or an over-wide binary rule reports a clean sweep."],
  "scripts/check-invariants.mjs#312": ["CONTRACT","rules and mechanism kept; login first-run story moved","Hard rule 9 on the markup: a public control must work with scripting off.\nAdmin is exempt; `/login` is not.\nA form needs a native submission path: `onSubmit` without `method` fails; `method` without\n`action` passes. A handler on a keyboard-reachable element is fine; on any other it fails.\nArrow functions contain `>`, so handlers are found first and their owning tag is located by\nscanning back, with brace and quote depth tracked."],
  "scripts/check-invariants.mjs#313": ["CONTRACT","one-line"],
  "scripts/check-invariants.mjs#314": ["CONTRACT","one-line"],
  "scripts/check-invariants.mjs#319": ["WHY","one-line"],
  "scripts/check-invariants.mjs#320": ["WHY","trimmed","Floored: an empty glob or a JSX scan that stopped matching reports a clean sweep."],
  "scripts/check-invariants.mjs#321": ["CONTRACT","three rules kept; the revisit note kept as ruling 88 requires; 2026-09-13 measurements moved","Tokens: (a) every `var(--x)` resolves to a declaration, (b) every declared token is used,\n(c) a component sheet states no raw hex. A misspelled `var()` is valid CSS and paints nothing.\n(b) reads JavaScript too: `app/lib/content/chart.mjs` uses `--chart-*` as strings.\nEach allowlist entry carries its reason.\nNot gated yet: raw numeric font-weight (3d) and off-scale spacing or radius (gate 4), since\nthere is no scale to compare against. Revisit both once Part A's scales land and the sheets\nare migrated (ruling 88)."],
  "scripts/check-invariants.mjs#322": ["CONTRACT","one-line"],
  "scripts/check-invariants.mjs#323": ["CONTRACT","one-line"],
  "scripts/check-invariants.mjs#325": ["CONTRACT","trimmed; tag kept","Named anywhere, gates included: a gate naming an undeclared token is a typo worth failing.\n@type {Set<string>}"],
  "scripts/check-invariants.mjs#326": ["CONTRACT","trimmed; tag kept","Painted: the narrower set the dead-token assertion reads.\n@type {Set<string>}"],
  "scripts/check-invariants.mjs#327": ["CONTRACT","one-line"],
  "scripts/check-invariants.mjs#330": ["WHY","rule and hard rule 10 kept; ruling narrative and plant moved","A mention in `scripts/check-*.mjs` does not make a token consumed. check:contrast requires\nevery colour token be named there, so counting it made (b) unfailable (Hard rule 10's class).\n`referenced` still takes gate mentions for the undefined-name check; `consumed` does not."],
  "scripts/check-invariants.mjs#331": ["WHY","trap kept, trimmed","The carried map below lists token names, not uses, so its region is removed first."],
  "scripts/check-invariants.mjs#333": ["WHY","one-line"],
  "scripts/check-invariants.mjs#334": ["WHY","trimmed","Each result below is a length, which is zero when the scan found nothing."],
  "scripts/check-invariants.mjs#335": ["CONTRACT","self-policing contract kept; redesign build narrative moved","Carried tokens: declared ahead of the owner that will paint them. Not an allowlist:\na row for an undeclared token fails, a row for a painted token fails, and after\n`CARRIED_EXPIRES` the map must be empty. Moving the date is a ruling, not a repair."],
  "scripts/check-invariants.mjs#336": ["WHY","row format kept; rulings 103 and 104, orphan deletions and counts moved","Each row names its owner: `scale:` (a member of a scale whose other members are read) or\n`component:` (a named painter not built yet). A token with no owner is dead and is deleted."],
  "scripts/check-invariants.mjs#337": ["CONTRACT","sentinel read by the scan"],
  "scripts/check-invariants.mjs#338": ["CONTRACT","short typed doc"],
  "scripts/check-invariants.mjs#339": ["CONTRACT","sentinel read by the scan"],
  "scripts/check-invariants.mjs#340": ["HISTORY","dated re-measurement log",null],
  "scripts/check-invariants.mjs#341": ["HISTORY","dated re-measurement and CI incident",null],
  "scripts/check-invariants.mjs#342": ["HISTORY","dated re-measurement log; method kept in #287",null],
  "scripts/check-invariants.mjs#343": ["WHY","reason kept; measurements and incident moved","Named per branch: --remote adds the live-database comparison, so one name would judge\none branch against the other's floor."],
};
