// Ruling 115 decisions, chunk 7: scripts/check-admin-ui.mjs blocks 0 to 210.
const F = "scripts/check-admin-ui.mjs#";
const d = {
  0: ["CONTRACT", "usage and contract kept; redesign story and fixture provenance moved", "Gate over what the admin's forms submit: each page reduces to `METHOD action | intent |\nfield names`, so a control may move but must send what it sent before. Server imports are\nstubbed; no server behaviour, styling or layout is seen. Fails closed: a missing fixture is\nan error, and every comparison is paired with a count.\n\n  npm run check:admin-ui\n  npm run check:admin-ui -- --update    (rewrites the baseline, deliberately loud)"],
  1: ["WHY", "trimmed; hard rule 17 kept", "Asserted against the constants: a copy would be a second owner (hard rule 17)."],
  2: ["WHY", "trimmed", "Asserted against the constant, not a copy."],
  3: ["WHY", "trimmed", "Read from the owner, never retyped. Dynamic: this tsconfig omits the app tree."],
  6: ["CONTRACT", "trimmed", "Loader states: one per shape that changes which controls render."],
  7: ["WHY", "trimmed", "Exactly one featured row, so an ignored flag fails."],
  8: ["WHY", "trimmed", "Pre-computed: the component may not read the clock."],
  9: ["CONTRACT", "trimmed", "One media object."],
  10: ["WHY", "trimmed", "The thumbnail url, so serving originals changes the src."],
  11: ["WHY", "row count moved", "Null placeholders are their own scenario."],
  12: ["CONTRACT", "trimmed", "Parsed by the loader."],
  13: ["CONTRACT", "trimmed", "Byte-identical rows."],
  14: ["WHY", "trimmed", "A fresh upload is `unattached`."],
  15: ["CONTRACT", "stale-fixture incident moved", "The loader's non-object fields, in one helper."],
  16: ["CONTRACT", "trimmed", "`q` is echoed so the input, chips and pager carry it."],
  17: ["WHY", "session heading moved", "Passed as an object, as the component receives it."],
  18: ["CONTRACT", "already short"],
  19: ["WHY", "wording history moved", "Input only: the wording is asserted against the route source."],
  20: ["CONTRACT", "trimmed", "The `?key=` view's loader shape."],
  21: ["HISTORY", "one-run incident; rest restates the code", null],
  22: ["CONTRACT", "trimmed", "Every filter empty."],
  23: ["WHY", "roadmap reference moved", "A missing number is not a zero; the live pair differs only in `complete`."],
  24: ["WHY", "trimmed", "`wip` is absent from both live fixtures."],
  25: ["CONTRACT", "trimmed", "Same rows, cut short: the missing slug is unknown."],
  26: ["CONTRACT", "trimmed", "No token, so no number."],
  28: ["WHY", "B004 crash story moved", "The whole `PostFields` shape: an unsupplied loader field is untested."],
  29: ["WHY", "trimmed", "Hand-written (fixture independence); first six characters differ, as the list prints six."],
  30: ["CONTRACT", "trimmed", "Origin for absolute preview URLs."],
  31: ["CONTRACT", "trimmed", "The edit route's loader data."],
  32: ["WHY", "trimmed", "The component reads it."],
  33: ["WHY", "ruling citation moved", "Rendered, so a restore is proven to add no submission."],
  34: ["WHY", "trimmed", "The section follows `state`, not the length."],
  35: ["WHY", "trimmed", "Hand-authored (fixture independence); `originRequests` differs from `rows`."],
  36: ["WHY", "trimmed", "`detail` is the instrument's sentence, which the page must render, not compose."],
  37: ["WHY", "trimmed", "One failing, so per-check and page-wide verdicts differ."],
  38: ["CONTRACT", "trimmed", "D1 behind, one commit not applied."],
  39: ["WHY", "trimmed", "Dates are `Date` objects, as the loader hands them."],
  41: ["CONTRACT", "section marker shortened", "Posts index."],
  42: ["WHY", "trimmed", "An empty result is not an empty corpus."],
  43: ["WHY", "2026-08-12 gap and session story moved", "`props` seeds selection, since a static render dispatches no events. Two selected, so\nthe count and plural are exercised."],
  44: ["WHY", "trimmed", "The no-script half of the delete guards."],
  45: ["WHY", "session and seam-count narrative moved", "Filtered, two visible, one selected: select-all must say shown."],
  46: ["WHY", "redesign narrative moved", "Media library. Detail states own the per-asset mutations."],
  47: ["WHY", "trimmed", "Usage unknown: nothing is unused, every delete refused."],
  48: ["WHY", "row count moved", "A document has no thumbnail, so the tile shows a label."],
  49: ["WHY", "trimmed", "A static row: no delete offered."],
  50: ["WHY", "404 incident moved", "A static asset is its own url; never prefix /media/."],
  51: ["WHY", "row count moved", "Images does not rasterize SVGs."],
  52: ["WHY", "session heading and counts moved", "A copy button submits nothing, so these need structural assertions."],
  53: ["WHY", "trimmed", "Real shape: the title comes off the key."],
  54: ["WHY", "ruling citation moved", "Seeded: no events are dispatched."],
  55: ["HISTORY", "session heading and narrative", null],
  56: ["WHY", "before-state moved", "Used by repository code, cited by no post."],
  57: ["WHY", "trimmed", "Template-placed: the claim and its source file."],
  58: ["WHY", "trimmed", "Document copy labels differ here only."],
  59: ["WHY", "trimmed", "Removal proposed on a comparison."],
  60: ["WHY", "trimmed", "Alt written: no suggestion offered."],
  61: ["WHY", "plant story moved", "Where precedence and any-flag disagree."],
  62: ["WHY", "trimmed", "A narrowed lens states its boundary."],
  63: ["WHY", "trimmed", "The only empty state with an action."],
  64: ["WHY", "trimmed", "Names the query back."],
  65: ["WHY", "trimmed", "Good news must not read as an error."],
  66: ["HISTORY", "session heading", null],
  67: ["WHY", "prompt() history moved", "The destructive submit lives behind this state."],
  68: ["WHY", "trimmed", "Opens from client state, via a seam."],
  69: ["WHY", "trimmed", "The bar needs a selection."],
  70: ["WHY", "trimmed", "Clear exists only here."],
  71: ["WHY", "trimmed", "Offers widen or clear, not upload."],
  72: ["WHY", "2026-08-17 gap moved", "Both chip shapes: several tags, and exactly one."],
  73: ["WHY", "trimmed", "Set-alt and delete appear here only."],
  74: ["WHY", "restates #49", "No delete offered."],
  75: ["WHY", "trimmed", "Must render a way back."],
  76: ["WHY", "trimmed", "The flash renders."],
  77: ["WHY", "trimmed", "Renders the loader's sentence."],
  78: ["WHY", "heading moved", "View modes: one tree, identical payload."],
  79: ["WHY", "trimmed", "Flat renders no heading."],
  80: ["WHY", "trimmed", "Reset exists only when modified."],
  81: ["WHY", "trimmed", "No empty-trash offer; explanation kept."],
  82: ["WHY", "trimmed", "A way out other than upload."],
  83: ["WHY", "trimmed", "The only twin-removal copy."],
  84: ["WHY", "trimmed", "Restore, never Move to trash."],
  85: ["HISTORY", "session heading", null],
  86: ["WHY", "trimmed", "Two folders, so a per-row grouper fails."],
  87: ["WHY", "trimmed", "The roster photograph."],
  88: ["WHY", "trimmed", "An undated row gets its own bucket."],
  89: ["WHY", "ruling and incident moved", "The only state issuing bulk intents; two for the plural."],
  90: ["WHY", "trimmed", "`role=all` is unfiltered; the default is not."],
  91: ["WHY", "trimmed", "Select-all must say shown."],
  92: ["CONTRACT", "section marker shortened", "New post."],
  93: ["CONTRACT", "section marker shortened", "Edit."],
  94: ["WHY", "trimmed", "A refused unconfirmed first publication."],
  95: ["WHY", "trimmed", "Ticks the picker, so `frInternal` is submitted."],
  96: ["WHY", "trimmed", "The negative for the unchecked box."],
  97: ["WHY", "feature heading and table trimmed", "Preview links: none, two, and published (neither control). Two links prove the tuple is\nshared, so a token leaking into the submission fails."],
  98: ["WHY", "trimmed", "Proves the section follows state, not emptiness."],
  99: ["WHY", "trimmed", "Origin requests. Error is the local state: no read token."],
  100: ["WHY", "trimmed", "Mentions. Destructive intents refuse in the action and render a second step for no-script\nreaders. Rows carry hostile input because the render is the boundary."],
  101: ["WHY", "ruling heading moved", "At `all`, so the escaping assertions see `MENTIONS[0]`."],
  102: ["WHY", "ruling and old-page history moved", "Fails both ways: not filtering, or not explaining."],
  103: ["WHY", "trimmed", "The hidden `intent` stays enabled, so the payload is unchanged; browser submission is not\nmodelled. The state exists for the label."],
  104: ["WHY", "ruling citation moved", "Each box asserted against the other."],
  105: ["HISTORY", "2026-08-25 coverage gap narrative", null],
  106: ["CONTRACT", "separator shortened", "Checks."],
  107: ["CONTRACT", "2026-09-03 change narrative moved", "Section 1: the publish state machine. Buttons submit their transition id as `intent`.\nEvery rule is paired with its negative."],
  109: ["CONTRACT", "already short"],
  110: ["CONTRACT", "trimmed", "A withdrawn draft."],
  111: ["WHY", "trimmed", "A repeated ask becomes a habit."],
  112: ["CONTRACT", "already short"],
  113: ["WHY", "trimmed", "Scheduled is already draft:false."],
  114: ["CONTRACT", "trimmed", "Exactly one primary."],
  116: ["WHY", "trimmed", "Each transition is a known intent with the same draft meaning."],
  117: ["WHY", "trimmed", "The confirmed publish means draft:false."],
  118: ["WHY", "trimmed", "Cmd+S has no submitter, so it names its intent; asserted on the flag it produces."],
  120: ["WHY", "trimmed", "Fail closed: a leaked private post is unrecoverable, a refused save is not."],
  121: ["WHY", "2026-09-03 replay and counts moved", "`fieldsFromForm` reads the intent. Bundled alone: mixed entries shift esbuild's outbase."],
  123: ["CONTRACT", "trimmed", "The request a submitter sends."],
  125: ["CONTRACT", "trimmed", "Every intent, through the real parser."],
  126: ["WHY", "trimmed", "An empty table passes the loop."],
  127: ["WHY", "trimmed", "A parser that also honours `draft` is a half-applied revert."],
  129: ["WHY", "trimmed", "Without it a parser returning a constant passes."],
  130: ["CONTRACT", "trimmed", "Agrees with publiclyVisible()."],
  131: ["WHY", "trimmed", "`publish_at <= now` is live."],
  132: ["CONTRACT", "trimmed", "Section 1b: every transition is legal under the policy, and every outcome is reachable."],
  133: ["CONTRACT", "trimmed", "Markdown a save carries.\n@param {boolean} draft\n@param {string | null} firstPublished"],
  134: ["CONTRACT", "trimmed", "Every table state."],
  136: ["CONTRACT", "trimmed", "Claimed outcomes."],
  138: ["WHY", "discovery story moved; hard rule 10 kept", "One varying condition: a literal `true` on the success path cannot fail (hard rule 10)."],
  141: ["WHY", "trimmed", "The committed draft flag is what was sent."],
  142: ["CONTRACT", "trimmed", "No orphan outcomes."],
  143: ["WHY", "trimmed", "And none unmodelled."],
  144: ["CONTRACT", "banner trimmed", "Section 2: what the pages submit."],
  146: ["CONTRACT", "trimmed", "Markup per state."],
  149: ["CONTRACT", "trimmed", "Raw markup per state."],
  151: ["WHY", "trimmed", "An empty render would match a baseline generated from a broken render."],
  152: ["WHY", "trimmed", "Fail closed."],
  154: ["WHY", "dated measurements moved; hard rule 10 kept", "Empty baselines equal a render with no forms. The floor is measured by running this gate,\nnever summed (hard rule 10)."],
  155: ["WHY", "dated measurements moved", "Floored because `--update` rewrites the baseline and cannot reach this copy."],
  156: ["CONTRACT", "trimmed", "Section 3: editor structure, not interaction."],
  158: ["CONTRACT", "trimmed", "React's escaping, mirrored.\n@param {string} text\n@returns {string}"],
  160: ["WHY", "trimmed", "Present before it speaks."],
  161: ["WHY", "trimmed", "The label matches the table."],
  163: ["HISTORY", "2026-09-03 rewrite story; the rule is in #167", null],
  164: ["WHY", "trimmed", "Each button submits its own id."],
  166: ["WHY", "trimmed", "No `draft` field, or a half revert passes."],
  167: ["WHY", "trimmed", "First publication sends the ask."],
  168: ["WHY", "trimmed", "Counted, so absence cannot pass."],
  169: ["WHY", "trimmed", "Its dialog's `save` would mean draft:false on a draft."],
  170: ["WHY", "trimmed", "Subtracted, not extracted: both render the same button, and an end anchor would match a\nneighbour."],
  171: ["CONTRACT", "already short"],
  172: ["WHY", "trimmed", "Without it an unconditional step, a one-press publication, passes."],
  173: ["WHY", "trimmed", "Counted: one featured row."],
  174: ["WHY", "trimmed", "The tuple set is distinct, so it cannot show which rows offer a control; counts do."],
  175: ["WHY", "plant story moved", "The bare id matches the form and any button aimed at it."],
  176: ["WHY", "trimmed", "A broken `form=` silently submits the bulk selection form instead."],
  177: ["WHY", "trimmed; hard rule 10 kept", "Scope first: an empty page satisfies every vacuously (hard rule 10)."],
  178: ["WHY", "trimmed", "First publication is reserved to the editor, so no list row may send it."],
  179: ["CONTRACT", "trimmed", "Frontmatter controls."],
  180: ["WHY", "trimmed", "A details opens without script."],
  181: ["WHY", "trimmed", "The hidden false renders first: `fieldsFromForm` takes the last value."],
  182: ["WHY", "trimmed", "Reflects the stored value."],
  183: ["WHY", "trimmed", "Without the marker an empty list reads as never offered, and data is lost."],
  184: ["WHY", "trimmed", "A spare row."],
  185: ["WHY", "already short"],
  186: ["WHY", "trimmed", "One field wide."],
  187: ["WHY", "trimmed", "Only published posts are offered."],
  188: ["WHY", "trimmed", "Names its fallback."],
  189: ["WHY", "trimmed", "Only a new post has a slug input."],
  190: ["WHY", "history moved", "An HTML `pattern` anchors implicitly, so only the negative catches an anchored source.\n`includes`, not a RegExp: the pattern is full of metacharacters."],
  192: ["WHY", "trimmed", "Scope first."],
  193: ["WHY", "trimmed", "Text the baseline cannot see."],
  194: ["WHY", "trimmed", "Unfiltered keeps the bare form."],
  195: ["WHY", "incident narrative moved", "View links are fieldless GETs, so hrefs are read. Needles derive from `PARAM_NAMES`."],
  196: ["WHY", "session history moved", "Every parameter non-default. `view` is list because column headers render only there."],
  198: ["WHY", "discovery story moved", "The search form is cut out: it owns `q`, and its Clear link must drop it."],
  199: ["WHY", "trimmed", "Scope first."],
  200: ["CONTRACT", "trimmed", "Droppable parameters.\n@type {Record<string, string>}"],
  201: ["WHY", "trimmed", "Pages differ per filter."],
  202: ["WHY", "trimmed", "An owner drops its default."],
  203: ["WHY", "trimmed", "No control owns `q`, so dropping it is always the bug. Others need one carrier each."],
  204: ["CONTRACT", "session heading moved", "Media structure the baseline cannot see."],
  205: ["CONTRACT", "trimmed", "The document card."],
  206: ["WHY", "trimmed", "Written out, not produced by `docTitle`: fixture independence."],
  207: ["WHY", "trimmed", "No raw filename too."],
  208: ["WHY", "trimmed", "Hidden decoration."],
  209: ["WHY", "mockup story moved", "Nothing stores a page count, so none may be invented."],
  210: ["WHY", "first-draft story moved", "Scoped to the card: there is no stylesheet, so CSS-hidden text elsewhere still counts."],
};
const out = {};
for (const [k, v] of Object.entries(d)) out[F + k] = v;
export default out;
