// Ruling 115 decisions, chunk 8: scripts/check-admin-ui.mjs blocks 211 to 384.
export default {
  "scripts/check-admin-ui.mjs#211": ["CONTRACT","section heading shortened","2. Caption bar"],
  "scripts/check-admin-ui.mjs#212": ["WHY","negative half kept; approval narrative cut","Without this, a bar drawn over every tile passes the assertion above."],
  "scripts/check-admin-ui.mjs#213": ["WHY","reason kept, shortened","One copy control per card, in both states. The payload baseline cannot see this:\n`type=\"button\"` is not a submission."],
  "scripts/check-admin-ui.mjs#214": ["CONTRACT","section heading shortened","3. List header and its URLs"],
  "scripts/check-admin-ui.mjs#215": ["WHY","reason kept, shortened","No `dims` sort key: half the library has no dimensions."],
  "scripts/check-admin-ui.mjs#216": ["WHY","discrimination reason kept","Counting both catches every column marked active as well as none."],
  "scripts/check-admin-ui.mjs#217": ["CONTRACT","intent and prohibition kept; quoted spec cut","Header and popover sort links land on identical URLs, both read off the markup; never\nbuild an expectation with `sortHref`, which would assert it equals itself. The active\ncolumn is exempt: its header reverses direction and the popover does not."],
  "scripts/check-admin-ui.mjs#219": ["WHY","trap kept; incident reference cut","Via `readView`: `hrefWith` omits defaults, so the spelled sort is not the meant sort."],
  "scripts/check-admin-ui.mjs#222": ["WHY","shortened","Nothing nests in the header, so the first `</div>` is its own."],
  "scripts/check-admin-ui.mjs#223": ["WHY","trap kept, shortened","Sort group only: Direction links resolve to the current key."],
  "scripts/check-admin-ui.mjs#224": ["WHY","prohibition kept; first-draft story moved","Never filter on `sort=` in the href: the default column links to a bare `/admin/media`."],
  "scripts/check-admin-ui.mjs#225": ["WHY","scope-first reason kept","Scope first: an empty list passes every comparison below."],
  "scripts/check-admin-ui.mjs#226": ["CONTRACT","already short"],
  "scripts/check-admin-ui.mjs#228": ["WHY","already short"],
  "scripts/check-admin-ui.mjs#229": ["WHY","reason kept, shortened","Asserted, or the exemption above lets every column stop toggling."],
  "scripts/check-admin-ui.mjs#230": ["CONTRACT","intent kept; session label cut","Three-state usage model: text the payload baseline cannot see."],
  "scripts/check-admin-ui.mjs#231": ["WHY","derivation reason kept","Derived from the module so the state list cannot drift."],
  "scripts/check-admin-ui.mjs#232": ["CONTRACT","section heading shortened","1. Third state"],
  "scripts/check-admin-ui.mjs#233": ["WHY","shortened","The negative, on a row with no reference, proves the assertion above discriminates."],
  "scripts/check-admin-ui.mjs#234": ["CONTRACT","section heading shortened","2. Inspector evidence"],
  "scripts/check-admin-ui.mjs#235": ["WHY","reason kept; date cut","The state, not the wording, so a true rephrasing passes."],
  "scripts/check-admin-ui.mjs#236": ["WHY","shortened","A claim names its source file."],
  "scripts/check-admin-ui.mjs#237": ["WHY","prohibition kept","Never call an unattached file \"unused\": the scan cannot see constructed paths or\nexternal links."],
  "scripts/check-admin-ui.mjs#238": ["WHY","shortened","Renders on every listing."],
  "scripts/check-admin-ui.mjs#239": ["WHY","mechanism kept; commit story moved","Read at source, not through the fixture: the note is loader data, so a render only\nechoes the gate's own copy."],
  "scripts/check-admin-ui.mjs#240": ["WHY","prohibition and scoping kept; screenshot incident moved","No \"unused\" in the rendered tile meta. Scoped to that element so the prose explaining\nthe rule may still use the word."],
  "scripts/check-admin-ui.mjs#241": ["WHY","shortened","Scope first: zero meta lines would pass the absence by examining nothing."],
  "scripts/check-admin-ui.mjs#242": ["WHY","trap kept; plant and first-draft story moved","Element-bounded, like the negative: a lazy `[\\s\\S]*?` crosses `</p>` into later markup."],
  "scripts/check-admin-ui.mjs#244": ["CONTRACT","section heading shortened","3. Row flags and tile dot"],
  "scripts/check-admin-ui.mjs#245": ["WHY","trap kept; first-draft story moved","Scoped: the no-alt lens hint says \"no alt\" on every page."],
  "scripts/check-admin-ui.mjs#246": ["WHY","discrimination reason kept; plant story moved","A tile with nothing worth flagging has no dot. This is the state where `tileFlagFor`\nand `flags.length > 0` disagree."],
  "scripts/check-admin-ui.mjs#247": ["WHY","shortened","Quiet tile, not a dropped flag."],
  "scripts/check-admin-ui.mjs#248": ["CONTRACT","section heading shortened","4. Lens notes, empty states"],
  "scripts/check-admin-ui.mjs#249": ["WHY","reason kept; date and tier cut","Presence and escape only; phrasing is the writer's."],
  "scripts/check-admin-ui.mjs#250": ["WHY","shortened","Each is the right empty state."],
  "scripts/check-admin-ui.mjs#251": ["HISTORY","narrowing note; code shows the facts",null],
  "scripts/check-admin-ui.mjs#252": ["WHY","reason kept; date cut","Echoing the query is the property."],
  "scripts/check-admin-ui.mjs#253": ["HISTORY","narrowing note; exclusion below explains itself",null],
  "scripts/check-admin-ui.mjs#254": ["WHY","shortened","Mutually exclusive."],
  "scripts/check-admin-ui.mjs#255": ["CONTRACT","section heading shortened","5. Suggestions"],
  "scripts/check-admin-ui.mjs#256": ["WHY","shortened","Never suggest over written alt."],
  "scripts/check-admin-ui.mjs#257": ["WHY","reason kept; unasserted counts cut","Documents take no alt."],
  "scripts/check-admin-ui.mjs#258": ["CONTRACT","section heading shortened","6. Copy labels"],
  "scripts/check-admin-ui.mjs#259": ["CONTRACT","section heading shortened","7. Duplicates"],
  "scripts/check-admin-ui.mjs#260": ["CONTRACT","section heading shortened","8. Palette and shortcuts"],
  "scripts/check-admin-ui.mjs#261": ["HISTORY","session story; the next blocks carry the rule",null],
  "scripts/check-admin-ui.mjs#262": ["WHY","pointer kept; date cut","Row count; the binding is asserted below."],
  "scripts/check-admin-ui.mjs#263": ["CONTRACT","shortened","Panel rows equal MEDIA_SHORTCUTS."],
  "scripts/check-admin-ui.mjs#264": ["WHY","rule and mechanism kept; plant story moved","Never advertise an unwired binding. Equal counts pass a fake row, so each row names its\nexpression and it must appear in an island."],
  "scripts/check-admin-ui.mjs#265": ["WHY","boundary kept; plant story moved","Loader wiring, by source grep: the harness cannot run a loader and states supply `usage`\nas input, so a disconnected model renders identically."],
  "scripts/check-admin-ui.mjs#266": ["WHY","shortened","Listing and lens count share one key list."],
  "scripts/check-admin-ui.mjs#267": ["CONTRACT","section heading shortened","8b. Cockpit"],
  "scripts/check-admin-ui.mjs#268": ["WHY","rule 17 reason kept, shortened","A view renders what the instrument reports (rule 17): print each check's own `detail`,\nsince a sentence rebuilt from its numbers drifts on the first rewording."],
  "scripts/check-admin-ui.mjs#269": ["WHY","owner pointer kept","Names come from CHECK_COPY, never retyped here."],
  "scripts/check-admin-ui.mjs#270": ["WHY","shortened","The positive half passes on a page printing both names and ids."],
  "scripts/check-admin-ui.mjs#271": ["WHY","shortened","The counts stay the verdict's own."],
  "scripts/check-admin-ui.mjs#273": ["WHY","shortened","State by word, not hue."],
  "scripts/check-admin-ui.mjs#274": ["WHY","shortened","The word survives forced-colors."],
  "scripts/check-admin-ui.mjs#275": ["WHY","shortened","No empty menus."],
  "scripts/check-admin-ui.mjs#276": ["HISTORY","duplicate of the next block",null],
  "scripts/check-admin-ui.mjs#277": ["WHY","reason kept; ruling narrative cut","Figures are the ones handed in, not hard-coded."],
  "scripts/check-admin-ui.mjs#278": ["WHY","shortened","Amber: the ship sync repairs it."],
  "scripts/check-admin-ui.mjs#279": ["WHY","shortened","No permanently empty panel."],
  "scripts/check-admin-ui.mjs#280": ["CONTRACT","shortened","Names, never values."],
  "scripts/check-admin-ui.mjs#281": ["CONTRACT","section heading shortened","9. No-script floor"],
  "scripts/check-admin-ui.mjs#282": ["WHY","rule kept, shortened","Enhancements are additive; the scriptless render is the proof."],
  "scripts/check-admin-ui.mjs#283": ["CONTRACT","intent kept; session label cut","Drawer and modals, rendered with no script or stylesheet."],
  "scripts/check-admin-ui.mjs#284": ["CONTRACT","section heading shortened","1. Drawer"],
  "scripts/check-admin-ui.mjs#285": ["WHY","shortened","An anchor dismisses without script."],
  "scripts/check-admin-ui.mjs#286": ["CONTRACT","section heading shortened","2. Confirmations"],
  "scripts/check-admin-ui.mjs#287": ["WHY","trap kept","Delete sits behind a confirmation state: an `onSubmit` `prompt()` never runs without\nscript, so the form submitted straight through."],
  "scripts/check-admin-ui.mjs#288": ["WHY","trap kept","Enabled in the server render: nothing enables it without script. The action is the check."],
  "scripts/check-admin-ui.mjs#289": ["WHY","shortened","Built from CONFIRM_FIELD, not its literal, so a rename moves the needle with the code."],
  "scripts/check-admin-ui.mjs#290": ["WHY","shortened","Cancel is a link."],
  "scripts/check-admin-ui.mjs#291": ["CONTRACT","doc and hard rule 10 kept; plant story moved","The modal's own form; tiles carry the same `key` fields (hard rule 10).\n@param {string} h\n@returns {string}"],
  "scripts/check-admin-ui.mjs#292": ["WHY","shortened","Trash is reversible, so no typed count."],
  "scripts/check-admin-ui.mjs#293": ["CONTRACT","section heading shortened","3. Selection bar"],
  "scripts/check-admin-ui.mjs#294": ["CONTRACT","section heading shortened","4. Tile chrome"],
  "scripts/check-admin-ui.mjs#295": ["WHY","shortened","Hidden by CSS only; keyboard and scan need the markup."],
  "scripts/check-admin-ui.mjs#296": ["WHY","trap kept; measurements moved","Keep \"its checkbox\" in the label: the `check:invariants` raw-SQL scanner misreads regex\nliterals here and parses `AND checkbox IN` as a column."],
  "scripts/check-admin-ui.mjs#297": ["CONTRACT","shortened; session label cut","Grouping headings and select-all wording."],
  "scripts/check-admin-ui.mjs#298": ["WHY","shortened; verdict story moved","Titles, not raw prefixes."],
  "scripts/check-admin-ui.mjs#299": ["WHY","shortened","Not a library total."],
  "scripts/check-admin-ui.mjs#300": ["WHY","shortened","Flat has no heading."],
  "scripts/check-admin-ui.mjs#301": ["WHY","shortened","Unfiltered keeps the bare form."],
  "scripts/check-admin-ui.mjs#302": ["WHY","reason kept","Draft preview links. A printed token is a capability, invisible to the payload baseline.\nEvery absence below pairs with a positive proving its needle can match."],
  "scripts/check-admin-ui.mjs#303": ["WHY","reason kept; date cut","Revoke copy carries a measured bound; both directions."],
  "scripts/check-admin-ui.mjs#304": ["WHY","shortened","Publication is immediate; keep that clause."],
  "scripts/check-admin-ui.mjs#305": ["WHY","shortened","The absolute URL is never printed. The token appears once, as the revoke form's hidden\nfield, so the URL's absence is asserted."],
  "scripts/check-admin-ui.mjs#306": ["WHY","shortened","The needle can match."],
  "scripts/check-admin-ui.mjs#307": ["WHY","already short"],
  "scripts/check-admin-ui.mjs#308": ["CONTRACT","scope reason kept; audit and ruling history moved","Copy law, asserted on rendered markup: source identifiers such as `TrafficRow` are never\nseen by a reader. Labels claim, prose explains, so the explaining `<details>` is exempt.\nEach needle is word-anchored and checked against a decoy."],
  "scripts/check-admin-ui.mjs#309": ["CONTRACT","trap kept; measurement cut","Whether a menu item has this label. React reorders attributes.\n@param {string} html @param {string} label"],
  "scripts/check-admin-ui.mjs#310": ["CONTRACT","shortened","Markup minus the exempt element."],
  "scripts/check-admin-ui.mjs#312": ["WHY","shortened","The exemption is neither empty nor total."],
  "scripts/check-admin-ui.mjs#313": ["WHY","shortened","Decoy first."],
  "scripts/check-admin-ui.mjs#314": ["WHY","controlled comparison kept; roadmap label cut","Readership: `live` and `truncated` differ only in `complete`."],
  "scripts/check-admin-ui.mjs#315": ["WHY","shortened; ruling narrative moved","Cached reads never reach the Worker."],
  "scripts/check-admin-ui.mjs#316": ["WHY","shortened","Complete and absent is zero."],
  "scripts/check-admin-ui.mjs#317": ["WHY","trap kept","Absent from a truncated result is not zero; `byPath[path] ?? 0` fails here."],
  "scripts/check-admin-ui.mjs#318": ["WHY","shortened","Identical cells mean `complete` is ignored."],
  "scripts/check-admin-ui.mjs#320": ["WHY","shortened","A reason, never a number."],
  "scripts/check-admin-ui.mjs#321": ["WHY","shortened","One owner (rule 17)."],
  "scripts/check-admin-ui.mjs#322": ["WHY","shortened","Both pages obey the copy law."],
  "scripts/check-admin-ui.mjs#323": ["WHY","shortened","The required half."],
  "scripts/check-admin-ui.mjs#324": ["WHY","shortened","Three distinct pages."],
  "scripts/check-admin-ui.mjs#325": ["WHY","already short"],
  "scripts/check-admin-ui.mjs#326": ["WHY","shortened","Errors are visible prose."],
  "scripts/check-admin-ui.mjs#327": ["WHY","both-halves reason kept; probe history moved","Answer present, placeholder gone."],
  "scripts/check-admin-ui.mjs#328": ["WHY","shortened","Mentions: stranger input, read back both ways."],
  "scripts/check-admin-ui.mjs#329": ["WHY","shortened","Escaped present is not live absent."],
  "scripts/check-admin-ui.mjs#330": ["WHY","shortened","A stranger's URL stays text."],
  "scripts/check-admin-ui.mjs#331": ["WHY","shortened","The post's own slug may link."],
  "scripts/check-admin-ui.mjs#332": ["WHY","ruling label cut","Quoted, not page prose."],
  "scripts/check-admin-ui.mjs#333": ["WHY","shortened","Chips with counts."],
  "scripts/check-admin-ui.mjs#335": ["WHY","shortened","All includes `unverified`."],
  "scripts/check-admin-ui.mjs#336": ["WHY","shortened","One current chip."],
  "scripts/check-admin-ui.mjs#337": ["WHY","ruling label cut","No link: nothing to decide."],
  "scripts/check-admin-ui.mjs#338": ["WHY","shortened","Absent, not zero."],
  "scripts/check-admin-ui.mjs#339": ["WHY","shortened","Headings asserted gone."],
  "scripts/check-admin-ui.mjs#340": ["HISTORY","restates the assertions below",null],
  "scripts/check-admin-ui.mjs#341": ["WHY","shortened","Box matches outcome."],
  "scripts/check-admin-ui.mjs#342": ["WHY","shortened","Weight is the class."],
  "scripts/check-admin-ui.mjs#343": ["WHY","shortened","No danger fill on rows."],
  "scripts/check-admin-ui.mjs#344": ["WHY","trap kept; amendment history moved","Stated once, on the pending filter. A literal string, never a /g regex: `lastIndex`\ncarries between the `.test()` calls below."],
  "scripts/check-admin-ui.mjs#346": ["WHY","shortened","Above the queue."],
  "scripts/check-admin-ui.mjs#347": ["WHY","shortened","Both negatives: not on every filter, not over an empty queue."],
  "scripts/check-admin-ui.mjs#348": ["WHY","shortened","Windows come from the constants."],
  "scripts/check-admin-ui.mjs#349": ["WHY","shortened","The label carries the count."],
  "scripts/check-admin-ui.mjs#350": ["WHY","shortened","Asserted together: \"verified is absent\" alone passes a row with no stamps."],
  "scripts/check-admin-ui.mjs#351": ["WHY","shortened","Only a render shows a scriptless second step."],
  "scripts/check-admin-ui.mjs#352": ["WHY","shortened","No field before it is asked for."],
  "scripts/check-admin-ui.mjs#353": ["HISTORY","floor measurement log; the floor's why is kept at MINIMUM_CHECKS",null],
  "scripts/check-admin-ui.mjs#354": ["WHY","rule and mechanism kept; ruling date cut","No-script fallback: the display axes stay real links. `shouldRevalidate` handles them on\nthe client, so a rotted anchor goes unseen. `hrefWith` omits defaults, so a default value\nis an anchor to the bare URL."],
  "scripts/check-admin-ui.mjs#355": ["WHY","hard rule 10 kept; plant story moved","Scoped to each axis nav: every link preserves the view state, so a page-wide search\npasses a toggle that became a button (hard rule 10)."],
  "scripts/check-admin-ui.mjs#357": ["CONTRACT","shortened","The labelled `<nav>` markup, or \"\".\n@param {string} html\n@param {string} ariaLabel"],
  "scripts/check-admin-ui.mjs#358": ["WHY","shortened","SCOPED-BY: `navNamed`."],
  "scripts/check-admin-ui.mjs#359": ["WHY","shortened","Scope non-empty: a renamed control would otherwise pass over zero states."],
  "scripts/check-admin-ui.mjs#361": ["WHY","shortened","Control first."],
  "scripts/check-admin-ui.mjs#363": ["WHY","shortened","The server resolves display axes from the URL; if the client overlay is not a no-op\nthere, scriptless readers get the default layout."],
  "scripts/check-admin-ui.mjs#364": ["CONTRACT","boundary kept; measurement cut","Pending transitions. One static pass keeps `useNavigation` idle, so this proves only that\n`data-pending` is conditional; a hardcoded mark would dim every page."],
  "scripts/check-admin-ui.mjs#365": ["WHY","shortened","From the router, not local state."],
  "scripts/check-admin-ui.mjs#366": ["WHY","shortened","SCOPED-BY: the whole file, so any hand-rolled mark fails."],
  "scripts/check-admin-ui.mjs#367": ["WHY","shortened","SCOPED-BY: the whole file."],
  "scripts/check-admin-ui.mjs#368": ["WHY","shortened","Free text needs a GET form."],
  "scripts/check-admin-ui.mjs#369": ["CONTRACT","shortened","Ruling 54"],
  "scripts/check-admin-ui.mjs#370": ["WHY","mechanism kept; history cut","(1) Confirmation dialog. A disabled submitter sends no name or value, so the intent must\nbe a field for disable-until-match to work."],
  "scripts/check-admin-ui.mjs#371": ["WHY","trap kept","Inline and enabled on the server: a `<dialog>` without `open` or `data-inline` is hidden,\nand nothing enables the button without script."],
  "scripts/check-admin-ui.mjs#372": ["WHY","shortened","No effects run here; read the source."],
  "scripts/check-admin-ui.mjs#373": ["WHY","shortened","(2) Drawer opener at 375. No viewport here, so the markup and breakpoint are checked;\nhiding the rail strands a narrow reader."],
  "scripts/check-admin-ui.mjs#374": ["WHY","shortened; incident examples moved","(3) Status sentence agrees with the notice."],
  "scripts/check-admin-ui.mjs#375": ["CONTRACT","already short"],
  "scripts/check-admin-ui.mjs#376": ["CONTRACT","shortened","@param {string} html"],
  "scripts/check-admin-ui.mjs#378": ["WHY","shortened","No clean claim under a notice."],
  "scripts/check-admin-ui.mjs#379": ["WHY","shortened","(4) No prose in any admin table: a `<caption>` is announced before every row. Runs over\nevery rendered state, so a new table is covered at once."],
  "scripts/check-admin-ui.mjs#380": ["WHY","scope and trap kept; count cut","(5) No 0.375rem in the sheets this pass owns. Comments are stripped first because the\nrule's own explanation quotes the literal."],
  "scripts/check-admin-ui.mjs#382": ["WHY","shortened","Scope non-empty: an unread file reports what a clean sweep reports."],
  "scripts/check-admin-ui.mjs#383": ["NUMBER","floor reason kept; measurement log moved","Executed-count floor: the total is the only witness to a block that stopped running.\nMeasured by running this gate, never summed; the slack absorbs a retired state."],
  "scripts/check-admin-ui.mjs#384": ["WHY","hard rule 17 kept; plant story moved","`assertFloor` prints the live count (hard rule 17)."],
};
