// Ruling 115 decisions, chunk 9: scripts/check-features.mjs blocks 0 to 210.
const F = "scripts/check-features.mjs#";
const H = "section heading shortened";
export default {
  [F + 0]: ["CONTRACT", "usage, boundaries and anchor rule kept; argument and emphasis cut", "Gate over the colophon's hand-written half: `npm run check:features`.\n\nIt verifies that what each claim is about still exists, never that the prose is true.\nThe route parser does not compose nested prefixes: anchor a nested route to its declared\nsegment, never to a hardcoded path list. Every feature needs a route, gate or assertion\nanchor; a decision anchor lives in Capsid and proves nothing offline. Fails closed on zero\nfeatures, zero anchors, or an unparsed routes.ts."],
  [F + 1]: ["WHY", "reason kept, shortened", "Same function the route calls, so the gate cannot agree only with itself (hard rule 10)."],
  [F + 2]: ["WHY", "shortened", "The key grammar's readers, so the demos are checked against the real module."],
  [F + 3]: ["WHY", "shortened", "The theme resolver, for the same reason."],
  [F + 4]: ["WHY", "shortened", "The demos' real code paths, imported rather than reimplemented."],
  [F + 5]: ["WHY", "already one line"],
  [F + 7]: ["CONTRACT", "contract kept; incident narrative moved", "Comments removed, line structure kept, so a match is a property of code. Every reader here\nuses it.\n\n@param {string} source"],
  [F + 9]: ["CONTRACT", "rule kept; move history cut", "Letter-digit tokens (D1, FTS5) are names, removed before a hard-rule-17 digit scan.\n\n@param {string} text"],
  [F + 11]: ["CONTRACT", "contract and failure direction kept", "Every path `routes.ts` declares, by regex. A route it cannot parse fails, the safe direction."],
  [F + 12]: ["WHY", "trap kept; list of other gates cut", "Comments first: this file's prose names paths."],
  [F + 14]: ["WHY", "already one line"],
  [F + 15]: ["CONTRACT", "trimmed", "Path to module file; an unresolvable module is absent and the caller fails it.\n\n@returns {Map<string, string>}"],
  [F + 17]: ["CONTRACT", "already one line"],
  [F + 19]: ["WHY", "shortened", "Taken from the command: gate names do not map to files mechanically."],
  [F + 20]: ["CONTRACT", "already one line"],
  [F + 21]: ["CONTRACT", H, "fail closed first"],
  [F + 22]: ["NUMBER", "floor asserted in code; measurement history moved", "Catches a parser that stops seeing nested `route()` calls."],
  [F + 28]: ["CONTRACT", H, "the anchors"],
  [F + 29]: ["CONTRACT", "already one line"],
  [F + 30]: ["WHY", "shortened", "A decision anchor proves nothing offline, so it may never stand alone."],
  [F + 32]: ["WHY", "rule and signals kept; audit measurement and draft story moved", "An anchor rendered as a link must answer an anonymous GET, else `anonymousGet: false`.\nDerived here: a default export is a page; else no loader, `status: 405` or\n`authenticateOperator` means not a page."],
  [F + 33]: ["WHY", "shortened", "A declared route with no module on disk fails rather than skips."],
  [F + 34]: ["WHY", "trap kept; backlog item and incident moved", "Both sides LF-normalized, or a multi-line anchor passes only on a CRLF disk."],
  [F + 35]: ["CONTRACT", H, "hard rule 17, on the prose"],
  [F + 36]: ["WHY", "rule, boundary and exemptions kept; audit story moved", "Hard rule 17 on the feature prose: no digit a gate does not own, no removed-pipeline\nwords. Cannot read tense. Only protocol constants are allowed; a date allowance would cover\nno field here (hard rule 10). Anchor text is exempt."],
  [F + 37]: ["CONTRACT", "trimmed", "Bare digits prose may carry. Closed: a protocol constant cannot go stale."],
  [F + 38]: ["CONTRACT", "already one line"],
  [F + 39]: ["HISTORY", "note about a move", null],
  [F + 40]: ["WHY", "date cut", "Removed-pipeline phrases; a sentence using one describes nothing real."],
  [F + 41]: ["WHY", "shortened", "Scope asserted below, or an empty list sweeps nothing."],
  [F + 44]: ["NUMBER", "floor asserted in code; measurement moved", "Floored under the measured field count."],
  [F + 45]: ["WHY", "shortened", "Proves the predicate can fire, since the real data may be clean."],
  [F + 46]: ["CONTRACT", H, "page search records"],
  [F + 47]: ["HISTORY", "placement rationale about another gate; nothing binding", null],
  [F + 50]: ["WHY", "ruling citation cut", "Fail closed: zero records would pass everything below."],
  [F + 52]: ["CONTRACT", "trimmed; counts cut", "Every page record lives at a declared route; papers share one parameterised route."],
  [F + 58]: ["WHY", "shortened", "Section anchors both ways: an unrendered anchor is a hit that scrolls nowhere."],
  [F + 61]: ["WHY", "shortened", "The only `<h2 id=` is in `SectionHead`, so any literal id is a second list."],
  [F + 62]: ["CONTRACT", H, "not-adopted labels"],
  [F + 63]: ["WHY", "intent kept; 2026-08-05 defect story moved", "The index carries the page's label, never the raw enum, and no reader holds a copy."],
  [F + 64]: ["WHY", "already one line"],
  [F + 66]: ["CONTRACT", "already one line"],
  [F + 67]: ["WHY", "shortened", "Direction 2: no label for an undeclared status."],
  [F + 68]: ["WHY", "shortened", "The artifact is what search matches, so it is read, not recomputed."],
  [F + 70]: ["WHY", "shortened", "Parenthesised, so a reason sentence cannot fire this."],
  [F + 71]: ["WHY", "trap kept; list of gates cut", "Comments stripped: both files name these values in prose."],
  [F + 72]: ["WHY", "shortened", "Each label declared exactly once keeps the descriptor the single source."],
  [F + 73]: ["WHY", "rule kept; 2026-09-11 incident moved", "While CI runs on main, no not-adopted entry may name continuous integration."],
  [F + 75]: ["CONTRACT", H, "enhancement inventory"],
  [F + 76]: ["WHY", "rule and boundary kept", "Hard rule 9: every enhancement names a fallback, both directions against `app/enhance/`.\nWhether it works is a wire claim (hard rule 7)."],
  [F + 77]: ["NUMBER", "count asserted in code", "A tripwire: a new module means walking this list (hard rule 9)."],
  [F + 78]: ["NUMBER", "floor asserted in code; measurement moved", "Set under measured, to catch a module that stopped being read."],
  [F + 80]: ["CONTRACT", "already one line"],
  [F + 82]: ["CONTRACT", "already one line"],
  [F + 83]: ["CONTRACT", "already one line"],
  [F + 84]: ["CONTRACT", "exclusions kept; measurement moved", "Sources under `app/` except `app/enhance/` and stylesheets: neither renders a fallback."],
  [F + 87]: ["WHY", "shortened", "Scope asserted so an empty walk fails by name."],
  [F + 88]: ["NUMBER", "floor asserted in code; measurement history moved", "Catches a walk that stops descending; re-measure by running the gate."],
  [F + 89]: ["WHY", "trap kept; recurrence story moved", "Comments stripped, so a comment cannot satisfy a fallback."],
  [F + 90]: ["WHY", "reason kept; defect story and measurement moved", "Plus what the shared renderer emits (remark-gfm footnotes), from a fixture, since the\nclaim is about the renderer and not the corpus."],
  [F + 91]: ["WHY", "shortened", "Scope first: a failed render would narrow the sweep."],
  [F + 92]: ["CONTRACT", "already one line"],
  [F + 94]: ["WHY", "shortened", "No checkable token would mean examining nothing."],
  [F + 95]: ["WHY", "already one line"],
  [F + 96]: ["WHY", "shortened", "Printed so its floor can be re-measured."],
  [F + 97]: ["CONTRACT", H, "coverage report"],
  [F + 98]: ["WHY", "shortened", "Reported, not failed: failing would invite filler prose."],
  [F + 99]: ["WHY", "intent kept; spec discussion cut", "The projects roster; parity catches a roster edited without a rebuild."],
  [F + 100]: ["WHY", "shortened", "Metric inputs, from the artifacts that own them; no expected value (hard rule 10)."],
  [F + 101]: ["WHY", "unasserted measurement moved", "Fail closed: an empty roster passes every loop below."],
  [F + 102]: ["WHY", "date cut", "A scope floor over a growing set; see check-tests.mjs."],
  [F + 103]: ["WHY", "already short"],
  [F + 104]: ["WHY", "shortened", "Closed: the route shapes structured data for these only."],
  [F + 105]: ["WHY", "shortened", "The kinds this gate verifies; the route refuses others."],
  [F + 106]: ["WHY", "move history cut", "The built corpus; a roster edited without a rebuild fails here."],
  [F + 107]: ["WHY", "already one line"],
  [F + 110]: ["WHY", "shortened", "Nullable by design; a value must pass the imported rule-6 predicate."],
  [F + 111]: ["WHY", "shortened", "Stored or derived, never both (hard rule 17: one owner)."],
  [F + 112]: ["WHY", "shortened", "Runs the route's derivation: producible, not a placeholder."],
  [F + 113]: ["WHY", "shortened", "Optional; two or three sentences when present."],
  [F + 114]: ["WHY", "shortened", "Optional; every entry verified against its owner."],
  [F + 115]: ["WHY", "shortened", "Must equal the post's title; a stale one would still link."],
  [F + 116]: ["WHY", "shortened", "Closed both ways: an unused term stops meaning anything."],
  [F + 118]: ["WHY", "shortened", "The route must read the roster and derive anchors from the shared helper."],
  [F + 119]: ["WHY", "rule and exemptions kept", "Hard rule 17 on roster prose; evidence and metric labels are exempt."],
  [F + 123]: ["NUMBER", "floor asserted in code; measurement moved", "Floored under measured; notable sentences move the count."],
  [F + 124]: ["WHY", "shortened", "Asserted on code: a field nothing renders passes every shape check."],
  [F + 125]: ["WHY", "shortened", "Unbranched, a derived metric renders an empty `<time>`."],
  [F + 126]: ["WHY", "shortened", "Parity both ways: catches a roster edited without a rebuild."],
  [F + 132]: ["NUMBER", "floor asserted in code; measurement history moved", "Executed-count floor, measured by running the gate, never by summing."],
  [F + 133]: ["WHY", "section intent and boundary kept", "The playground: each demo runs the real module against expectations it did not produce\n(hard rule 10). A rendered page is verify-live's claim (hard rule 7)."],
  [F + 134]: ["CONTRACT", "already one line"],
  [F + 137]: ["WHY", "reason kept; measurement date cut", "`line` and `area` both emit `<path>`, so the mark group label is asserted too."],
  [F + 139]: ["WHY", "shortened", "Fail closed: an empty list passes every loop."],
  [F + 140]: ["WHY", "shortened", "Scope floor, as for the roster."],
  [F + 141]: ["CONTRACT", H, "manifest and page"],
  [F + 142]: ["WHY", "shortened", "Keyed by slug: a position index shifts headers while list checks stay green."],
  [F + 144]: ["WHY", "already one line"],
  [F + 148]: ["WHY", "hoisting history moved", "Demos cite published articles; a draft link is a missing page."],
  [F + 149]: ["CONTRACT", H, "contrast lab"],
  [F + 150]: ["WHY", "shortened", "Lc is signed, so polarity is asserted both ways."],
  [F + 151]: ["CONTRACT", H, "fusion arithmetic"],
  [F + 152]: ["WHY", "already one line"],
  [F + 155]: ["WHY", "shortened", "The exact strings toFixed(5) renders."],
  [F + 156]: ["WHY", "trap kept; first-version story cut", "The page reads the decomposition, never computes it; asserted on code, not JSX text."],
  [F + 157]: ["CONTRACT", H, "media key grammar"],
  [F + 158]: ["WHY", "shortened", "Hand-written expectations (hard rule 10's fixture independence)."],
  [F + 159]: ["WHY", "shortened", "\"refused\" is an answer, so the throw branch runs."],
  [F + 160]: ["WHY", "shortened", "Presets must cover every branch."],
  [F + 166]: ["CONTRACT", H, "key demo wiring"],
  [F + 167]: ["CONTRACT", H, "theme resolver"],
  [F + 168]: ["WHY", "shortened", "Real resolver, real request, hand-written expectations."],
  [F + 169]: ["WHY", "shortened", "No header differs from an empty one: the resolver returns early."],
  [F + 170]: ["WHY", "behaviour kept; plant story moved", "A throw is this preset's named failure, and the loop continues."],
  [F + 171]: ["WHY", "shortened", "Branch coverage for the resolver."],
  [F + 177]: ["CONTRACT", H, "theme demo wiring"],
  [F + 178]: ["WHY", "trap kept; plant story moved", "Word-anchored: a suffixed name contains the shorter one (hard rule 10)."],
  [F + 179]: ["WHY", "shortened", "The lede's claim about the Worker, checked there (hard rule 7)."],
  [F + 180]: ["CONTRACT", H, "markdown pipeline"],
  [F + 181]: ["WHY", "shortened", "Snippets render through `renderBody`; the image resolver refuses media."],
  [F + 183]: ["WHY", "shortened", "On the source: the resolver's throw names the wrong cause."],
  [F + 184]: ["WHY", "shortened", "A bare throw is not enough; the directive must be named."],
  [F + 186]: ["WHY", "shortened", "Escaped text is fine; an attribute is not."],
  [F + 187]: ["WHY", "shortened", "Branches no published article can show."],
  [F + 191]: ["CONTRACT", H, "markdown demo wiring"],
  [F + 192]: ["WHY", "shortened", "Both links of the chain are asserted."],
  [F + 193]: ["WHY", "shortened", "The loader picks from manifest slugs, never a body from the URL."],
  [F + 194]: ["WHY", "shortened", "A shipped neighbour does not complete the deferred entry."],
  [F + 196]: ["CONTRACT", H, "chart renderer"],
  [F + 197]: ["WHY", "shortened", "check:contrast never reads this SVG."],
  [F + 198]: ["CONTRACT", H, "copy law"],
  [F + 199]: ["HISTORY", "record of a deleted assertion", null],
  [F + 200]: ["WHY", "reason kept; refactor story moved", "The claim is that Cache-Control is set, by helper or constant."],
  [F + 201]: ["WHY", "already short"],
  [F + 202]: ["CONTRACT", H, "artifact parity"],
  [F + 208]: ["NUMBER", "floor asserted in code; summing history moved", "Measured by running the section, never by summing."],
  [F + 209]: ["WHY", "reason kept; measurements moved", "Whole-gate floor: section floors cannot see another section stopping."],
  [F + 210]: ["NUMBER", "floor asserted in code; incident and measurements moved", "Within the tolerance `scripts/check-floors.mjs` owns; re-measure by running the gate."],
};
