/**
 * Publication record for the CV and publications surfaces.
 *
 * Structured content edited by commit, so it lives here rather than in the D1
 * `posts` table, following the precedent set by phage-hunters.ts. PDFs are
 * committed under public/publications/ and served as static assets, which are
 * a separate limit from the Worker script size and so cost the bundle nothing.
 *
 * Every record carries `access` even though most are self-hosted, so a single
 * publication can be switched to an external link without a schema change.
 * Year is the Crossref published-print year, which is authoritative here and
 * disagrees with ORCID on four records.
 */

export type TopicId =
  | "human-simian-retroviruses"
  | "avian-retroviruses"
  | "bacteriophages"
  | "science-education";

export type PublicationType =
  | "article"
  | "review"
  | "chapter"
  | "abstract"
  | "teaching-resource";

export type Access = "self-hosted" | "external";

export type Topic = {
  id: TopicId;
  label: string;
  description: string;
};

export type Publication = {
  id: string;
  title: string;
  authors: string[];
  journal: string | null;
  year: number;
  /**
   * The deposited date at its own precision: YYYY-MM-DD, YYYY-MM or YYYY.
   * `year` stays the grouping key; this is what `citation_publication_date`
   * needs, and 28 of the 36 records carry a day.
   */
  publishedDate: string | null;
  volume: string | null;
  issue: string | null;
  pages: string | null;
  /** Set only where `pages` is genuinely a range or a first page. */
  firstPage: string | null;
  lastPage: string | null;
  doi: string;
  pmid: string | null;
  pmcid: string | null;
  pmcUrl: string | null;
  type: PublicationType;
  topics: TopicId[];
  access: Access;
  /** Set when access is "self-hosted". */
  pdfPath: string | null;
  /** Set when access is "external". */
  externalUrl: string | null;
  /** Preprint of this record, where one exists. */
  preprintDoi: string | null;
  isOpenAccess: boolean;
  license: string | null;
  /**
   * WHICH registry said so, and at what content-version. `crossref:tdm-only`
   * is a measured answer and not an absence: it means the publisher deposited
   * terms and they were text-mining terms, which license redistribution to
   * nobody. A null means no terms were found at either registry.
   */
  licenseSource: string | null;
  /**
   * A PLAIN-LANGUAGE LINE, written by hand, or null.
   *
   * One sentence, under 200 characters, saying what the paper found in words a
   * non-specialist reads. NOT a summary of the abstract: the abstract is already
   * on the page, and a shorter paraphrase of it in the same voice would be
   * noise. This is the sentence somebody would say out loud.
   *
   * Null on every record until Dustin writes one. The page renders it only
   * where it exists, which is why an empty field is a state rather than a gap.
   * `check:publications` enforces the length, the single sentence and the
   * house dash rule; it cannot enforce that the sentence is any good.
   */
  summary: string | null;
  /**
   * A RETRACTION, CORRECTION OR EXPRESSION OF CONCERN, or null.
   *
   * Null on every record, and measured rather than assumed: no `updated-by`
   * and no `relation` on any of the 34 Crossref DOIs, read 2026-09-12. The
   * field exists so that the day one arrives is a data change and not a code
   * change, which is the day nobody wants to be writing this. `doi` is the
   * NOTICE's DOI: a paper carries `updated-by` pointing at the notice, and
   * the notice carries `update-to` pointing back.
   *
   * The shape and the sentence belong to `app/lib/publications/update-notice.mjs`,
   * which `check:publications` validates every record through and
   * `test/publication-update-notice.test.mjs` drives with a real retracted DOI.
   */
  updateNotice: {
    type: "retraction" | "correction" | "expression-of-concern";
    doi: string;
    date: string | null;
  } | null;
  /**
   * SEQUENCE ACCESSIONS THIS PAPER DEPOSITED, read from its own
   * data-availability statement and from nowhere else.
   *
   * Empty on every record whose journal requires no such statement. A bare
   * accession regex over a PDF returns the COMPARISON organisms' deposits, which
   * is a wrong citation rather than a missing one: the grounds, and the three
   * measured cases, are on `app/lib/publications/accessions.mjs`.
   * `check:publications` reconciles this against the extracted text in both
   * directions.
   */
  accessions: { kind: string; id: string }[];
  selected: boolean;
  abstract: string | null;
};

export const TOPICS: Topic[] = [
  {
    id: "human-simian-retroviruses",
    label: "Human and simian retroviruses",
    description: "HTLV-1 accessory proteins and how related retroviruses establish infection and persistence",
  },
  {
    id: "avian-retroviruses",
    label: "Avian retroviruses",
    description: "Reticuloendotheliosis virus and related retroviruses in wild bird populations",
  },
  {
    id: "bacteriophages",
    label: "Bacteriophages",
    description: "Phage genomics with undergraduate researchers",
  },
  {
    id: "science-education",
    label: "Science education",
    description: "Turning coursework into real research, and public attitudes toward science",
  },
];

/** Newest first. */
export const PUBLICATIONS: Publication[] = [
  {
    id: "edwards-2026-communication-rubrics",
    title: "Science communication tools: rubrics for generating posters and manuscripts that are authentic to the practice of science",
    authors: ["Tamarah Lynne Adair", "Swati Agrawal", "Yesmi P. Ahumada-Santos", "Regina Alvarez", "Kirk R. Anders", "Mauricio Antunes", "Mary Ayuk", "María Elena Báez-Flores", "Dondra Bailey", "Frederick N. Baliraine", "Mitchell F. Balish", "Christa Tobey Bancroft", "Michèle Barmoy", "Tonya C. Bates", "Andrea Beyer", "Suparna Bhalla", "Dave Bollivar", "Lisa M. Bono", "Rebecca Bortz", "Tejas Bouklas", "Kristen Butela", "Christine A. Byrum", "Megan Carroll", "Steven Michael Caruso", "Nancy Castro", "Kari Clase", "Kristen Clermont", "Sean T. Coleman", "Pamela L. Connerly", "Amaya M. Garcia Costas", "Steven Gaines Cresawn", "Tom D'Elia", "Aimee Danley", "Megan K. Dennis", "Arturo Diaz", "Erin L. Doyle", "Iain Duffy", "Dustin Cole Edwards", "Elvira Eivazova", "Eric Engstrom", "Christy Fillman", "Christine L. Fleischacker", "Victoria J. Frost", "Julie Torruellas Garcia", "Bryan P. Gibb", "Alyssa Mae Gleichsner", "Sharon Gusky", "Rebekah F. Hare", "Danielle Heller", "Lee E. Hughes", "Jacob D. Kagey", "Bridgette Kirkpatrick", "Karen K. Klyczek", "Kathryn P. Kohl", "Hari Kotturi", "Julia Y. Lee-Soety", "Heather Lindberg", "Bhaswati Manish", "Sergei A. Markov", "Matthew David Mastropaolo", "James T. Melton", "Jon Mitchell", "Sally Dixon Molloy", "Denise L. Monti", "Tiara Perez Morales", "María Alejandra Mussi", "Holly Nance", "Fernando Nieto", "Imade Yolanda Nsa", "Shallee T. Page", "Ricardo Parra-Unda", "Vipaporn Phuntumart", "Brett E. Pickett", "Richard Scott Pollenz", "Sarah N. Reardon", "Jessica Rocheleau", "Ombeline Rossier", "Naomi Smith Rowland", "Adam D. Rudner", "Elizabeth E. Rueschhoff", "Viknesh Sivanathan", "Martha Smith Caldas", "C. Nicole Sunnen", "Sarah J. Swerdlow", "Kissaou Tchedre", "Kara Thoemke", "Deborah Tobiason", "Sara S. Tolsma", "Tara Turley-Stoulig", "Quinn Vega", "Patricia Waikel", "Catherine Ward", "Vassie C. Ware", "Jackie M. Washington", "Daniel Eric Westholm", "Beth Wilkes", "Daniel Williams", "Elizabeth Williams", "Ellen M. Wisner"],
    journal: "Journal of Microbiology &amp; Biology Education",
    year: 2026,
    publishedDate: "2026-04-30",
    volume: "27",
    issue: "1",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/jmbe.00313-25",
    pmid: "41733342",
    pmcid: "PMC13130995",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13130995/",
    type: "article",
    topics: ["science-education"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-jmbe-00313-25/10-1128-jmbe-00313-25.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by-nc-nd",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Two rubrics for grading student posters and short papers in research courses, written by about 100 SEA-PHAGES faculty.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Traditional undergraduate science courses often prioritize content mastery over authentic engagement with the scientific process. Course-based research, also referred to as course-based undergraduate research experiences (CUREs), addresses this limitation by immersing students in authentic scientific practice. In course-based research, assessment practices can also mirror the authentic scientific practice, where extensive formative feedback supports refinement of skills and understanding. Here, we present two rubrics designed to support the teaching and assessment of science communication in a way that reflects how scientists prepare to disseminate their research findings. One rubric is for creating scientific posters and another for writing short-format manuscripts. Developed by approximately 100 faculty members who collaboratively implement CUREs through the Howard Hughes Medical Institute (HHMI) Science Education Alliance (SEA) program, these rubrics outline the authentic steps scientists take when preparing to communicate their research and provide performance levels that clarify expectations for both students and instructors. Together, these tools aim to further align undergraduate science education and authentic scientific practice.",
  },
  {
    id: "edwards-2025-covid-vaccines",
    title: "Acceptance, perceptions, and compliance for COVID-19 vaccines among students attending a rural university: An interventional study using brief video messages",
    authors: ["Amber L. Harris Bozer", "Subi Gandhi", "Dustin C. Edwards"],
    journal: "Journal of American College Health",
    year: 2025,
    publishedDate: "2025-11-26",
    volume: "73",
    issue: "10",
    pages: "4056-4070",
    firstPage: "4056",
    lastPage: "4070",
    doi: "10.1080/07448481.2025.2472184",
    pmid: null,
    pmcid: null,
    pmcUrl: null,
    type: "article",
    topics: ["science-education"],
    access: "self-hosted",
    pdfPath: "/publications/10-1080-07448481-2025-2472184/10-1080-07448481-2025-2472184.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: false,
    license: null,
    licenseSource: "none-deposited",
    summary: "Short videos did not change COVID-19 vaccine attitudes among 298 students at a rural Texas university.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Objective: The purpose of this study was to examine the factors associated with vaccine compliance and the effectiveness of short-term video interventions on COVID-19 vaccine perceptions among students attending a state university located in rural Texas. Participants: A total of 298 students participated in an online survey. Methods: Students completed the COVID-19 Vaccine Acceptance Scale (COVID-VAC) and Perceptions of Vaccines Scale before and after watching one of three videos (neutral, educational, or disease effects). Results: Differences in vaccination status were observed for ethnicity and political leanings ( p p > 0.05). Conclusions: Short-term video interventions were ineffective in altering vaccine perceptions and improving acceptance of the COVID-19 vaccine in our study population. Impact of the type and duration of educational videos should be explored by future studies to combat vaccine hesitancy in future population-based studies.",
  },
  {
    id: "edwards-2025-godfather",
    title: "Complete genome sequence of bacteriophage Godfather isolated from Microbacterium foliorum",
    authors: ["Joshua Hutchings", "Lauren Bower", "Ethan Collum", "Timothy Hester", "Melody Hunter", "Chaney Kelly", "Luke Reynolds", "Cole Moore", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2025,
    publishedDate: "2025-02-11",
    volume: "14",
    issue: "2",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/mra.00888-24",
    pmid: "39817740",
    pmcid: "PMC11812392",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11812392/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-00888-24/10-1128-mra-00888-24.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of phage Godfather, isolated from Stephenville soil; 17,452 bp, 24 genes, cluster EE.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"PP725414"},{"kind":"sra","id":"SRX24892095"}],
    selected: false,
    abstract: "Microbacteriophage Godfather was collected from a soil sample in Stephenville, Texas. The 17,452-bp double-stranded genome contains 24 protein-coding genes. The genome shares &gt;99% nucleotide sequence identity with cluster EE microbacteriophages Scamander, Danno, Kojax4, and Burgy.",
  },
  {
    id: "edwards-2025-phage-therapy",
    title: "Exploration of Providers’ Perceptions and Attitudes Toward Phage Therapy and Intentions for Future Adoption as an Alternative to Traditional Antibiotics in the US—A Cross-Sectional Study",
    authors: ["Subi Gandhi", "Dustin Edwards", "Keith Emmert", "Bonnie Large"],
    journal: "International Journal of Environmental Research and Public Health",
    year: 2025,
    publishedDate: "2025-07-18",
    volume: "22",
    issue: "7",
    pages: "1139",
    firstPage: "1139",
    lastPage: null,
    doi: "10.3390/ijerph22071139",
    pmid: "40724203",
    pmcid: "PMC12294182",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12294182/",
    type: "article",
    topics: ["bacteriophages", "science-education"],
    access: "self-hosted",
    pdfPath: "/publications/10-3390-ijerph22071139/10-3390-ijerph22071139.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Survey of 196 US clinicians: 49 percent knew about phage therapy, 56 percent would consider using it.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Antibiotic resistance presents a global threat, making the swift development of alternative treatments essential. Phage therapy, which employs bacterial viruses that specifically target bacteria, shows promise. Although this method has been utilized for over a century, primarily in Eastern Europe, its use in the US remains limited. This study aimed to assess the awareness and willingness of US healthcare providers to adopt phage therapy in response to the growing issue of antibiotic resistance. A survey of 196 healthcare providers, primarily MDs and DOs, found that while 99% were aware of antimicrobial resistance, only 49% were knowledgeable about phage therapy as a treatment for resistant bacterial infections. Nonetheless, 56% were open to considering phage therapy, and this willingness was associated with prior knowledge, concerns about antibiotic resistance, previous training, and confidence in recommending it (p &lt; 0.05). Our study of U.S. healthcare providers revealed key findings about their views on phage therapy as a potential alternative for treating bacterial infections. Credible information is essential to promoting phage therapy use among U.S. providers via educational initiatives, clinical guidance, and research dissemination to promote phage therapy use among U.S. providers. Evidence-based education and clinical guidance help providers make sound decisions on the appropriate and safe use of phage therapy.",
  },
  {
    id: "edwards-2024-irec",
    title: "An inclusive Research and Education Community (iREC) model to facilitate undergraduate science education reform",
    authors: ["Denise L. Monti", "Julia C. Gill", "Tamarah L. Adair", "Sandra D. Adams", "Yesmi Patricia Ahumada-Santos", "Isabel Amaya", "Kirk Anders", "Justin R. Anderson", "Mauricio S. Antunes", "Mary Ayuk", "Frederick Baliraine", "Tonya C. Bates", "Andrea R. Beyer", "Suparna Bhalla", "Tejas Bouklas", "Sharon K. Bullock", "Kristen A. Butela", "Christine Byrum", "Steven M. Caruso", "Rebecca Chong", "Hui-Min Chung", "Stephanie B. Conant", "Brett Condon", "Katie E. Crump", "Tom D'Elia", "Megan K. Dennis", "Linda C. DeVeaux", "Lautaro Diacovich", "Arturo Diaz", "Iain Duffy", "Dustin Edwards", "Patricia C. Fallest-Strobl", "Ann Findley", "Matthew R. Fisher", "Marie P. Fogarty", "Victoria Jane Frost", "Maria D. Gainey", "Courtney S. Galle", "Bryan Gibb", "Urszula Golebiewska", "Hugo Gramajo", "Anna S. Grinath", "Jennifer Guerrero", "Nancy Guild", "Kathryn E. Gunn", "Susan Gurney", "Lee E. Hughes", "Pradeepa Jayachandran", "Kristen Johnson", "Allison Johnson", "Alison E. Kanak", "Michelle L. Kanther", "Rodney A. King", "Kathryn Kohl", "Julia Lee-Soety", "Lynn O. Lewis", "Heather Lindberg", "Jaclyn A. Madden", "Breonna J. Martin", "Matthew D. Mastropaolo", "Sean McClory", "Evan C. Merkhofer", "Julie A. Merkle", "Jon Mitchell", "María Alejandra Mussi", "Fernando Nieto", "Jillian Nissen", "Imade Yolanda Nsa", "Mary G. O'Donnell", "R. Deborah Overath", "Shallee T. Page", "Andrea Panagakis", "Jesús Ricardo Parra Unda", "Michelle B. Pass", "Tiara Perez Morales", "Nick T. Peters", "Ruth Plymale", "Richard Pollenz", "Nathan S. Reyna", "Claire A. Rinehart", "Jessica Rocheleau", "John S. Rombold", "Ombeline Rossier", "Adam D. Rudner", "Elizabeth E. Rueschhoff", "Christopher D. Shaffer", "Mary Ann V. Smith", "Amy B. Sprenkle", "C. Nicole Sunnen", "Michael A. Thomas", "Michelle M. Tigges", "Deborah Tobiason", "Sara Sybesma Tolsma", "Julie Torruellas Garcia", "Peter Uetz", "Edwin Vazquez", "Catherine M. Ward", "Vassie C. Ware", "Jacqueline M. Washington", "Matthew J. Waterman", "Daniel E. Westholm", "Keith A. Wheaton", "Simon J. White", "Elizabeth C. Williams", "Daniel C. Williams", "Ellen M. Wisner", "William H. Biederman", "Steven G. Cresawn", "Danielle M. Heller", "Deborah Jacobs-Sera", "Daniel A. Russell", "Graham F. Hatfull", "David J. Asai", "David I. Hanauer", "Mark J. Graham", "Viknesh Sivanathan"],
    journal: "Frontiers in Education",
    year: 2024,
    publishedDate: "2024-08-21",
    volume: "9",
    issue: null,
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.3389/feduc.2024.1442318",
    pmid: "39686966",
    pmcid: "PMC11649309",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11649309/",
    type: "article",
    topics: ["science-education"],
    access: "self-hosted",
    pdfPath: "/publications/10-3389-feduc-2024-1442318/10-3389-feduc-2024-1442318.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "How the SEA-PHAGES faculty community adopts and improves research courses over time, from interviews with over 100 members.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Over the last two decades, there have been numerous initiatives to improve undergraduate student outcomes in STEM. One model for scalable reform is the inclusive Research Education Community (iREC). In an iREC, STEM faculty from colleges and universities across the nation are supported to adopt and sustainably implement course-based research – a form of science pedagogy that enhances student learning and persistence in science. In this study, we used pathway modeling to develop a qualitative description that explicates the HHMI Science Education Alliance (SEA) iREC as a model for facilitating the successful adoption and continued advancement of new curricular content and pedagogy. In particular, outcomes that faculty realize through their participation in the SEA iREC were identified, organized by time, and functionally linked. The resulting pathway model was then revised and refined based on several rounds of feedback from over 100 faculty members in the SEA iREC who participated in the study. Our results show that in an iREC, STEM faculty organized as a long-standing community of practice leverage one another, outside expertise, and data to adopt, implement, and iteratively advance their pedagogy. The opportunity to collaborate in this manner and, additionally, to be recognized for pedagogical contributions sustainably engages STEM faculty in the advancement of their pedagogy. Here, we present a detailed pathway model of SEA that, together with underpinning features of an iREC identified in this study, offers a framework to facilitate transformations in undergraduate science education.",
  },
  {
    id: "edwards-2024-faculty-identity",
    title: "The professional identity of STEM faculty as instructors of course-based research experiences",
    authors: ["David Hanauer", "Richard Alvey", "Ping An", "Christa Bancroft", "Kristen Butela", "Sean Coleman", "Kari L. Clase", "Parks Collins", "Stephanie Conant", "Pamela Connerly", "Bernadette Connors", "Megan K. Dennis", "Erin L. Doyle", "Dustin Edwards", "Christy Fillman", "Ann Findley", "Victoria J. Frost", "Maria Gainey", "Urszula Golebiewska", "Nancy Guild", "Sharon B. Gusky", "Allison Johnson", "Kristen Johnson", "Karen K. Klyczek", "Julia Lee-Soety", "Heather Lindberg", "Matthew D. Mastropaolo", "Julie A. Merkle", "Jon Mitchell", "Sally Molloy", "Fernando Nieto", "Jillian Nissen", "Tiara Perez Morales", "Nick T. Peters", "Susanne P. Pfeifer", "Richard Pollenz", "Mary L. Preuss", "Germán Rosas-Acosta", "Margaret S. Saha", "Amy Sprenkle", "C. Nicole Sunnen", "Deborah Tobiason", "Sara S. Tolsma", "Vassie Ware", "Yesmi Patricia Ahumada-Santos", "Regina V. Alvarez", "Justin Anderson", "Mary Ayuk", "María Elena Báez-Flores", "Dondra Bailey", "Frederick Baliraine", "Elizabeth Behr", "Andrea R. Beyer", "Suparna Bhalla", "Lisa M. Bono", "Donald P. Breakwell", "Christine Byrum", "Iain Duffy", "Alyssa Gleichsner", "Melinda Harrison", "Renee Ho", "Lee E. Hughes", "Jacob D. Kagey", "Kathryn Kohl", "Sean McClory", "Alison Moyer", "Maria A. Mussi", "Holly Nance", "Imade Y. Nsa", "Shallee T. Page", "Jesús Ricardo Parra Unda", "Jessica Rocheleau", "Sarah Swerdlow", "Kara Thoemke", "Megan S. Valentine", "Quinn C. Vega", "Catherine Ward", "Daniel C. Williams", "Ellen Wisner", "William H. Biederman", "Steven G. Cresawn", "Mark J. Graham", "Graham Hatfull", "Danielle Heller", "Deborah Jacobs-Sera", "Denise Monti", "Pushpa Ramakrishna", "Daniel Russell", "Viknesh Sivanathan"],
    journal: "Frontiers in Education",
    year: 2024,
    publishedDate: "2024-10-24",
    volume: "9",
    issue: null,
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.3389/feduc.2024.1442306",
    pmid: "39686967",
    pmcid: "PMC11649311",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11649311/",
    type: "article",
    topics: ["science-education"],
    access: "self-hosted",
    pdfPath: "/publications/10-3389-feduc-2024-1442306/10-3389-feduc-2024-1442306.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "What 97 instructors of research courses say about being a scientist and a teacher at the same time.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "The professional identity of scientists has historically been cultivated to value research over teaching, which can undermine initiatives that aim to reform science education. Course-Based Research Experiences (CRE) and the inclusive Research and Education Communities (iREC) are two successful and impactful reform efforts that integrate research and teaching. The aim of this study is to explicate the professional identity of instructors who implement a CRE within an established iREC and to explore how this identity contributes to the success of these programs. 97 CRE instructors from the Science Education Alliance (SEA) iREC participated in a 2-year, multi-stage, qualitative research project that involved weekly reflective journaling, autoethnographic description, small group evaluation and writing, and large-scale community checking. The resulting description of professional identity consisted of shared values (inclusivity, student success, community membership, ownership/agency, science, overcoming failure, and persistence), specified roles (mentor, advocate, scientist, educator, motivator, collaborator, community builder, learner, evaluator and project manager) and a stated sense of self (dedicated, resilient, pride in students, multiskilled, valued, community member, responsible and overworked). Analysis of individual reflective diary entries revealed how a professional identity underpinned and facilitated the ways in which faculty addressed challenges that arose and worked toward the success of every student. It is the self-concept of the professional identity of the instructor in the context of the CRE classroom that directed the extended commitment and effort that these instructors evidently put into their work with students, which facilitated student engagement, student persistence, and their collective scientific output. The study concludes that a professional identity of STEM faculty in the context of a CRE and iREC combines being a researcher and educator, and that this integrated identity is central for current initiatives aimed at transforming undergraduate STEM education.",
  },
  {
    id: "edwards-2024-writing-microbiology-resource",
    title: "Writing Microbiology Resource Announcements (MRA)",
    authors: ["Arturo Diaz", "Julia Lee-Soety", "Shima Chaudhary", "Denise Monti", "Viknesh Sivanathan", "Richard Pollenz", "Alison Kanak", "Amy Sprenkle", "Andrea Beyer", "Bridgette Kirkpatrick", "Carole Twichell", "Christine Byrum", "Deborah Tobiason", "Dustin Edwards", "Elizabeth Godin", "Emily Savage", "Heather Lindberg", "Holly Nance", "Jessica Rocheleau", "Julie Garcia", "Kathryn Dye", "Kristen Butela", "Lisa Bono", "Matthew Mastropaolo", "Megan Dennis", "Naomi Rowland", "Quinn Vega", "Regina Alvarez", "Rocky Ng", "Ruth Plymale", "Sergei Markov", "Steven Caruso", "Tara Stoulig", "Tiara Perez", "Vassie Ware", "Veronique Delesalle", "Adam Rudner", "Beth Wilkes", "Christa Bancroft", "Christine Fleischacker", "Eric Engstrom", "Frederick Baliraine", "Hari Kotturi", "Jacqueline Washington", "James Shanks", "Lee Hughes", "Matthew Fisher", "Pamela Connerly", "Patricia Waikel", "Sarah Reardon", "Sean Coleman", "Shallee Page", "Swati Agrawal", "Tamarah Adair", "Thomas Ndolo", "Alexandra Jerby", "Amanda Freise", "Amaya Costas", "Christy Fillman", "Dane Bowder", "Daniel Westholm", "Daniel Williams", "Ellen Wisner", "Jennifer Guerrero", "Joseph Stukey", "Karen Klyczek", "Kari Clase", "Maria Gainey", "MARY AYUK", "Mauricio Antunes", "Rebecca Bortz", "Steven Cresawn", "Suparna Bhalla", "Victoria Frost", "C. Sunnen", "Mitchell Balish", "Brett Pickett", "Claire Rinehart", "Luis Actis", "Megan Valentine", "Alyssa Gleichsner", "Melissa Harrison", "Jennifer Broderick", "Sally Molloy", "Gerry Zegers", "Jared Stees", "Kara Thoemke", "Rodney King", "Liz Williams", "Jon Mitchell", "John Rombold", "Kissaou Tchedre", "Edwin Vazquez", "Sharon Gusky", "Elvira Eivazova", "Dominique Dotson", "Alejandra Mussi", "Jacob Kagey", "Randy DeJong", "Catherine Ward", "Rebekah Hare", "Kathryn Kohl", "Imade Nsa", "Tejas Bouklas", "Sarah Tolsma", "Charlotte Berkes", "Melody Neely", "Aimee Danley"],
    journal: "QUBES Educational Resources",
    year: 2024,
    publishedDate: "2024",
    volume: null,
    issue: null,
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.25334/B5BS-F125",
    pmid: null,
    pmcid: null,
    pmcUrl: null,
    type: "teaching-resource",
    topics: ["science-education"],
    access: "external",
    pdfPath: null,
    externalUrl: "https://doi.org/10.25334/B5BS-F125",
    preprintDoi: null,
    isOpenAccess: false,
    license: null,
    licenseSource: "none-deposited",
    summary: "A classroom guide for writing a genome announcement as a group.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "This resources provides a framework for students to write a Microbiology Resource Announcement, collaboratively.",
  },
  {
    id: "edwards-2023-mraaronian",
    title: "Complete genome sequence of bacteriophage MrAaronian isolated from an Arthrobacter globiformis culture",
    authors: ["Ian Haines", "Jessica Blakely", "Ashley Branson", "Diana Estrada", "Rebeca Fernandez Robles", "Katelyn Fitzgerald", "Shelby Jeffers", "Timyee Leung", "Jasmine Munoz", "Ashley Olivos", "Anayeli Ramirez", "Caressa Smith", "Justin Spere", "Idaleth Tavarez", "Isabella Wood", "Ethan Zavala", "Madison Arrighi", "Angelica Coronel-Galindo", "Megan K. Dennis", "Marlee Goppert", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2023,
    publishedDate: "2023-12-14",
    volume: "12",
    issue: "12",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/MRA.00778-23",
    pmid: "37933970",
    pmcid: "PMC10720457",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10720457/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-00778-23/10-1128-mra-00778-23.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of phage MrAaronian, isolated from flowerbed soil in Poughkeepsie; 54,509 bp, 87 genes, cluster AW.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"OR159662"},{"kind":"sra","id":"SRX21368075"}],
    selected: false,
    abstract: "Arthrobacteriophage MrAaronian contains a 54,509 bp DNA genome with 87 predicted protein-coding genes. MrAaronian has siphovirus morphology and was collected from a flowerbed soil sample in Poughkeepsie, NY, and isolated on an Arthrobacter globiformis B-2979 culture. MrAaronian has &gt; 99% nucleotide identity with cluster AW arthrobacteriophages Michelle, Stayer, Sloopyjoe, and StarLord.",
  },
  {
    id: "edwards-2023-classroom-assessment",
    title: "Models of classroom assessment for course-based research experiences",
    authors: ["David I. Hanauer", "Tong Zhang", "Mark J. Graham", "Sandra D. Adams", "Yesmi Patricia Ahumada-Santos", "Richard M. Alvey", "Mauricio S. Antunes", "Mary A. Ayuk", "María Elena Báez-Flores", "Christa T. Bancroft", "Tonya C. Bates", "Meghan J. Bechman", "Elizabeth Behr", "Andrea R. Beyer", "Rebecca L. Bortz", "Dane M. Bowder", "Laura A. Briggs", "Victoria Brown-Kennerly", "Michael A. Buckholt", "Sharon K. Bullock", "Kristen A. Butela", "Christine A. Byrum", "Steven M. Caruso", "Catherine P. Chia", "Rebecca A. Chong", "Hui-Min Chung", "Kari L. Clase", "Sean T. Coleman", "D. Parks Collins", "Stephanie B. Conant", "Brett M. Condon", "Pamela L. Connerly", "Bernadette J. Connors", "Jennifer E. Cook-Easterwood", "Katie E. Crump", "Tom D’Elia", "Megan K. Dennis", "Linda C. DeVeaux", "Lautaro Diacovich", "Iain Duffy", "Nicholas P. Edgington", "Dustin C. Edwards", "Tenny O. G. Egwuatu", "Elvira R. Eivazova", "Patricia C. Fallest-Strobl", "Christy L. Fillman", "Ann M. Findley", "Emily Fisher", "Matthew R. Fisher", "Marie P. Fogarty", "Amanda C. Freise", "Victoria J. Frost", "Maria D. Gainey", "Amaya M. Garcia Costas", "Atenea A. Garza", "Hannah E. Gavin", "Raffaella Ghittoni", "Bryan Gibb", "Urszula P. Golebiewska", "Anna S. Grinath", "Susan M. R. Gurney", "Rebekah F. Hare", "Steven G. Heninger", "John M. Hinz", "Lee E. Hughes", "Pradeepa Jayachandran", "Kristen C. Johnson", "Allison A. Johnson", "Michelle Kanther", "Margaret Kenna", "Bridgette L. Kirkpatrick", "Karen K. Klyczek", "Kathryn P. Kohl", "Michael Kuchka", "Amber J. LaPeruta", "Julia Y. Lee-Soety", "Lynn O. Lewis", "Heather M. Lindberg", "Jaclyn A. Madden", "Sergei A. Markov", "Matthew D. Mastropaolo", "Vinayak Mathur", "Sean P. McClory", "Evan C. Merkhofer", "Julie A. Merkle", "Scott F. Michael", "Jon C. Mitchell", "Sally D. Molloy", "Denise L. Monti", "María Alejandra Mussi", "Holly Nance", "Fernando E. Nieto-Fernandez", "Jillian C. Nissen", "Imade Y. Nsa", "Mary G. O’Donnell", "Shallee T. Page", "Andrea Panagakis", "Jesús Ricardo Parra-Unda", "Tara A. Pelletier", "Tiara G. Perez Morales", "Nick T. Peters", "Vipaporn Phuntumart", "Richard S. Pollenz", "Mary L. Preuss", "David P. Puthoff", "Muideen K. Raifu", "Nathan S. Reyna", "Claire A. Rinehart", "Jessica M. Rocheleau", "Ombeline Rossier", "Adam D. Rudner", "Elizabeth E. Rueschhoff", "Amy Ryan", "Sanghamitra Saha", "Christopher D. Shaffer", "Mary Ann V. Smith", "Amy B. Sprenkle", "Christy L. Strong", "C. Nicole Sunnen", "Brian P. Tarbox", "Louise Temple", "Kara R. Thoemke", "Michael A. Thomas", "Deborah M. Tobiason", "Sara S. Tolsma", "Julie Torruellas Garcia", "Megan S. Valentine", "Edwin Vazquez", "Robert E. Ward", "Catherine M. Ward", "Vassie C. Ware", "Marcie H. Warner", "Jacqueline M. Washington", "Daniel E. Westholm", "Keith A. Wheaton", "Beth M. Wilkes", "Elizabeth C. Williams", "William H. Biederman", "Steven G. Cresawn", "Danielle M. Heller", "Deborah Jacobs-Sera", "Graham F. Hatfull", "David J. Asai", "Viknesh Sivanathan"],
    journal: "Frontiers in Education",
    year: 2023,
    publishedDate: "2023-11-28",
    volume: "8",
    issue: null,
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.3389/feduc.2023.1279921",
    pmid: "39687267",
    pmcid: "PMC11649310",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11649310/",
    type: "article",
    topics: ["science-education"],
    access: "self-hosted",
    pdfPath: "/publications/10-3389-feduc-2023-1279921/10-3389-feduc-2023-1279921.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "How experienced instructors assess and grade students in research courses.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Course-based research pedagogy involves positioning students as contributors to authentic research projects as part of an engaging educational experience that promotes their learning and persistence in science. To develop a model for assessing and grading students engaged in this type of learning experience, the assessment aims and practices of a community of experienced course-based research instructors were collected and analyzed. This approach defines four aims of course-based research assessment—(1) Assessing Laboratory Work and Scientific Thinking; (2) Evaluating Mastery of Concepts, Quantitative Thinking and Skills; (3) Appraising Forms of Scientific Communication; and (4) Metacognition of Learning—along with a set of practices for each aim. These aims and practices of assessment were then integrated with previously developed models of course-based research instruction to reveal an assessment program in which instructors provide extensive feedback to support productive student engagement in research while grading those aspects of research that are necessary for the student to succeed. Assessment conducted in this way delicately balances the need to facilitate students’ ongoing research with the requirement of a final grade without undercutting the important aims of a CRE education.",
  },
  {
    id: "edwards-2022-fizzles",
    title: "Complete Genome Sequence of Bacteriophage Fizzles, Isolated from Microbacterium foliorum",
    authors: ["Skyler Adams", "Gabrielle Spotz", "Riley Babcock", "Chloe Butler", "Samantha Conger", "Madison Crew", "Stephanie Garcia", "Joanna Gonzalez", "Jocelyn Hodges", "Alondra Martinez", "Samuel Munoz", "Chloe O’Grady", "Abigail Quirl", "Kristin Sefcik", "Tanner Taylor", "Gustavo Vazquez", "Faith Cox", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2022,
    publishedDate: "2022-01-20",
    volume: "11",
    issue: "1",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/MRA.01077-21",
    pmid: "34989620",
    pmcid: "PMC8759393",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8759393/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-01077-21/10-1128-mra-01077-21.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of phage Fizzles, isolated from an ant hill in Stephenville; 62,078 bp, 104 genes, only 84 percent similar to its nearest relatives.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"MW924638"},{"kind":"sra","id":"SRX11067172"}],
    selected: false,
    abstract: "Microbacteriophage Fizzles has a 62,078-bp linear double-stranded DNA genome sequence, predicted to contain 104 protein-coding genes. Fizzles is a Siphoviridae actinobacteriophage isolated from an ant hill soil sample collected in Stephenville, TX. Microbacteriophage Fizzles has &gt;83.6% nucleotide identity with microbacteriophages Squash and Nike.",
  },
  {
    id: "edwards-2022-loca",
    title: "Complete Genome Sequence of Bacteriophage Loca, Isolated on a Microbacterium foliorum Culture",
    authors: ["Aurod Ounsinegad", "Megan Ashcraft", "Emily Bliss", "Dasire Brawley", "Grace Clements", "Austin Densmore", "Alexis Gastin", "Marisol Luciano", "Cole Moore", "Virginia Munoz", "Aryana Pernarelli", "Maci Pitner", "Esmae Velsen", "Kara Wiggam", "Marlee Goppert", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2022,
    publishedDate: "2022-10-20",
    volume: "11",
    issue: "10",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/mra.00783-22",
    pmid: "36066260",
    pmcid: "PMC9584219",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9584219/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-00783-22/10-1128-mra-00783-22.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of phage Loca, swabbed from a shopping cart handle in Stephenville; 17,475 bp, 25 genes.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"ON260814"},{"kind":"sra","id":"SRX14483214"}],
    selected: false,
    abstract: "Microbacteriophage Loca was extracted from a shopping cart handle swab sample in Stephenville, TX, and isolated on a Microbacterium foliorum NRRL-24224 culture. The 17,475-bp double-stranded DNA genome contains 25 predicted protein-coding genes and has &gt;96% nucleotide identity to bacteriophages Quaker and Livingwater.",
  },
  {
    id: "edwards-2022-fowlpox",
    title: "Genome Sequence of Fowlpox Virus-Integrated Reticuloendotheliosis Virus from a Rio Grande Wild Turkey (Meleagris gallopavo intermedia)",
    authors: ["Bianca Willis", "Camille Trautman", "Faith Cox", "Tiffany Lujan", "Jason Hardin", "Robert Dittmar", "Camila Romano", "Jeff Brady", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2022,
    publishedDate: "2022-06-16",
    volume: "11",
    issue: "6",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/mra.00174-22",
    pmid: "35575555",
    pmcid: "PMC9202434",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9202434/",
    type: "article",
    topics: ["avian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-00174-22/10-1128-mra-00174-22.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "A reticuloendotheliosis virus genome found inserted inside a fowlpox virus from a wild turkey in Gillespie County, Texas.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"OL857287"},{"kind":"sra","id":"SRX11820217"}],
    selected: false,
    abstract: "We report the genome sequence of a nearly intact reticuloendotheliosis virus (REV) insertion within a field strain of fowlpox virus from a Rio Grande wild turkey in Gillespie County, TX. The proviral REV genome comprises 7,943 bp and contains partial long terminal repeats.",
  },
  {
    id: "edwards-2022-instructional-models",
    title: "Instructional Models for Course-Based Research Experience (CRE) Teaching",
    authors: ["David I. Hanauer", "Mark J. Graham", "Rachel J. Arnold", "Mary A. Ayuk", "Mitchell F. Balish", "Andrea R. Beyer", "Kristen A. Butela", "Christine A. Byrum", "Catherine P. Chia", "Hui-Min Chung", "Kari L. Clase", "Stephanie Conant", "Roy J. Coomans", "Tom D’Elia", "Jason Diaz", "Arturo Diaz", "Jean A. Doty", "Nicholas P. Edgington", "Dustin C. Edwards", "Elvira Eivazova", "Christine B. Emmons", "Kayla M. Fast", "Emily J. Fisher", "Christine L. Fleischacker", "Gregory D. Frederick", "Amanda C. Freise", "Maria D. Gainey", "Chris R. Gissendanner", "Urszula P. Golebiewska", "Nancy A. Guild", "Heather L. Hendrickson", "Christopher D. Herren", "Margaret S. Hopson-Fernandes", "Lee E. Hughes", "Deborah Jacobs-Sera", "Allison A. Johnson", "Bridgette L. Kirkpatrick", "Karen K. Klyczek", "Ann P. Koga", "Hari Kotturi", "Janine LeBlanc-Straceski", "Julia Y. Lee-Soety", "Justin E. Leonard", "Matthew D. Mastropaolo", "Evan C. Merkhofer", "Scott F. Michael", "Jon C. Mitchell", "Swarna Mohan", "Denise L. Monti", "Christos Noutsos", "Imade Y. Nsa", "Nick T. Peters", "Ruth Plymale", "Richard S. Pollenz", "Megan L. Porter", "Claire A. Rinehart", "German Rosas-Acosta", "Joseph F. Ross", "Michael R. Rubin", "Anne E. Scherer", "Stephanie C. Schroeder", "Christopher D. Shaffer", "Amy B. Sprenkle", "C. Nicole Sunnen", "Sarah J. Swerdlow", "Deborah Tobiason", "Sara S. Tolsma", "Philippos K. Tsourkas", "Robert E. Ward", "Vassie C. Ware", "Marcie H. Warner", "Jacqueline M. Washington", "Kristi M. Westover", "Simon J. White", "JoAnn L. Whitefleet-Smith", "Daniel C. Williams", "Michael J. Wolyniak", "Jill H. Zeilstra-Ryalls", "David J. Asai", "Graham F. Hatfull", "Viknesh Sivanathan"],
    journal: "CBE—Life Sciences Education",
    year: 2022,
    publishedDate: "2022-03",
    volume: "21",
    issue: "1",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1187/cbe.21-03-0057",
    pmid: "34978921",
    pmcid: "PMC9250372",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9250372/",
    type: "article",
    topics: ["science-education"],
    access: "self-hosted",
    pdfPath: "/publications/10-1187-cbe-21-03-0057/10-1187-cbe-21-03-0057.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by-nc-sa",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Three models for how instructors teach research courses.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "A report on research that explicates three models of pedagogical practice that underpin and characterize inquiry instruction in a course-based research experience.",
  },
  {
    id: "edwards-2022-lymphoproliferative",
    title: "Molecular Surveillance for Lymphoproliferative Disease Virus and Reticuloendotheliosis Virus in Rio Grande Wild Turkeys (Meleagris gallopavo intermedia) in Texas, USA",
    authors: ["Faith Cox", "Jason Hardin", "Robert Dittmar", "Dustin Edwards"],
    journal: "Journal of Wildlife Diseases",
    year: 2022,
    publishedDate: "2022-11-30",
    volume: "58",
    issue: "4",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.7589/JWD-D-22-00023",
    pmid: null,
    pmcid: null,
    pmcUrl: null,
    type: "article",
    topics: ["avian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-7589-jwd-d-22-00023/10-7589-jwd-d-22-00023.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: false,
    license: null,
    licenseSource: "none-deposited",
    summary: "First detection of lymphoproliferative disease virus in Texas wild turkeys; 373 birds tested, about 4 percent positive in affected counties.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Reticuloendotheliosis virus (REV) and lymphoproliferative disease virus (LPDV) are avian retroviruses that can cause neoplastic disease and present with similar pathologies. Lymphoproliferative disease virus has been reported in the Eastern US and states bordering Texas, USA, but has not been previously detected within the state. In a prior study, we detected REV in native Rio Grande Wild Turkeys (Meleagris gallopavo intermedia) and an Eastern Wild Turkey (Meleagris gallopavo silvestris) originating from West Virginia. Given LPDV detection in states bordering Texas and our finding of an REV-positive Eastern Wild Turkey imported from a LPDV endemic region, we sought to determine LPDV prevalence in Texas and continue surveillance for REV. During 2018-20, dried blood spots from 373 individual Rio Grande Wild Turkeys from 20 different counties were tested for the presence of proviral REV or LPDV DNA. In affected counties, approximately 4% of individuals were infected with REV (7/197) or LPDV (10/273) and one bird was coinfected with both viruses. Phylogenetic analysis indicated a close relationship of the LPDV isolates to variants from other Southern and Central states. This study provides molecular evidence of LPDV in Texas, and continued surveillance is necessary to determine the potential effects of the virus on reproductive success, coinfections, and overall health of Wild Turkey populations.",
  },
  {
    id: "edwards-2022-prairie-chicken",
    title: "Near-Complete Proviral Genome Sequence of Reticuloendotheliosis Virus Isolated from an Attwater’s Prairie Chicken (Tympanuchus cupido attwateri)",
    authors: ["Bianca Willis", "Brittany Stewart", "Faith Cox", "Tiffany Lujan", "Holly Haefele", "Camila Romano", "Jeff Brady", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2022,
    publishedDate: "2022-04-21",
    volume: "11",
    issue: "4",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/mra.00173-22",
    pmid: "35319244",
    pmcid: "PMC9022497",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9022497/",
    type: "article",
    topics: ["avian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-00173-22/10-1128-mra-00173-22.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of the reticuloendotheliosis virus from the 2016 to 2017 outbreak in captive Attwater's prairie chickens.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"OL857288"},{"kind":"sra","id":"SRX11820216"},{"kind":"sra","id":"SRX13461851"}],
    selected: false,
    abstract: "We report the near-complete proviral genome sequence of a reticuloendotheliosis virus isolated and propagated from an endangered Attwater’s prairie chicken (Tympanuchus cupido attwateri) during a 2016–2017 outbreak at a captive breeding facility.",
  },
  {
    id: "edwards-2021-indylu",
    title: "Complete Genome Sequence of Bacteriophage IndyLu, Isolated from a Microbacterium foliorum Culture",
    authors: ["Ashley Suris", "Selina Alvarado", "Tommy Butler", "Carlos Canales", "Matthew Castro", "Julia Gaston", "Marlee Goppert", "Raylon Huckaby", "Jesse Laposky", "Jessica Lee", "Elizabeth Mullins", "Damla Ustundag", "Josue Zuniga", "Faith Cox", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2021,
    publishedDate: "2021-12-16",
    volume: "10",
    issue: "50",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/MRA.01079-21",
    pmid: "34913713",
    pmcid: "PMC8675261",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8675261/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-01079-21/10-1128-mra-01079-21.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of phage IndyLu, isolated from Stephenville soil; 41,958 bp, 71 genes, one tRNA.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"OK318958"},{"kind":"sra","id":"SRX12683423"}],
    selected: false,
    abstract: "Microbacteriophage IndyLu was isolated from Microbacterium foliorum NRRL B-24224. The 41,958-bp double-stranded DNA genome has 71 predicted protein coding genes and 1 tRNA. The lytic actinobacteriophage was extracted from soil samples collected in Stephenville, TX, and is related to cluster EB bacteriophages Didgeridoo and Lahqtemish.",
  },
  {
    id: "edwards-2021-joy99",
    title: "Complete Genome Sequence of Mycobacteriophage Joy99",
    authors: ["Faith Cox", "Josh Katuri", "Megan Adams", "Danielle Bachhofer", "Ashleigh Cooper", "Jessica Doty", "Miranda Fuentes", "Leeila Hanson", "Travis Miller", "Jonathan Musgrave", "Aleksey Palumbo", "Camille Trautman", "Julie Edwards", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2021,
    publishedDate: "2021-08-12",
    volume: "10",
    issue: "32",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/mra.00556-21",
    pmid: "34382830",
    pmcid: "PMC8359790",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8359790/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-00556-21/10-1128-mra-00556-21.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of phage Joy99, annotated by Bluff Dale High School students; 59,837 bp, 97 genes.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"MH536822"},{"kind":"sra","id":"SRX4721439"}],
    selected: false,
    abstract: "Joy99 is a siphoviral mycobacteriophage with a 59,837-base pair double-stranded DNA genome and is predicted to contain 97 protein-coding genes and a single tRNA gene. Joy99 was isolated in Saint Louis, MO, and annotated by students at Bluff Dale High School in community engagement with Tarleton State University.",
  },
  {
    id: "edwards-2021-tripl3t-zeuska",
    title: "Complete Genome Sequences of Mycobacterium Phages Tripl3t and Zeuska",
    authors: ["Faith Cox", "Tiffany Lujan", "Matthew Bristerpostma", "Rheaven Sandoval", "Haze Murphy", "Leah Dowell", "Jaime Merrill", "Julie Edwards", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2021,
    publishedDate: "2021-08-12",
    volume: "10",
    issue: "32",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/mra.00558-21",
    pmid: "34382828",
    pmcid: "PMC8359786",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8359786/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-00558-21/10-1128-mra-00558-21.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genomes of phages Tripl3t and Zeuska, annotated by Bluff Dale and Tolar high school students; about 53,600 bp each.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"MK524499"},{"kind":"genbank","id":"MK524506"},{"kind":"sra","id":"SRX4721438"},{"kind":"sra","id":"SRX4721441"}],
    selected: false,
    abstract: "Tripl3t and Zeuska are siphoviral bacteriophages that were isolated from Mycobacterium smegmatis mc 2 155 and contain double-stranded DNA genomes 53,565 bp and 53,598 bp in length, respectively. Tripl3t and Zeuska were annotated by students at Bluff Dale High School (Bluff Dale, TX) and Tolar High School (Tolar, TX) in community engagement with Tarleton State University.",
  },
  {
    id: "edwards-2021-understanding-restriction-enzyme",
    title: "Understanding Restriction Enzyme Digests",
    authors: ["Swati Agrawal", "Sara Anderson", "Dustin Edwards", "Bryan Gibb", "Matthew Mastropaolo"],
    journal: "QUBES Educational Resources",
    year: 2021,
    publishedDate: "2021",
    volume: null,
    issue: null,
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.25334/8CXE-6883",
    pmid: null,
    pmcid: null,
    pmcUrl: null,
    type: "teaching-resource",
    topics: ["science-education"],
    access: "external",
    pdfPath: null,
    externalUrl: "https://doi.org/10.25334/8CXE-6883",
    preprintDoi: null,
    isOpenAccess: false,
    license: null,
    licenseSource: "none-deposited",
    summary: "Four classroom exercises on restriction enzyme digests and why they are used to screen phage DNA.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Prior to submitting genomic DNA for sequencing, SEA students perform a restriction endonuclease digest with several enzymes, which provides a fast and cost-effective way of quickly screening isolated phages. The pattern of bands on the gel should be unique except for very closely related or identical phages, which is useful when trying to identify novel bacteriophages to send for sequencing and ultimately for annotation. Students often struggle with understanding what restriction enzymes are, how they work, and why this is an important step in phage characterization. The ‘Restriction Enzyme Digests’ set of teaching resources provides four active learning exercises that introduce students to restriction enzymes, demonstrate how they work, and why they are a useful tool in the lab and for bacteriophage identification.",
  },
  {
    id: "edwards-2020-muscovy-ducks",
    title: "Detection of Reticuloendotheliosis Virus in Muscovy Ducks, Wild Turkeys, and Chickens in Brazil",
    authors: ["Giovana S. Caleiro", "Cristina F. Nunes", "Paulo R. Urbano", "Karin Kirchgatter", "Jansen de Araujo", "Edison Luiz Durigon", "Luciano M. Thomazelli", "Brittany M. Stewart", "Dustin C. Edwards", "Camila M. Romano"],
    journal: "Journal of Wildlife Diseases",
    year: 2020,
    publishedDate: "2020-07-02",
    volume: "56",
    issue: "3",
    pages: "631",
    firstPage: "631",
    lastPage: null,
    doi: "10.7589/2019-04-088",
    pmid: null,
    pmcid: null,
    pmcUrl: null,
    type: "article",
    topics: ["avian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-7589-2019-04-088/10-7589-2019-04-088.pdf",
    externalUrl: null,
    preprintDoi: "10.1101/698985",
    isOpenAccess: false,
    license: null,
    licenseSource: "none-deposited",
    summary: "First report of reticuloendotheliosis virus in Brazil; 16.8 percent of ducks, turkeys and chickens tested were positive.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Reticuloendotheliosis viruses (REVs) are known to cause immunosuppressive and oncogenic disease that affects numerous avian species. Reticuloendotheliosis viruses are present worldwide and recently have been reported in South America with cases of infected commercial flocks in Argentina. We surveyed for the presence of REV in birds from a state in the northern region of Brazil using real-time PCR. We report here the presence of REV in Brazil, detected in Muscovy Ducks ( Cairina moschata ), Wild Turkeys ( Meleagris gallopavo ), and chickens ( Gallus gallus ) at a relatively high prevalence (16.8%). Phylogenetic analysis indicated a close relationship of these strains to variants in the US. This study provides evidence of REV in the Amazon biome and provides a baseline for future surveillance of the virus in the region and throughout Brazil.",
  },
  {
    id: "edwards-2019-finny",
    title: "Complete Genome Sequence of Bacteriophage Finny, Isolated from a Microbacterium foliorum Culture",
    authors: ["Tiffany Lee", "Michaela Aguirre", "Shey Andrews", "Kayla Bahr", "Abigail Ballard", "Matthew Bristerpostma", "Faith Cox", "Leah Dowell", "David Kiker", "Tiffany Lujan", "Stacy Luka", "Abbigal Ramirez", "Rheaven Sandoval", "Kenneth Underhill", "Haze Murphy", "Cecilia Cabrera", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2019,
    publishedDate: "2019-10-03",
    volume: "8",
    issue: "40",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/mra.01039-19",
    pmid: "31582442",
    pmcid: "PMC6776782",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6776782/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-01039-19/10-1128-mra-01039-19.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of phage Finny, isolated from New Braunfels soil; 40,313 bp, 63 genes.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"MK894432"},{"kind":"sra","id":"SRX6700907"}],
    selected: false,
    abstract: "Actinobacteriophage Finny contains a circularly permuted 40,313-bp double-stranded DNA genome with 63 predicted protein-coding genes. Finny was directly isolated from a soil sample collected in New Braunfels, Texas, that was incubated with Microbacterium foliorum SEA B-24224. Finny is closely related to bacteriophages MCubed, Andromedas, ColaCorta, Eleri, and Sansa.",
  },
  {
    id: "edwards-2019-ryadel",
    title: "Complete Genome Sequence of Cluster O Mycobacterium smegmatis Bacteriophage Ryadel",
    authors: ["Travis Miller", "Danielle Bachhofer", "Ashleigh Cooper", "Jessica Doty", "Josh Katuri", "Jonathan Musgrave", "Aleksey Palumbo", "Heidi Spann", "Amanda Stone", "Keith Emmert", "Julie Edwards", "Jesse Meik", "James Pierce", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2019,
    publishedDate: "2019-03-28",
    volume: "8",
    issue: "13",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/mra.01594-18",
    pmid: "30923246",
    pmcid: "PMC6439249",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6439249/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-01594-18/10-1128-mra-01594-18.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of phage Ryadel, a cluster O phage with an elongated head; 72,658 bp, 132 genes.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"MH590592"},{"kind":"sra","id":"SRX4721442"}],
    selected: false,
    abstract: "Mycobacteriophage Ryadel is a newly isolated cluster O Siphoviridae bacteriophage, characterized by an unusual prolate capsid, containing a 72,658-base-pair double-stranded DNA genome with 132 predicted protein-coding genes. Conserved among cluster O bacteriophages, the Ryadel genome contains 31 copies of a unique 17-bp sequence with dyad symmetry.",
  },
  {
    id: "edwards-2019-texas-survey",
    title: "Survey of Reticuloendotheliosis Virus in Wild Turkeys (Meleagris gallopavo) in Texas, USA",
    authors: ["Brittany Stewart", "Camille Trautman", "Faith Cox", "Heidi Spann", "Jason Hardin", "Robert Dittmar", "Dustin Edwards"],
    journal: "Journal of Wildlife Diseases",
    year: 2019,
    publishedDate: "2019-07-09",
    volume: "55",
    issue: "3",
    pages: "689",
    firstPage: "689",
    lastPage: null,
    doi: "10.7589/2018-08-187",
    pmid: null,
    pmcid: null,
    pmcUrl: null,
    type: "article",
    topics: ["avian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-7589-2018-08-187/10-7589-2018-08-187.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: false,
    license: null,
    licenseSource: "none-deposited",
    summary: "Survey of 393 wild turkeys in Texas for reticuloendotheliosis virus after an outbreak at Fossil Rim; 5 percent positive in affected counties.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Reticuloendotheliosis virus (REV) is an immunosuppressive and sometimes oncogenic avian retrovirus that establishes lifelong infection in a wide range of avian species. REV-infected wild birds roaming near at-risk captive flocks, such as is the case for the highly endangered Attwater's Prairie Chicken (APC; Tympanuchus cupido attwateri ), could act as a reservoir for viral transmission. In wild birds, prevalence rates of REV are low and appearance of associated disease is uncommon. During 2016-17, nearly half of all captive adult APC mortality at Fossil Rim Wildlife Center captive breeding facility in Glen Rose, Texas, US was attributed to REV infection. The unusually high REV prevalence rate prompted us to survey for this virus in wild galliforms throughout the region. From 2016-17, 393 blood samples collected from two subspecies of Wild Turkeys ( Meleagris gallopavo ) were tested for REV proviral DNA through amplification of the viral 3' long terminal repeat and segments of the viral pol gene. In REV-affected counties, 5% (5/98) of native Rio Grande Wild Turkeys ( Meleagris gallopavo intermedia ) were identified as REV-positive. In addition, we detected REV in one of 62 Eastern Wild Turkeys ( Meleagris gallopavo silvestris ) that had been imported during conservation efforts. To better determine protective measures, continued surveillance, including collection and genetic analysis of REV-infected samples, is necessary to identify sources of REV outbreaks in captive APC flocks.",
  },
  {
    id: "edwards-2018-arlo",
    title: "Complete Genome Sequence of Cluster A1 Mycobacterium smegmatis Bacteriophage Arlo",
    authors: ["Brittany Stewart", "Megan Adams", "Miranda Fuentes", "Leeila Hanson", "Esperanza Sandoval", "Mario Tovar", "Camille Trautman", "Bianca Willis", "Keith Emmert", "Julie Edwards", "Jesse Meik", "James Pierce", "Dustin Edwards"],
    journal: "Microbiology Resource Announcements",
    year: 2018,
    publishedDate: "2018-10-25",
    volume: "7",
    issue: "16",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1128/mra.01242-18",
    pmid: "30533744",
    pmcid: "PMC6256580",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6256580/",
    type: "article",
    topics: ["bacteriophages"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-mra-01242-18/10-1128-mra-01242-18.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Genome of phage Arlo, isolated from Bluff Dale soil; 52,960 bp, 96 genes, cluster A1.",
    updateNotice: null,
    accessions: [{"kind":"genbank","id":"MH576971"},{"kind":"sra","id":"SRX4721440"}],
    selected: false,
    abstract: "Mycobacteriophage Arlo is a newly isolated Siphoviridae bacteriophage isolated from soil samples collected in Bluff Dale, Texas. Mycobacteriophage Arlo has a 52,960 base-pair double-stranded DNA genome that is predicted to contain 96 protein-coding genes.",
  },
  {
    id: "edwards-2015-simian-lymphotropic",
    title: "Discovery and Characterization of Auxiliary Proteins Encoded by Type 3 Simian T-Cell Lymphotropic Viruses",
    authors: ["Jocelyn Turpin", "Chloé Journo", "Nga Ling Ko", "Flore Sinet", "Alexandre Carpentier", "Amandine Galioot", "Dustin Edwards", "Anne-Mieke Vandamme", "Louis Gazzolo", "Madeleine Duc Dodon", "Antoine Gessain", "Fatah Kashanchi", "Ivan Balansard", "Romain Lacoste", "Renaud Mahieux"],
    journal: "Journal of Virology",
    year: 2015,
    publishedDate: "2015-01-15",
    volume: "89",
    issue: "2",
    pages: "931-951",
    firstPage: "931",
    lastPage: "951",
    doi: "10.1128/jvi.02150-14",
    pmid: "25355890",
    pmcid: "PMC4300634",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4300634/",
    type: "article",
    topics: ["human-simian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-jvi-02150-14/10-1128-jvi-02150-14.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: null,
    licenseSource: "crossref:tdm-only",
    summary: "Three new accessory proteins found in simian T-cell lymphotropic virus type 3 and where each goes in the cell.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Human T-cell lymphotropic virus type 1 (HTLV-1) and HTLV-2 encode auxiliary proteins that play important roles in viral replication, viral latency, and immune escape. The presence of auxiliary protein-encoding open reading frames (ORFs) in HTLV-3, the latest HTLV to be discovered, is unknown. Simian T-cell lymphotropic virus type 3 (STLV-3) is almost identical to HTLV-3. Given the lack of HTLV-3-infected cell lines, we took advantage of STLV-3-infected cells and of an STLV-3 molecular clone to search for the presence of auxiliary transcripts. Using reverse transcriptase PCR (RT-PCR), we first uncovered the presence of three unknown viral mRNAs encoding putative proteins of 5, 8, and 9 kDa and confirmed the presence of the previously reported RorfII transcript. The existence of these viral mRNAs was confirmed by using splice site-specific RT-PCR with ex vivo samples. We showed that p5 is distributed throughout the cell and does not colocalize with a specific organelle. The p9 localization is similar to that of HTLV-1 p12 and induced a strong decrease in the calreticulin signal, similarly to HTLV-1 p12. Although p8, RorfII, and Rex-3 share an N-terminal sequence that is predicted to contain a nucleolar localization signal (NoLS), only p8 is found in the nucleolus. The p8 location in the nucleolus is linked to a bipartite NoLS. p8 and, to a lesser extent, p9 repressed viral expression but did not alter Rex-3-dependent mRNA export. Using a transformation assay, we finally showed that none of the STLV-3 auxiliary proteins had the ability to induce colony formation, while both Tax-3 and antisense protein of HTLV-3 (APH-3) promoted cellular transformation. Altogether, these results complete the characterization of the newly described primate T-lymphotropic virus type 3 (PTLV-3). IMPORTANCE Together with their simian counterparts, HTLVs form the primate T-lymphotropic viruses. HTLVs arose from interspecies transmission between nonhuman primates and humans. HTLV-1 and HTLV-2 encode auxiliary proteins that play important roles in viral replication, viral latency, and immune escape. The presence of ORFs encoding auxiliary proteins in HTLV-3 or STLV-3 genomes was unknown. Using in silico analyses, ex vivo samples, or in vitro experiments, we have uncovered the presence of 3 previously unknown viral mRNAs encoding putative proteins and confirmed the presence of a previously reported viral transcript. We characterized the intracellular localization of the four proteins. We showed that two of these proteins repress viral expression but that none of them have the ability to induce colony formation. However, both Tax and the antisense protein APH-3 promote cell transformation. Our results allowed us to characterize 4 new retroviral proteins for the first time.",
  },
  {
    id: "edwards-2014-both-orf-i",
    title: "Both orf-I isoforms, p12 and p8, are required for efficient HTLV-1 infection and persistence",
    authors: ["Cynthia Pise-Masison", "Maria Fernanda de Castro-Amarante", "Cody Buchmann", "Yoshimi Enoso-Akahata", "Claudio Fenezia", "Dustin Edwards", "Luiz Carlos Junior Alcantara", "Izabela Bialuk", "Steven Jacobson", "Bernardo Galvao-Castro", "Antoine Gessain", "Genoveffa Franchini"],
    journal: "Retrovirology",
    year: 2014,
    publishedDate: "2014-01",
    volume: "11",
    issue: "S1",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1186/1742-4690-11-s1-o13",
    pmid: null,
    pmcid: "PMC4044360",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4044360/",
    type: "abstract",
    topics: ["human-simian-retroviruses"],
    access: "external",
    pdfPath: null,
    externalUrl: "https://doi.org/10.1186/1742-4690-11-s1-o13",
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Conference talk: HTLV-1 needs both p12 and p8 to infect and persist.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: null,
  },
  {
    id: "edwards-2014-codependence",
    title: "Co-dependence of HTLV-1 p12 and p8 Functions in Virus Persistence",
    authors: ["Cynthia A. Pise-Masison", "Maria Fernanda de Castro-Amarante", "Yoshimi Enose-Akahata", "R. Cody Buchmann", "Claudio Fenizia", "Robyn Washington Parks", "Dustin Edwards", "Martina Fiocchi", "Luiz Carlos Alcantara", "Izabela Bialuk", "Jhanelle Graham", "Jean-Claude Walser", "Katherine McKinnon", "Bernardo Galvão-Castro", "Antoine Gessain", "David Venzon", "Steven Jacobson", "Genoveffa Franchini"],
    journal: "PLoS Pathogens",
    year: 2014,
    publishedDate: "2014-11-06",
    volume: "10",
    issue: "11",
    pages: "e1004454",
    firstPage: null,
    lastPage: null,
    doi: "10.1371/journal.ppat.1004454",
    pmid: "25375128",
    pmcid: "PMC4223054",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4223054/",
    type: "article",
    topics: ["human-simian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-1371-journal-ppat-1004454/10-1371-journal-ppat-1004454.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "public-domain",
    licenseSource: "unpaywall:best_oa_location",
    summary: "HTLV-1 established infection in macaques only when it made both p12 and p8; making mostly one or the other failed.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "HTLV-1 orf-I is linked to immune evasion, viral replication and persistence. Examining the orf-I sequence of 160 HTLV-1-infected individuals; we found polymorphism of orf-I that alters the relative amounts of p12 and its cleavage product p8. Three groups were identified on the basis of p12 and p8 expression: predominantly p12, predominantly p8 and balanced expression of p12 and p8. We found a significant association between balanced expression of p12 and p8 with high viral DNA loads, a correlate of disease development. To determine the individual roles of p12 and p8 in viral persistence, we constructed infectious molecular clones expressing p12 and p8 (D26), predominantly p12 (G29S) or predominantly p8 (N26). As we previously showed, cells expressing N26 had a higher level of virus transmission in vitro. However, when inoculated into Rhesus macaques, cells producing N26 virus caused only a partial seroconversion in 3 of 4 animals and only 1 of those animals was HTLV-1 DNA positive by PCR. None of the animals exposed to G29S virus seroconverted or had detectable viral DNA. In contrast, 3 of 4 animals exposed to D26 virus seroconverted and were HTLV-1 positive by PCR. In vitro studies in THP-1 cells suggested that expression of p8 was sufficient for productive infection of monocytes. Since orf-I plays a role in T-cell activation and recognition; we compared the CTL response elicited by CD4+ T-cells infected with the different HTLV-1 clones. Although supernatant p19 levels and viral DNA loads for all four infected lines were similar, a significant difference in Tax-specific HLA.A2-restricted killing was observed. Cells infected with Orf-I-knockout virus (12KO), G29S or N26 were killed by CTLs, whereas cells infected with D26 virus were resistant to CTL killing. These results indicate that efficient viral persistence and spread require the combined functions of p12 and p8.",
  },
  {
    id: "edwards-2014-p30-tlr3",
    title: "Human T-Cell Leukemia/Lymphoma Virus Type 1 p30, but Not p12/p8, Counteracts Toll-Like Receptor 3 (TLR3) and TLR4 Signaling in Human Monocytes and Dendritic Cells",
    authors: ["Claudio Fenizia", "Martina Fiocchi", "Kathryn Jones", "Robyn Washington Parks", "Michele Ceribelli", "Sebastien A. Chevalier", "Dustin Edwards", "Francis Ruscetti", "Cynthia A. Pise-Masison", "Genoveffa Franchini"],
    journal: "Journal of Virology",
    year: 2014,
    publishedDate: "2014-01",
    volume: "88",
    issue: "1",
    pages: "393-402",
    firstPage: "393",
    lastPage: "402",
    doi: "10.1128/jvi.01788-13",
    pmid: "24155397",
    pmcid: "PMC3911690",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3911690/",
    type: "article",
    topics: ["human-simian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-jvi-01788-13/10-1128-jvi-01788-13.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: null,
    licenseSource: "crossref:tdm-only",
    summary: "HTLV-1 p30 suppresses the interferon response in monocytes and dendritic cells; p12 and p8 do not.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "The human T-cell leukemia/lymphoma virus type 1 (HTLV-1) p30 protein, essential for virus infectivity in vivo, is required for efficient infection of human dendritic cells (DCs) but not B and T cells in vitro. We used a human monocytic cell line, THP-1, and dendritic cells to study the mechanism of p30 and p12/p8 requirements in these cell types. p30 inhibited the expression of interferon (IFN)-responsive genes (ISG) following stimulation by lipopolysaccharide (LPS) of Toll-like receptor 4 (TLR4) and by poly(I·C) of TLR3 but not of TLR7/8 with imiquimod. Results with THP-1 mirrored those for ex vivo human primary monocytes and monocyte-derived dendritic cells (Mo-mDC). The effect of p30 on TLR signaling was also demonstrated by ablating its expression within a molecular clone of HTLV-1. HTLV-1 infection of monocytes inhibited TLR3- and TLR4-induced ISG expression by 50 to 90% depending on the genes, whereas the isogenic clone p30 knockout virus was less effective at inhibiting TLR3 and TRL4 signaling and displayed lower infectivity. Viral expression and inhibition of ISG transcription was, however, rescued by restoration of p30 expression. A chromatin immunoprecipitation assay demonstrated that p30 inhibits initiation and elongation of PU.1-dependent transcription of IFN-α1, IFN-β, and TLR4 genes upon TLR stimulation. In contrast, experiments conducted with p12/p8 did not demonstrate an effect on ISG expression. These results provide a mechanistic explanation of the requirement of p30 for HTLV-1 infectivity in vivo, suggest that dampening interferon responses in monocytes and DCs is specific for p30, and represent an essential early step for permissive HTLV-1 infection and persistence.",
  },
  {
    id: "edwards-2014-palmitoylation",
    title: "Palmitoylation and p8-Mediated Human T-Cell Leukemia Virus Type 1 Transmission",
    authors: ["Dustin Edwards", "Risaku Fukumoto", "Maria Fernanda de Castro-Amarante", "Luiz Carlos Junior Alcantara", "Bernardo Galvão-Castro", "Robyn Washington Parks", "Cynthia Pise-Masison", "Genoveffa Franchini"],
    journal: "Journal of Virology",
    year: 2014,
    publishedDate: "2014-02-15",
    volume: "88",
    issue: "4",
    pages: "2319-2322",
    firstPage: "2319",
    lastPage: "2322",
    doi: "10.1128/jvi.03444-13",
    pmid: "24284316",
    pmcid: "PMC3911539",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3911539/",
    type: "article",
    topics: ["human-simian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-jvi-03444-13/10-1128-jvi-03444-13.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: null,
    licenseSource: "crossref:tdm-only",
    summary: "Mutating cysteine 39 stops HTLV-1 p8 and p12 from dimerizing and being palmitoylated, but p8 still reaches the cell surface and spreads the virus.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "The orf-I gene of human T-cell leukemia type 1 (HTLV-1) encodes p8 and p12 and has a conserved cysteine at position 39. p8 and p12 form disulfide-linked dimers, and only the monomeric forms of p8 and p12 are palmitoylated. Mutation of cysteine 39 to alanine (C39A) abrogated dimerization and palmitoylation of both proteins. However, the ability of p8 to localize to the cell surface and to increase cell adhesion and viral transmission was not affected by the C39A mutation.",
  },
  {
    id: "edwards-2014-role-of-regulatory",
    title: "Role of regulatory proteins in HIV-1/HTLV-1 coinfection",
    authors: ["Dustin Edwards", "Klaus Strebel", "Robyn Washington Parks", "Cynthia Pise-Masison", "Claudio Fenizia", "Martina Fiocchi", "Genoveffa Franchini"],
    journal: "Retrovirology",
    year: 2014,
    publishedDate: "2014-01",
    volume: "11",
    issue: "S1",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1186/1742-4690-11-s1-p122",
    pmid: null,
    pmcid: "PMC4043673",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4043673/",
    type: "abstract",
    topics: ["human-simian-retroviruses"],
    access: "external",
    pdfPath: null,
    externalUrl: "https://doi.org/10.1186/1742-4690-11-s1-p122",
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Conference poster on how HIV-1 and HTLV-1 regulatory proteins interact in coinfection.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: null,
  },
  {
    id: "edwards-2012-epidemiology-database",
    title: "A Public HTLV-1 Molecular Epidemiology Database for Sequence Management and Data Mining",
    authors: ["Thessika Hialla Almeida Araujo", "Leandro Inacio Souza-Brito", "Pieter Libin", "Koen Deforche", "Dustin Edwards", "Antonio Eduardo de Albuquerque-Junior", "Anne-Mieke Vandamme", "Bernardo Galvao-Castro", "Luiz Carlos Junior Alcantara"],
    journal: "PLoS ONE",
    year: 2012,
    publishedDate: "2012-09-10",
    volume: "7",
    issue: "9",
    pages: "e42123",
    firstPage: null,
    lastPage: null,
    doi: "10.1371/journal.pone.0042123",
    pmid: "22970114",
    pmcid: "PMC3438164",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3438164/",
    type: "article",
    topics: ["human-simian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-1371-journal-pone-0042123/10-1371-journal-pone-0042123.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "A public online database of 2,457 HTLV-1 sequences.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Background: It is estimated that 15 to 20 million people are infected with the human T-cell lymphotropic virus type 1 (HTLV-1). At present, there are more than 2,000 unique HTLV-1 isolate sequences published. A central database to aggregate sequence information from a range of epidemiological aspects including HTLV-1 infections, pathogenesis, origins, and evolutionary dynamics would be useful to scientists and physicians worldwide. Described here, we have developed a database that collects and annotates sequence data and can be accessed through a user-friendly search interface. The HTLV-1 Molecular Epidemiology Database website is available at http://htlv1db.bahia.fiocruz.br/. Methodology/principal findings: All data was obtained from publications available at GenBank or through contact with the authors. The database was developed using Apache Webserver 2.1.6 and SGBD MySQL. The webpage interfaces were developed in HTML and sever-side scripting written in PHP. The HTLV-1 Molecular Epidemiology Database is hosted on the Gonçalo Moniz/FIOCRUZ Research Center server. There are currently 2,457 registered sequences with 2,024 (82.37%) of those sequences representing unique isolates. Of these sequences, 803 (39.67%) contain information about clinical status (TSP/HAM, 17.19%; ATL, 7.41%; asymptomatic, 12.89%; other diseases, 2.17%; and no information, 60.32%). Further, 7.26% of sequences contain information on patient gender while 5.23% of sequences provide the age of the patient. Conclusions/significance: The HTLV-1 Molecular Epidemiology Database retrieves and stores annotated HTLV-1 proviral sequences from clinical, epidemiological, and geographical studies. The collected sequences and related information are now accessible on a publically available and user-friendly website. This open-access database will support clinical research and vaccine development related to viral genotype.",
  },
  {
    id: "edwards-2011-geranylgeranyl",
    title: "Inhibition of Geranylgeranyl Transferase-I Decreases Cell Viability of HTLV-1-Transformed Cells",
    authors: ["Dustin C. Edwards", "Katherine M. McKinnon", "Claudio Fenizia", "Kyung-Jin Jung", "John N. Brady", "Cynthia A. Pise-Masison"],
    journal: "Viruses",
    year: 2011,
    publishedDate: "2011-10-10",
    volume: "3",
    issue: "10",
    pages: "1815-1835",
    firstPage: "1815",
    lastPage: "1835",
    doi: "10.3390/v3101815",
    pmid: "22069517",
    pmcid: "PMC3205383",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3205383/",
    type: "article",
    topics: ["human-simian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-3390-v3101815/10-3390-v3101815.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "A geranylgeranyl transferase inhibitor reduces viability of HTLV-1-transformed cells and lowers Tax.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Human T-cell leukemia virus type-1 (HTLV-1) is the etiological agent of adult T-cell leukemia (ATL), an aggressive and highly chemoresistant malignancy. Rho family GTPases regulate multiple signaling pathways in tumorigenesis: cytoskeletal organization, transcription, cell cycle progression, and cell proliferation. Geranylgeranylation of Rho family GTPases is essential for cell membrane localization and activation of these proteins. It is currently unknown whether HTLV-1-transformed cells are preferentially sensitive to geranylgeranylation inhibitors, such as GGTI-298. In this report, we demonstrate that GGTI-298 decreased cell viability and induced G2/M phase accumulation of HTLV-1-transformed cells, independent of p53 reactivation. HTLV-1-LTR transcriptional activity was inhibited and Tax protein levels decreased following treatment with GGTI-298. Furthermore, GGTI-298 decreased activation of NF-κB, a downstream target of Rho family GTPases. These studies suggest that protein geranylgeranylation contributes to dysregulation of cell survival pathways in HTLV-1-transformed cells.",
  },
  {
    id: "edwards-2011-orf-encoded",
    title: "Orf-I and Orf-II-Encoded Proteins in HTLV-1 Infection and Persistence",
    authors: ["Dustin Edwards", "Claudio Fenizia", "Heather Gold", "Maria Fernanda de Castro-Amarante", "Cody Buchmann", "Cynthia A. Pise-Masison", "Genoveffa Franchini"],
    journal: "Viruses",
    year: 2011,
    publishedDate: "2011-06-17",
    volume: "3",
    issue: "6",
    pages: "861-885",
    firstPage: "861",
    lastPage: "885",
    doi: "10.3390/v3060861",
    pmid: "21994758",
    pmcid: "PMC3185781",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3185781/",
    type: "article",
    topics: ["human-simian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-3390-v3060861/10-3390-v3060861.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Review of the HTLV-1 orf-I and orf-II proteins p12, p8, p13 and p30.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "The 3' end of the human T-cell leukemia/lymphoma virus type-1 (HTLV-1) genome contains four overlapping open reading frames (ORF) that encode regulatory proteins. Here, we review current knowledge of HTLV-1 orf-I and orf-II protein products. Singly spliced mRNA from orf-I encodes p12, which can be proteolytically cleaved to generate p8, while differential splicing of mRNA from orf-II results in production of p13 and p30. These proteins have been demonstrated to modulate transcription, apoptosis, host cell activation and proliferation, virus infectivity and transmission, and host immune responses. Though these proteins are not essential for virus replication in vitro, p8, p12, p13, and p30 have an important role in the establishment and maintenance of HTLV-1 infection in vivo.",
  },
  {
    id: "edwards-2011-role-of-dimerization",
    title: "Role of dimerization and palmitoylation on the function of HTLV-1 p12 and p8",
    authors: ["Dustin Edwards", "Risaku Fukumoto", "Nancy Van Prooyen", "Heather Gold", "Maria F de Castro-Amarante", "Luiz Alcantara", "Genoveffa Franchini"],
    journal: "Retrovirology",
    year: 2011,
    publishedDate: "2011-12",
    volume: "8",
    issue: "S1",
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1186/1742-4690-8-s1-a124",
    pmid: null,
    pmcid: "PMC3112592",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3112592/",
    type: "abstract",
    topics: ["human-simian-retroviruses"],
    access: "external",
    pdfPath: null,
    externalUrl: "https://doi.org/10.1186/1742-4690-8-s1-a124",
    preprintDoi: null,
    isOpenAccess: true,
    license: "cc-by",
    licenseSource: "unpaywall:best_oa_location",
    summary: "Conference abstract on dimerization and palmitoylation of HTLV-1 p12 and p8.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: null,
  },
  {
    id: "edwards-2008-tax-repression",
    title: "Human T-Cell Leukemia Virus Type 1 Tax Relieves Repression of Proliferating Cell Nuclear Antigen Gene Expression",
    authors: ["Dustin C. Edwards", "Susan J. Marriott"],
    journal: "Journal of Virology",
    year: 2008,
    publishedDate: "2008-12",
    volume: "82",
    issue: "23",
    pages: "11714-11722",
    firstPage: "11714",
    lastPage: "11722",
    doi: "10.1128/jvi.00356-08",
    pmid: "18799587",
    pmcid: "PMC2583679",
    pmcUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2583679/",
    type: "article",
    topics: ["human-simian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-1128-jvi-00356-08/10-1128-jvi-00356-08.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: true,
    license: null,
    licenseSource: "crossref:tdm-only",
    summary: "HTLV-1 Tax relieves a repressor on the PCNA promoter, raising PCNA expression.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "Human T-cell leukemia virus type 1 (HTLV-1) is the etiological agent of adult T-cell leukemia. The transforming ability of Tax, the viral oncoprotein, is believed to depend on interactions with cell cycle regulators and on transactivation of genes that control cellular proliferation, including proliferating cell nuclear antigen (PCNA), a cofactor associated with DNA replication and repair. Tax associates with cellular transcription factors to alter their affinity for cognate DNA elements, leading to increased or decreased transcription from that promoter. Although it has been demonstrated that Tax transactivates the PCNA promoter, the mechanism of transcriptional activation is unknown. Here we report a cellular complex that binds specifically to a novel site within the minimal Tax-responsive element of the TATAA-less PCNA promoter. Mutation at this binding site or Tax expression inhibited complex formation and increased promoter activity, suggesting that the complex is a transcriptional repressor. The activation of PCNA gene expression by Tax and consequential decrease in nucleotide excision repair mediated by PCNA overexpression could contribute to the reduced DNA repair capacity and genomic instability observed in HTLV-1-infected cells.",
  },
  {
    id: "edwards-2007-rna-tumour",
    title: "RNA Tumour Viruses",
    authors: ["Dustin C. Edwards", "Susan J. Marriott"],
    journal: "The Cancer Handbook",
    year: 2007,
    publishedDate: "2007-10-15",
    volume: null,
    issue: null,
    pages: null,
    firstPage: null,
    lastPage: null,
    doi: "10.1002/9780470025079.chap06.pub2",
    pmid: null,
    pmcid: null,
    pmcUrl: null,
    type: "chapter",
    topics: ["human-simian-retroviruses"],
    access: "self-hosted",
    pdfPath: "/publications/10-1002-9780470025079-chap06-pub2/10-1002-9780470025079-chap06-pub2.pdf",
    externalUrl: null,
    preprintDoi: null,
    isOpenAccess: false,
    license: null,
    licenseSource: "crossref:tdm-only",
    summary: "Textbook chapter on RNA tumour viruses, focused on HTLV-1 Tax.",
    updateNotice: null,
    accessions: [],
    selected: false,
    abstract: "It is estimated that 15% of all cancer cases are aetiologically linked to viral infection. In these cancers, genomic instability and subsequent multi‐step tumourigenesis is associated with the expression of viral oncoproteins. Human T‐cell leukaemia virus type‐I (HTLV‐I), a prototypic representative of the RNA tumour viruses, is linked to the development of adult T‐cell leukaemia. The HTLV‐I oncoprotein, Tax, targets the regulators of cell cycle progression and DNA repair, leading to cellular transformation.",
  },
];
