// Reads the CV's profile and appointments, derives the owner's identity (app/lib/identity.mjs) and writes
// app/lib/identity.generated.mjs, which app/lib/seo.ts, the CV and the page compile import. build:content calls
// it, and so does the install step, so a clone that has not built yet still has the file the app imports.

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import matter from "gray-matter";

import { deriveIdentity } from "../../app/lib/identity.mjs";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const CV_DIR = path.join(ROOT, "content", "cv");
export const IDENTITY_PATH = path.join(ROOT, "app", "lib", "identity.generated.mjs");

/** The identity the CV files state now. Throws with every problem when the CV cannot give a role. */
export function readIdentity() {
  const files = readdirSync(CV_DIR).filter((name) => name.endsWith(".md"));
  /** @type {Array<Record<string, any>>} */
  const entries = [];
  /** @type {Record<string, any> | undefined} */
  let person;
  for (const name of files) {
    const data = matter(readFileSync(path.join(CV_DIR, name), "utf8"), {}).data;
    if (name === "profile.md") person = data.person;
    if (data.type === "appointment" && Array.isArray(data.entries)) entries.push(...data.entries.map((e) => ({ ...e, type: "appointment" })));
  }
  if (!person) throw new Error("content/cv/profile.md has no person");
  const result = deriveIdentity(/** @type {any} */ (person), entries);
  if (!result.ok) throw new Error(`the CV cannot give the site an identity:\n  ${result.errors.join("\n  ")}`);
  return result.identity;
}

/** The generated module's text for an identity. */
export function identityModule(/** @type {ReturnType<typeof readIdentity>} */ identity) {
  return (
    "// Generated by scripts/build-identity.mjs from content/cv/profile.md and appointments.md. Do not edit:\n" +
    "// change the CV, and build:content (or the next install) writes this again. See app/lib/identity.mjs.\n" +
    `export const IDENTITY = Object.freeze(${JSON.stringify(identity, null, 2)});\n`
  );
}

/** Writes the module, and only when it changed, so a build that changed nothing touches nothing. */
export function writeIdentity() {
  const identity = readIdentity();
  const text = identityModule(identity);
  let before = "";
  try {
    before = readFileSync(IDENTITY_PATH, "utf8");
  } catch {
    mkdirSync(path.dirname(IDENTITY_PATH), { recursive: true });
  }
  if (before !== text) writeFileSync(IDENTITY_PATH, text, "utf8");
  return { identity, changed: before !== text };
}
