// Reads data/references/*.fasta (GenBank records and slices of them, fetched once and kept as NCBI wrote them) and writes
// app/lib/registry/references.generated.mjs, which the registry's placement code imports (app/lib/registry/align.mjs). The
// FASTA files are the source; the module is derived from them, so the Worker carries the sequences with no second copy to keep.
// build:content calls it, and so does the install step, so a clone that has not built yet still has the file the app imports.

import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { parseReference } from "../../app/lib/registry/reference.mjs";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
export const REFERENCES_DIR = path.join(ROOT, "data", "references");
export const REFERENCES_PATH = path.join(ROOT, "app", "lib", "registry", "references.generated.mjs");

/** The file a reference id is kept in: the id with its colon spelled as an underscore, so it is a legal name everywhere. @param {string} id */
export function referenceFile(id) {
  return `${id.replace(":", "_")}.fasta`;
}

/**
 * Every reference in data/references, parsed. A file whose name is not its record's id is refused, so an id can only name one
 * file and a file cannot be read as another record.
 *
 * @returns {Record<string, import("../../app/lib/registry/reference.mjs").Reference>}
 */
export function readReferences() {
  /** @type {Record<string, import("../../app/lib/registry/reference.mjs").Reference>} */
  const out = {};
  for (const name of readdirSync(REFERENCES_DIR).filter((n) => n.endsWith(".fasta")).sort()) {
    const reference = parseReference(readFileSync(path.join(REFERENCES_DIR, name), "utf8"));
    if (referenceFile(reference.id) !== name) {
      throw new Error(`data/references/${name} holds ${reference.id}, so it must be named ${referenceFile(reference.id)}`);
    }
    out[reference.id] = reference;
  }
  return out;
}

/** The generated module's text. @param {ReturnType<typeof readReferences>} references */
export function referencesModule(references) {
  return (
    "// Generated by scripts/build-references.mjs from data/references/*.fasta. Do not edit: change the FASTA files, and\n" +
    "// build:content (or the next install) writes this again. See app/lib/registry/reference.mjs.\n" +
    `export const REFERENCES = Object.freeze(${JSON.stringify(references, null, 2)});\n`
  );
}

/** Writes the module, and only when it changed, so a build that changed nothing touches nothing. */
export function writeReferences() {
  const references = readReferences();
  const text = referencesModule(references);
  let before = "";
  try {
    before = readFileSync(REFERENCES_PATH, "utf8");
  } catch {
    mkdirSync(path.dirname(REFERENCES_PATH), { recursive: true });
  }
  if (before !== text) writeFileSync(REFERENCES_PATH, text, "utf8");
  return { references, changed: before !== text };
}
