import { PageShell } from "~/components/page-shell";
import { SITE, pageMeta, publicHtmlHeaders } from "~/lib/seo";

// prose.css is route-scoped: a page using `.prose` without importing it renders unstyled.
import "~/styles/prose.css";

/** Every sentence is derivable from the code, and no retention period is stated that the code does not own. */
export function headers() {
  // The shared builder: a hand-written pair drops the Vary line and serves one reader's theme to another.
  return new Headers(publicHtmlHeaders());
}

export function meta() {
  return pageMeta({
    title: `Privacy | ${SITE.name}`,
    description:
      "What this site records, what it does not, and where each of those facts lives in the code.",
    path: "/privacy",
  });
}

export default function Privacy() {
  return (
    <PageShell>
      <header className="page-head">
        <h1>Privacy</h1>
        <p className="muted">
          What this site records, what it does not, and where each of those facts lives in
          the code. Every statement here describes something the source does; nothing is
          aspirational.
        </p>
      </header>

      <div className="prose">
        <h2 id="page-views">Page views</h2>
        <p>
          This site keeps no visitor record of its own. Page views are counted by{" "}
          <strong>Cloudflare Web Analytics</strong>, which Cloudflare switches on for this
          domain and which adds one small script to each page as it is delivered. The script
          measures that the page was viewed and how fast it loaded, and reports back to this
          site&rsquo;s own address. Cloudflare says Web Analytics does not collect
          visitors&rsquo; personal data; the figures the site owner sees are totals by page, country and
          browser type, never a list of people.
        </p>
        <p>
          That script is the one thing on a page that this repository does not write: the
          site&rsquo;s security policy names that single file as the only outside script it
          allows, so nothing else from another company can run. Cloudflare also counts
          requests as they pass through its network, which is how it tells search crawlers
          and AI crawlers apart from readers.
        </p>
        <p>
          How long Cloudflare keeps those figures is Cloudflare&rsquo;s retention policy, not a
          setting in this repository. This page does not quote a number it does not control.
        </p>

        <h2 id="ask">Asking a question</h2>
        <p>
          The search page has an optional Ask feature. Using it sends your question to a
          language model running on Cloudflare&rsquo;s network, together with passages from
          this site that matched it. The answer is generated from those passages.
        </p>
        <p>
          Answers are cached for seven days, keyed by a hash of the question, so that the
          same question asked twice does not bill a second generation. The cache holds the
          question&rsquo;s hash, the answer, and which passages it drew on. It does not hold
          who asked.
        </p>
        <p>
          The feature is opt-in per question: classic search never reaches it, and a page
          that is not searched never sends anything anywhere.
        </p>

        <h2 id="security-reports">Security reports</h2>
        <p>
          This site sends a Content Security Policy, and browsers report violations of it to
          an endpoint here. Those reports are written to the Worker&rsquo;s log stream
          verbatim. A report is generated by your browser and describes the page and the
          resource that was blocked; it is a debugging signal about the site, not about you.
        </p>

        <h2 id="webmentions">Mentions from other sites</h2>
        <p>
          Another site can tell this one that it has linked to a post here. When that
          happens, this site fetches the page that was named and stores four things: the
          address of that page, which post it linked to, an author name read from the page
          if it publishes one, and a short excerpt of the text around the link. It does not
          store the IP address of whoever sent it. Nothing appears anywhere on the site
          until it has been approved by hand, and until then it is visible only to the
          administrator.
        </p>

        <h2 id="cookies">Cookies</h2>
        <p>
          There is one cookie for ordinary readers. It is called{" "}
          <code>theme</code>, it holds either <code>light</code> or <code>dark</code>, and it
          lasts a year. You only have it if you have used the theme button; until then the
          site simply follows your device and stores nothing. It exists so the site renders in
          the colors you chose on the first byte rather than flickering into them. Nothing
          else is stored on your device.
        </p>
        <p>
          There is a second cookie, a sign-in session, and it exists only for the one
          administrator of this site. If you have not signed in, you do not have it.
        </p>

        <h2 id="processors">Who else is involved</h2>
        <p>
          <strong>Cloudflare</strong> runs everything: the Worker that serves these pages,
          the database, the file storage, the page-view analytics described above, and the
          model that answers Ask questions. The one script a page runs that this site did not
          write is Cloudflare&rsquo;s analytics script, served from Cloudflare&rsquo;s own
          address; no other company&rsquo;s script runs on any page.
        </p>
        <p>
          <strong>The Germomics podcast host</strong> is reached only if you play the episode
          on the home page: playing it loads the audio from the podcast&rsquo;s host, by way of
          OP3, the download counter the show uses.
        </p>
        <p>
          <strong>Cloudflare Access</strong> signs in the administrators of this site. It is
          reached only from the admin address, and only by the people it is set up to let in.
        </p>

        <h2 id="checking">Checking any of this</h2>
        <p>
          The repository is the authority for every claim above, and{" "}
          <a href="/colophon">the colophon</a> describes how the site is built. If this page
          and the code ever disagree, the code is right and this page is a bug.
        </p>

        <h2 id="questions">Questions about privacy</h2>
        <p>
          Email <a href="mailto:privacy@dustinedwards.info">privacy@dustinedwards.info</a> about
          anything on this page, or to ask what the site holds that concerns you.
        </p>
      </div>
    </PageShell>
  );
}
