// Generated and committed because a Worker cannot read the resolved hex out of a stylesheet.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveToken, THEME_SELECTORS, tokenBlock } from "./lib/tokens.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_PATH = join(root, "content", "tokens.json");

/** A figure series slot is declared as a ramp step, and the swatch wants the color. */
const resolve = (/** @type {Record<string, string>} */ block, /** @type {string} */ name) =>
  resolveToken(block, name).value;

const light = tokenBlock("light", THEME_SELECTORS.light);
const dark = tokenBlock("dark", THEME_SELECTORS.dark);

/* The palette blocks are the ones declaring --paper. A theme block inserted
   above them would otherwise be read as the palette. */
for (const [label, block] of /** @type {Array<[string, Record<string, string>]>} */ ([
  ["light", light],
  ["dark", dark],
])) {
  if (!("--paper" in block)) throw new Error(`${label}: block does not declare --paper`);
}

const names = Object.keys(light);
const missing = names.filter((n) => !(n in dark));
if (missing.length > 0) {
  throw new Error(`dark does not declare: ${missing.join(", ")}`);
}

const tokens = names.map((name) => {
  const l = resolve(light, name);
  const d = resolve(dark, name);
  if (l === null || d === null) throw new Error(`${name} does not resolve in both themes`);
  return { name, light: l, dark: d };
});

const payload = {
  $comment:
    "Generated by scripts/build-tokens.mjs from app/app.css. app.css is the owner; " +
    "check:contrast holds this file against it. Edit the stylesheet, then re-run " +
    "npm run build:tokens.",
  tokens,
};

writeFileSync(OUT_PATH, `${JSON.stringify(payload, null, 2)}\n`);
console.log(`build:tokens wrote ${tokens.length} tokens to content/tokens.json`);
