// Importing the upstream sheet from a component would put it in a route stylesheet for every post,
// most with no math, and ship three font formats where every supported browser reads one.

import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { isMain } from "./lib/is-main.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const KATEX_DIR = join(root, "node_modules", "katex", "dist");
export const KATEX_CSS_PATH = join("app", "styles", "katex.generated.css");
export const KATEX_FONT_DIR = join("app", "fonts", "katex");
export const KATEX_OVERRIDES_PATH = join("app", "styles", "katex-overrides.css");

export const OVERRIDES_MARKER = "/* ---- site overrides ---- */\n";

export function installedKatexVersion() {
  const pkg = JSON.parse(
    readFileSync(join(root, "node_modules", "katex", "package.json"), "utf8"),
  );
  return String(pkg.version);
}

/**
 * Anchored on the format keyword, not the extension, which also appears inside the filename. A face
 * with no woff2 source is left alone: dropping every source would silently remove the face.
 *
 * @param {string} src the contents of one `src:` declaration
 * @returns {string | null} the trimmed list, or null when there is no woff2
 */
export function woff2Only(src) {
  const entries = src
    .split(/,(?![^(]*\))/)
    .map((e) => e.trim())
    .filter(Boolean);
  const kept = entries.filter((e) => /format\(\s*["']?woff2["']?\s*\)/.test(e));
  return kept.length > 0 ? kept.join(",") : null;
}

/**
 * @param {string} css the contents of katex.min.css
 * @returns {{ css: string, faces: string[], untrimmed: string[] }}
 */
export function trimStylesheet(css) {
  const faces = new Set();
  /** @type {string[]} */
  const untrimmed = [];

  const out = css.replace(/@font-face\s*\{([^}]*)\}/g, (block, body) => {
    const src = body.match(/src\s*:\s*([^;}]+)/);
    if (!src) return block;
    const trimmed = woff2Only(src[1]);
    if (trimmed === null) {
      untrimmed.push(body.match(/font-family\s*:\s*([^;]+)/)?.[1]?.trim() ?? body.slice(0, 40));
      return block;
    }
    return block.replace(src[1], trimmed);
  });

  // Runs over the whole stylesheet, so a woff2 url surviving outside an @font-face block is caught too.
  const rewritten = out.replace(/url\(\s*["']?fonts\/([^"')]+\.woff2)["']?\s*\)/g, (_m, file) => {
    faces.add(file);
    return `url("../fonts/katex/${file}")`;
  });

  return { css: rewritten, faces: [...faces].sort(), untrimmed };
}

/** Exported so `check:content` can derive it and byte-compare without shelling out to this script. */
export function generateKatexCss() {
  const version = installedKatexVersion();
  const source = readFileSync(join(KATEX_DIR, "katex.min.css"), "utf8");
  const { css, faces, untrimmed } = trimStylesheet(source);

  if (untrimmed.length > 0) {
    throw new Error(
      `katex ${version} declares ${untrimmed.length} @font-face block(s) with no woff2 ` +
        `source (${untrimmed.join(", ")}). Trimming them would drop the face entirely, so ` +
        `this stops rather than shipping math that renders in a fallback font.`,
    );
  }
  if (faces.length === 0) {
    throw new Error(
      `the trimmed stylesheet references no woff2 font at all, which cannot be right for ` +
        `katex ${version}. The url rewrite matched nothing, so its needle is wrong.`,
    );
  }

  const header =
    `/* GENERATED by scripts/build-katex.mjs from katex ${version}. Do not edit.\n` +
    ` *\n` +
    ` * The upstream katex.min.css with the woff and truetype sources removed and\n` +
    ` * the font urls repointed at app/fonts/katex/. Grounds, including why this is\n` +
    ` * derived, committed, and not under public/, are in that script. Regenerate\n` +
    ` * with \`npm run build:katex\`; check:content byte-compares it against a fresh\n` +
    ` * derivation, so a katex bump that nobody regenerated is a named failure.\n` +
    ` *\n` +
    ` * Everything below the site-overrides marker at the end of this file is\n` +
    ` * app/styles/katex-overrides.css, which is hand written and is where a site\n` +
    ` * rule goes. The marker is not quoted here: a CSS comment ends at the first\n` +
    ` * close sequence, so reproducing it inside this one terminated the header\n` +
    ` * early and lightningcss refused the whole stylesheet (measured 2026-09-06).\n` +
    ` */\n`;

  // Appended rather than a second link, so a math post costs one request.
  const overrides = readFileSync(join(root, KATEX_OVERRIDES_PATH), "utf8");

  return { css: `${header}${css}\n${OVERRIDES_MARKER}${overrides}`, faces, version };
}

/** @param {Buffer} buf */
const sha = (buf) => createHash("sha256").update(buf).digest("hex").slice(0, 12);

function main() {
  const { css, faces, version } = generateKatexCss();

  const fontDir = join(root, KATEX_FONT_DIR);
  // Replaced, not merged: a face removed upstream would otherwise stay on disk forever.
  rmSync(fontDir, { recursive: true, force: true });
  mkdirSync(fontDir, { recursive: true });

  let bytes = 0;
  for (const face of faces) {
    const buf = readFileSync(join(KATEX_DIR, "fonts", face));
    writeFileSync(join(fontDir, face), buf);
    bytes += buf.length;
  }

  writeFileSync(join(root, KATEX_CSS_PATH), css, "utf8");

  // Both directions: a one-directional copy is how a stale face survives a version bump.
  const onDisk = readdirSync(fontDir).sort();
  const orphans = onDisk.filter((f) => !faces.includes(f));
  if (orphans.length > 0) {
    throw new Error(`copied faces the stylesheet does not name: ${orphans.join(", ")}`);
  }

  console.log(
    `build:katex ok. katex ${version}: ${KATEX_CSS_PATH} ${Buffer.byteLength(css)} bytes ` +
      `(sha ${sha(Buffer.from(css))}), ${faces.length} woff2 face(s) ${bytes} bytes into ` +
      `${KATEX_FONT_DIR}/.`,
  );
}

if (isMain(import.meta.url)) {
  try {
    main();
  } catch (error) {
    console.error(
      `build:katex failed. ${error instanceof Error ? error.message : String(error)}`,
    );
    process.exit(1);
  }
}
