// Ruling 115, wave 3: workers/**/*.ts and app/**/*.ts, largest comment bytes first
// (re-measured at fda6ef1: 88 files, 853261 bytes,
// 495697 comment, 1017 blocks).
export const WAVE3 = [
  "workers/app.ts",
  "app/lib/search/ask.server.ts",
  "app/lib/editor/publish.server.ts",
  "app/lib/operator/api.server.ts",
  "app/lib/seo.ts",
  "workers/watchdog.ts",
  "app/lib/search/search.server.ts",
  "app/enhance/blog.ts",
  "app/routes/api.health.ts",
  "app/lib/search/ask-guard.server.ts",
  "app/db/schema.ts",
  "app/lib/editor/frontmatter.ts",
  "app/routes/media.$.ts",
  "app/enhance/theme.ts",
  "workers/media-events.ts",
  "app/routes/webmention.ts",
  "app/routes/search.ask.ts",
  "app/lib/media/core.server.ts",
  "app/enhance/palette.ts",
  "app/lib/health/checks.server.ts",
  "app/routes.ts",
  "app/lib/webmention/verify.server.ts",
  "app/env.d.ts",
  "app/lib/admin/traffic.server.ts",
  "app/lib/media/rebuild.server.ts",
  "app/lib/theme.ts",
  "app/lib/media/upload.server.ts",
  "app/routes/sitemap.ts",
  "app/lib/smoke.server.ts",
  "app/lib/preview-links.server.ts",
  "app/lib/editor/github.server.ts",
  "app/lib/media/backup.server.ts",
  "app/lib/cache-purge.server.ts",
  "app/lib/markdown-twin.ts",
  "app/routes/api.csp-report.ts",
  "app/lib/bearer.server.ts",
  "app/lib/citations.server.ts",
  "app/enhance/ask.ts",
  "app/lib/editor/action.server.ts",
  "app/lib/operator/auth.server.ts",
  "app/routes/admin.media.upload.ts",
  "workers/ask-budget.ts",
  "app/lib/webmention/decide.server.ts",
  "app/data/publications.ts",
  "app/lib/media/resolvers/posts.server.ts",
  "app/lib/admin/secrets.server.ts",
  "app/lib/auth.server.ts",
  "app/lib/timing.ts",
  "app/lib/admin/types.ts",
  "app/lib/blog-view.ts",
  "app/lib/editor/draft-buffer.ts",
  "app/lib/media/resolvers.server.ts",
  "app/routes/api.operator.ts",
  "app/lib/editor/divergence.server.ts",
  "app/lib/health/snapshot.server.ts",
  "app/lib/content/render-snippet.server.ts",
  "app/lib/editor/feedback.ts",
  "app/routes/theme.ts",
  "app/routes/blog.feed[.json].ts",
  "app/data/organisms.ts",
  "app/components/admin/disclosure.ts",
  "app/routes/admin.preview.ts",
  "app/lib/webmention/advertise.ts",
  "app/data/phage-hunters.ts",
  "app/lib/context.ts",
  "app/lib/nav.ts",
  "app/routes/publications[.json].ts",
  "app/lib/editor/link-targets.server.ts",
  "app/lib/auth-rate.server.ts",
  "app/routes/blog.rss[.xml].ts",
  "app/lib/client-ip.ts",
  "app/routes/llms-full[.txt].ts",
  "app/routes/robots.ts",
  "app/routes/llms.ts",
  "app/routes/publications[.bib].ts",
  "app/lib/content/wasm.server.ts",
  "app/routes/api.auth.$.ts",
  "app/routes/blog.series.$series.rss[.xml].ts",
  "app/routes/blog.$slug[.md].ts",
  "app/routes/blog.tags.$tag.rss[.xml].ts",
  "app/routes/blog.atom[.xml].ts",
  "app/routes/blog.tags.$tag.feed[.json].ts",
  "app/routes/blog.series.$series.feed[.json].ts",
  "app/routes/publications.$slug[.bib].ts",
  "app/routes/publications[.ris].ts",
  "app/db/auth-schema.ts",
  "app/routes/publications.$slug[.ris].ts",
  "app/lib/auth-client.ts",
];

// Chunks balanced by COMMENT BYTES, not by file count: a chunk's cost is what it holds to
// read and rewrite, and wave 2's count-balanced chunks ran from 27 to 181 blocks.
export const CHUNKS = {
  "1": [
    ["workers/app.ts",0,38],
  ],
  "2": [
    ["app/lib/search/ask.server.ts",0,52],
  ],
  "3": [
    ["app/lib/editor/publish.server.ts",0,49],
    ["app/lib/operator/api.server.ts",0,48],
  ],
  "4": [
    ["app/lib/seo.ts",0,38],
    ["workers/watchdog.ts",0,28],
  ],
  "5": [
    ["app/lib/search/search.server.ts",0,44],
    ["app/enhance/blog.ts",0,26],
    ["app/routes/api.health.ts",0,13],
  ],
  "6": [
    ["app/lib/search/ask-guard.server.ts",0,25],
    ["app/db/schema.ts",0,49],
    ["app/lib/editor/frontmatter.ts",0,24],
    ["app/routes/media.$.ts",0,12],
  ],
  "7": [
    ["app/enhance/theme.ts",0,17],
    ["workers/media-events.ts",0,11],
    ["app/routes/webmention.ts",0,19],
    ["app/routes/search.ask.ts",0,21],
    ["app/lib/media/core.server.ts",0,19],
  ],
  "8": [
    ["app/enhance/palette.ts",0,30],
    ["app/lib/health/checks.server.ts",0,11],
    ["app/routes.ts",0,28],
    ["app/lib/webmention/verify.server.ts",0,12],
    ["app/env.d.ts",0,9],
    ["app/lib/admin/traffic.server.ts",0,13],
    ["app/lib/media/rebuild.server.ts",0,16],
  ],
  "9": [
    ["app/lib/theme.ts",0,9],
    ["app/lib/media/upload.server.ts",0,11],
    ["app/routes/sitemap.ts",0,5],
    ["app/lib/smoke.server.ts",0,9],
    ["app/lib/preview-links.server.ts",0,19],
    ["app/lib/editor/github.server.ts",0,17],
    ["app/lib/media/backup.server.ts",0,12],
    ["app/lib/cache-purge.server.ts",0,6],
  ],
  "10": [
    ["app/lib/markdown-twin.ts",0,5],
    ["app/routes/api.csp-report.ts",0,7],
    ["app/lib/bearer.server.ts",0,3],
    ["app/lib/citations.server.ts",0,11],
    ["app/enhance/ask.ts",0,13],
    ["app/lib/editor/action.server.ts",0,10],
    ["app/lib/operator/auth.server.ts",0,7],
    ["app/routes/admin.media.upload.ts",0,7],
    ["workers/ask-budget.ts",0,9],
    ["app/lib/webmention/decide.server.ts",0,5],
    ["app/data/publications.ts",0,10],
    ["app/lib/media/resolvers/posts.server.ts",0,3],
  ],
  "11": [
    ["app/lib/admin/secrets.server.ts",0,4],
    ["app/lib/auth.server.ts",0,5],
    ["app/lib/timing.ts",0,6],
    ["app/lib/admin/types.ts",0,10],
    ["app/lib/blog-view.ts",0,8],
    ["app/lib/editor/draft-buffer.ts",0,10],
    ["app/lib/media/resolvers.server.ts",0,11],
    ["app/routes/api.operator.ts",0,3],
    ["app/lib/editor/divergence.server.ts",0,5],
    ["app/lib/health/snapshot.server.ts",0,3],
    ["app/lib/content/render-snippet.server.ts",0,1],
    ["app/lib/editor/feedback.ts",0,4],
    ["app/routes/theme.ts",0,3],
    ["app/routes/blog.feed[.json].ts",0,2],
    ["app/data/organisms.ts",0,3],
    ["app/components/admin/disclosure.ts",0,3],
    ["app/routes/admin.preview.ts",0,3],
    ["app/lib/webmention/advertise.ts",0,1],
    ["app/data/phage-hunters.ts",0,0],
    ["app/lib/context.ts",0,3],
    ["app/lib/nav.ts",0,1],
    ["app/routes/publications[.json].ts",0,1],
    ["app/lib/editor/link-targets.server.ts",0,1],
  ],
  "12": [
    ["app/lib/auth-rate.server.ts",0,1],
    ["app/routes/blog.rss[.xml].ts",0,1],
    ["app/lib/client-ip.ts",0,0],
    ["app/routes/llms-full[.txt].ts",0,1],
    ["app/routes/robots.ts",0,1],
    ["app/routes/llms.ts",0,2],
    ["app/routes/publications[.bib].ts",0,0],
    ["app/lib/content/wasm.server.ts",0,1],
    ["app/routes/api.auth.$.ts",0,0],
    ["app/routes/blog.series.$series.rss[.xml].ts",0,0],
    ["app/routes/blog.$slug[.md].ts",0,1],
    ["app/routes/blog.tags.$tag.rss[.xml].ts",0,0],
    ["app/routes/blog.atom[.xml].ts",0,0],
    ["app/routes/blog.tags.$tag.feed[.json].ts",0,0],
    ["app/routes/blog.series.$series.feed[.json].ts",0,0],
    ["app/routes/publications.$slug[.bib].ts",0,0],
    ["app/routes/publications[.ris].ts",0,0],
    ["app/db/auth-schema.ts",0,0],
    ["app/routes/publications.$slug[.ris].ts",0,0],
    ["app/lib/auth-client.ts",0,0],
  ],
};

/**
 * The share of comment bytes this wave aims to keep, raised for wave 3 by the seat.
 *
 * These are runtime files and they carry the prohibitions and the boundary statements: what a
 * path may never do, and what a check cannot see. Both classes stay whatever they cost, so the
 * rate follows the classes rather than the classes following the rate. Wave 4 is .tsx, carries
 * far fewer of either, and keeps the earlier target.
 */
export const KEEP_SHARE = 0.4;

/**
 * What this wave covers and where it was measured, for the history document's header.
 *
 * The header used to hardcode wave 2's sentence, so wave 3's document opened by saying it took
 * files "under scripts/" when it takes workers/ and app/. A per-wave fact belongs with the wave.
 */
export const BASE = "fda6ef1";
export const SCOPE = "the 88 files under workers/ and app/";
