// My blind tags. Index is positional into blocks.json from extract-blocks.mjs.
// Grok's TSV is NOT read until this file is complete.
//
// Structural classes are applied programmatically at the end (later exact
// copies, reset.css preflight one-liners, the repeated split header); the
// entries here are per-block judgements made by reading the prose.
export const DECISIONS = {
  // ---- public-chrome.css, page-shell.css, chrome-nav.css ----
  194: ["POINTER", "split header, canonical statement is app/app.css:1885"],
  195: ["KEEP", "why the chrome is brand; measured 1.4:1 seam"],
  196: ["KEEP", "measured 320/414/552 overflow; corrects a false recorded measurement"],
  197: ["KEEP", "why the admin topbar shares the inset declaration"],
  198: ["KEEP", "specificity (0,2,0) outranks bare :focus-visible (0,1,0)"],
  199: ["KEEP", "the wordmark prohibition, specificity and measured on-chrome pairs"],
  200: ["KEEP", "specificity (0,2,0) beats (0,1,0), login card untouched"],
  201: ["KEEP", "2rem inside 4rem min-height; 36x50 ratio"],
  202: ["POINTER", "split header, canonical statement is app/app.css:1885"],
  203: ["KEEP", "why diagnostic output is not .prose pre; overflow-x rule"],
  204: ["KEEP", "prose keeps its own measure, does not stretch"],
  205: ["KEEP", "why header and footer are one chrome"],
  206: ["KEEP", "why both insets must match"],
  207: ["KEEP", "specificity (0,1,0) repointed at (0,2,0)"],
  208: ["KEEP", "specificity (0,2,1) and (0,2,0) against base (0,1,1)"],
  209: ["KEEP", "WCAG 2.2 2.5.8 and the inline-link exception deliberately not taken"],
  210: ["CUT", "bare section label, no rule"],
  211: ["KEEP", "why the shell owns the viewport; double-scroll forbidden"],
  212: ["POINTER", "split header, canonical statement is app/app.css:1885"],
  213: ["KEEP", "why every class is defined here; Tailwind never sees D1 markup"],
  214: ["KEEP", "why --control-h lives here; check:contrast parses :root"],
  215: ["KEEP", "why wrapping is needed in both places"],
  216: ["KEEP", "v4 no-visited ruling, specificity (0,2,1) vs (0,1,1), proved"],
  217: ["KEEP", "why the box grew and the text did not move"],
  218: ["KEEP", "why chrome values are borrowed; no unmeasured pair enters"],
  219: ["CUT", "history: describes two rules that no longer exist"],
  220: ["KEEP", "the cascade mechanism for the theme toggle, no-script correctness"],

  // ---- skip-link.css, motion-print.css, search-trigger.css, shell.css ----
  221: ["KEEP", "shared height; falls back to auto where --control-h is out of scope"],
  222: ["KEEP", "WCAG 2.2 target size, 28px square above the 24px floor"],
  223: ["KEEP", "the default layer: no cookie, the machine decides"],
  224: ["KEEP", "the explicit layer outranks the media query"],
  225: ["POINTER", "split header, canonical statement is app/app.css:1885"],
  226: ["KEEP", "the progressive-enhancement floor for everything below"],
  227: ["KEEP", "why the skip link takes the inverted pair; collision checked"],
  228: ["KEEP", "measured ~1.1:1; specificity (0,1,1) wins on order"],
  229: ["KEEP", "reduced motion is instant, never absent"],
  230: ["CUT", "bare section label"],
  231: ["KEEP", "prohibition: must not become a theme token, with the reason"],
  232: ["KEEP", "why [data-enhanced] is carried; outranking"],
  233: ["KEEP", "why link targets are spelled out in print"],
  234: ["KEEP", "measured frame counts and timings; the opt-out prohibition"],
  235: ["POINTER", "split header, canonical statement is app/app.css:1885"],
  236: ["KEEP", "enhancement-only scope; no-script reader sees none of it"],
  237: ["KEEP", "ruling, rule 2 grounds, 24px floor, shared --control-h"],
  238: ["KEEP", "carries the imported-last cascade fact; the rest is history"],
  239: ["KEEP", ".tracks not .page, the track is the measure"],
  240: ["KEEP", "measured scrollWidth 340 against clientWidth 320"],
  241: ["KEEP", "single-direction flow spacing; specificity (0,1,2) vs (0,1,1)"],
  242: ["KEEP", "footer prohibitions: no fill, no logo repeat, no social row"],

  // ---- blog-index, blog-search, search-page, ask, palette-dialog ----
  268: ["KEEP", "tag chips are links so filtering works with no script"],
  269: ["KEEP", "24px minimum target, WCAG 2.2 AA"],
  270: ["KEEP", "token not opacity; check:contrast structurally cannot see opacity"],
  271: ["KEEP", "measured 39x23 and 33x23 against the 24px floor"],
  272: ["CUT", "bare section label"],
  297: ["POINTER", "split header, canonical statement is app/app.css:1885"],
  298: ["KEEP", "Layer 0 must work with scripting off"],
  299: ["KEEP", "measured 1216 from x=32 against 768 from x=256; records the mirror"],
  300: ["KEEP", "names the criterion the min-height exists for"],
  301: ["KEEP", "why gold not purple; rule 6 keeps purple off signalling"],
  302: ["CUT", "bare section label"],
  303: ["KEEP", "24px minimum target with its source"],
  304: ["KEEP", "why the generated answer carries a visible edge"],
  333: ["KEEP", "why the dialog sits high rather than centred"],
  334: ["KEEP", "ratified scrim; warns one role had two owners agreeing by luck"],
  335: ["KEEP", "2.4.7 prohibition; why :focus-visible rather than :focus"],
  336: ["CUT", "restates the declaration below it"],
  337: ["CUT", "bare section label"],

  // ---- prose.css ----
  243: ["CUT", "bare section separator"],
  244: ["KEEP", "why the LQIP split is here and not inline; cover not stretch"],
  245: ["KEEP", "rule 2 underline exemption and the ground it rests on"],
  246: ["KEEP", "measured 4.35:1 under the 4.5 floor; opacity invisible to the gate"],
  247: ["KEEP", "why Plot's style block is stripped; two reasons"],
  248: ["KEEP", "names what references the declaration"],
  249: ["KEEP", "why the table is collapsed and where the accessible name sits"],
  250: ["KEEP", "why a diagram is an img and why there are two; display:none deliberate"],
  251: ["KEEP", "measured 2px overflow at 320 on CI; why anywhere not break-word"],
  252: ["KEEP", "prohibition: no second declaration, no per-theme block, one owner"],
  253: ["KEEP", "why em rather than a fixed pixel size"],
  254: ["KEEP", "the border is load-bearing, with the failure it prevents"],
  255: ["KEEP", "why the fallback keeps --swatch out of the theme blocks"],
  256: ["KEEP", "prohibition: the chip never absorbs the shrink"],
  257: ["KEEP", "ratified forced-colors policy; forced-color-adjust deliberately unused"],
  258: ["KEEP", "why it is set here too, for unlisted languages"],
  259: ["KEEP", "provenance: markup is emitted by remark-gfm and cannot be changed"],
  260: ["KEEP", "provenance of the visually hidden heading"],
  261: ["KEEP", "one owner, rule 17; the cascade position that stopped being reliable"],
  262: ["KEEP", "why anchors are hidden but keyboard reachable"],
  263: ["KEEP", "WCAG 2.2 2.5.8 measured at 14.8 x 29"],
  264: ["KEEP", "why the reveal is scoped to hover; partial opacity invisible to the gate"],
  265: ["KEEP", "why the theme background is dropped; gate holds 4.5:1 on both surfaces"],
  266: ["KEEP", "measured against real pipeline output rather than assumed"],
  267: ["KEEP", "why only a span declaring its own background is matched; inherit trap"],

  // ---- post-shell.css, post-enhancements.css ----
  273: ["POINTER", "split header, canonical statement is app/app.css:1885"],
  274: ["CUT", "bare section separator"],
  275: ["KEEP", "WCAG 2.2 2.5.8 measured at 497.6 x 22.5"],
  276: ["CUT", "separator plus history of what was added on a date"],
  277: ["KEEP", "why the dek is a standfirst, not a first paragraph"],
  278: ["KEEP", "why the height is left to the image; D1 stores no dimensions"],
  279: ["KEEP", "why title and description must not run together"],
  280: ["KEEP", "hard rule 5: pinned bordered target takes --border-strong"],
  281: ["KEEP", "why the share row inherits .post-actions"],
  282: ["KEEP", "why one bordered-target style rather than two"],
  283: ["CUT", "restates the class name"],
  284: ["CUT", "restates the class name"],
  285: ["CUT", "bare label"],
  286: ["KEEP", "why the room is reserved conditionally; two rules, two browsers"],
  287: ["KEEP", "why the band is neutral; gate holds tokens on both surfaces"],
  288: ["CUT", "restates the class name"],
  289: ["CUT", "restates the class name"],
  290: ["KEEP", "top layer beats any z-index race; why ::backdrop not background"],
  291: ["KEEP", "ratified scrim at the heavier lightbox weight, with the why"],
  292: ["KEEP", "why a visible close exists; hard rule 5 border"],
  293: ["KEEP", "agent actions are plain links that work without script"],
  294: ["KEEP", "why mentions joins rather than copies; no new colour token"],
  295: ["KEEP", "why citation entries need air and no marker"],
  296: ["KEEP", "why anywhere: a 280-character excerpt with no spaces"],

  // ---- projects.css, publications.css, playground.css ----
  305: ["POINTER", "split header, canonical statement is app/app.css:1885"],
  306: ["KEEP", "binding rule 7; auto-fit collapses with no breakpoint or script"],
  307: ["KEEP", "why the metric leads: a number before a claim"],
  308: ["KEEP", "why the date is never absent"],
  309: ["KEEP", "why no bullet: it would promise an ordering the list lacks"],
  310: ["KEEP", "rule 1: status never carried by colour alone"],
  311: ["KEEP", "rule 2 exemption applies to the shape, not the colour"],
  312: ["KEEP", "why auto margin needs to be the last flex child"],
  313: ["KEEP", "why the citations sit last and the order that produces"],
  314: ["KEEP", "heading element for the outline, label type so it does not compete"],
  315: ["KEEP", "why stacked: a flex row would hyphenate two long titles"],
  316: ["KEEP", "why the leading is tightened for wrapped titles"],
  317: ["CUT", "bare label"],
  318: ["KEEP", "why it is a separate sheet; the token names differ from the original"],
  319: ["KEEP", "filter state in the URL, nothing needs scripting"],
  320: ["KEEP", "measured 40px against the 24px minimum"],
  321: ["KEEP", "the narrow underline exemption and its ground"],
  322: ["KEEP", "not opacity; the gate cannot see alpha, and the gap is recorded"],
  323: ["CUT", "pure separator rule"],
  324: ["KEEP", "edge and text tokens are NOT interchangeable, with the reason"],
  325: ["KEEP", "why only the wrap behaviour is its own"],
  326: ["KEEP", "why the paper page reuses names rather than restating them"],
  327: ["KEEP", "measured: the longest title is 150 characters, four lines of display"],
  328: ["KEEP", "why the export row reads as a caption, not a control"],
  329: ["KEEP", "why numbered; order is meaningful, longest runs to 50 entries"],
  330: ["KEEP", "why set apart by space rather than a rule or tint"],
  331: ["KEEP", "why deposits sit under the abstract, not in the link row"],
  332: ["KEEP", "why tinted, the opposite of the choice two rules above"],
  338: ["POINTER", "split header, canonical statement is app/app.css:1885"],
  339: ["KEEP", "binding rule 7 read correctly; rule 1, nothing distinguished by hue"],
  340: ["KEEP", "the row wraps, so no breakpoint and no script"],
  341: ["KEEP", "24px minimum target, WCAG 2.2 2.5.8"],
  342: ["KEEP", "why the cap is stated in the UI and not only enforced"],
  343: ["KEEP", "real URLs, shareable, work with scripting off"],
  344: ["KEEP", "the one legitimate inline colour: the reader's own input"],
  345: ["KEEP", "wide content scrolls in its own box; the body never scrolls sideways"],
  346: ["KEEP", "measured 26px overflow clipping the fused total"],
  347: ["KEEP", "h3 under h2 keeps the outline ordered"],
  348: ["KEEP", "why the snippet is deliberately not highlighted"],
  349: ["KEEP", "why nothing is added here; prose.css owns the treatment"],
  350: ["KEEP", "why the first-block top margin is removed inside a pane"],

  // ---- app.css, fonts through the Hill Country roles ----
  35: ["KEEP", "why Inter is self-hosted; request count before and after"],
  36: ["KEEP", "measured CLS 0.0674, one shift, single-variable"],
  37: ["KEEP", "ruled: the italic is kept and costs 79,716 bytes"],
  38: ["KEEP", "the metric-adjusted fallback and the measurement behind it"],
  39: ["KEEP", "serif axes read out of the binary rather than claimed"],
  40: ["KEEP", "measured 2026-09-13 with the method; records two wrong readings"],
  41: ["KEEP", "why the stacks are a plain :root block and not @theme"],
  42: ["KEEP", "measured 24 declarations, 14 values, three one apart"],
  43: ["KEEP", "the z-index trap: NOT --z-dropdown, with the three layers"],
  44: ["KEEP", "why Inter Fallback sits between the face and the generics"],
  45: ["KEEP", "why the mono stack became a token: a fourth copy would drift"],
  46: ["KEEP", "prohibition: the serif sets headings 32px and up and nothing else"],
  47: ["KEEP", "one owner; why it is not in the colour blocks"],
  48: ["KEEP", "why five properties and not a font shorthand"],
  49: ["KEEP", "why 420 rather than 400 on limestone"],
  50: ["CUT", "bare consumer list, no rule"],
  51: ["KEEP", "weight 600 not 560; the later step wins"],
  52: ["KEEP", "no leading token, and why a member with no reader is not a hole"],
  53: ["KEEP", "why this is the last Inter level"],
  54: ["KEEP", "the serif floor: 2rem fixed, never fluid, with the reason"],
  55: ["KEEP", "measured: lands on exactly 2rem at 375"],
  56: ["KEEP", "measured 2rem at 375, 3.25rem at 1280"],
  57: ["KEEP", "tracking is not one of the five; why no zero token"],
  58: ["KEEP", "why the strong nav weight is one form now and was two"],
  59: ["KEEP", "aliases are not levels, with the reason"],
  60: ["KEEP", "the only breakpoint in the type scale; keeps levels single-owner"],
  61: ["KEEP", "why the space scale is not in the colour blocks"],
  62: ["KEEP", "prohibition: nothing in the design uses a value off this scale"],
  63: ["KEEP", "the track is the measure, not a max-width on a child"],
  64: ["KEEP", "control dimensions are not spacing; 2.5.5 AAA is not the AA floor"],
  65: ["KEEP", "64rem is the header's breakpoint, so it introduces no new number"],
  66: ["KEEP", "durations named by job; why a number name invites reuse"],
  67: ["KEEP", "measured: under about 100ms reads as simultaneous; not 0"],
  68: ["KEEP", "measured band, 120 to 200ms, for a noticed state change"],
  69: ["KEEP", "measured fade band; prohibition, it is NOT the scroll reveal"],
  70: ["KEEP", "why a whole-document transition gets its own duration"],
  71: ["KEEP", "every hex is COPIED from the spec, never derived here"],
  72: ["CUT", "bare palette label"],
  73: ["KEEP", "why the heading token exists in light mode at all"],
  74: ["KEEP", "deliberately below the floor; measured 2.46:1 with the exemption"],
  75: ["KEEP", "prohibition: brand never signals a state"],
  76: ["KEEP", "ratified v4 chrome; why five role tokens instead of a hex per rule"],
  77: ["KEEP", "why the scrim is opaque: the backdrop would otherwise be the picture"],
  78: ["CUT", "bare palette label"],
  79: ["CUT", "bare palette label"],
  80: ["CUT", "bare palette label"],
  81: ["KEEP", "prohibition: decorative only, never signals a state"],
  82: ["KEEP", "destructive against danger; the distinction the library makes"],
  83: ["KEEP", "states which text colour goes on the highlight"],
  84: ["KEEP", "keyed by hue not position; rust needs a direct label"],
  85: ["KEEP", "ruling 65 status: these names exist and nothing reads them yet"],
  86: ["KEEP", "names the role limestone plays"],
  87: ["KEEP", "the lighter-in-dark rule for the raised surface"],
  88: ["KEEP", "prohibition: dust never sets type"],
  89: ["KEEP", "prohibition: not --text-secondary"],
  90: ["KEEP", "prohibition: lines only, never text, never a functional boundary"],
  91: ["KEEP", "measured 1.57:1 on limestone"],
  92: ["KEEP", "prohibition: a press is not a hover and is never --visited"],

  // ---- app.css, figure palette through the split ----
  93: ["KEEP", "prohibition: legal on /search over paper and nowhere else"],
  94: ["KEEP", "error text and the field border width"],
  95: ["KEEP", "figures only; no semantic colour, a series is not a state"],
  96: ["KEEP", "prohibition: figures sit on paper, never on raised"],
  97: ["KEEP", "maps the token to the brief's primitive"],
  98: ["KEEP", "maps the token to the brief's primitive"],
  99: ["KEEP", "maps the token to the brief's primitive"],
  100: ["KEEP", "slots are the interface; a chart never reads a hue name"],
  101: ["KEEP", "names the light and dark ramp positions this slot resolves to"],
  102: ["KEEP", "names the light and dark ramp positions this slot resolves to"],
  103: ["KEEP", "names the light and dark ramp positions this slot resolves to"],
  104: ["KEEP", "names the light and dark ramp positions this slot resolves to"],
  105: ["KEEP", "names the light and dark ramp positions this slot resolves to"],
  106: ["KEEP", "the catch hue follows the backdrop, not the theme, with the reason"],
  107: ["KEEP", "names the light and dark ramp positions this slot resolves to"],
  108: ["KEEP", "the zero-JS path and the system setting are one code path"],
  109: ["KEEP", "prohibition: warm brown-black, never blue-black"],
  110: ["KEEP", "measured 13.1:1; why the body steps one off maximum"],
  111: ["KEEP", "measured chrome pairs 10.1, 6.9 and about 10"],
  112: ["POINTER", "dark copy of the scrim note at app/app.css:798"],
  113: ["KEEP", "measured 7.59/6.80/5.94 mirroring 7.62/6.87/6.34"],
  114: ["POINTER", "dark copy of the Paper Glass Light note at app/app.css:883"],
  124: ["POINTER", "dark copy of the figure palette note at app/app.css:918"],
  129: ["POINTER", "dark copy of the series slots note at app/app.css:947"],
  135: ["POINTER", "dark copy of the lamp catch hue note at app/app.css:962"],
  137: ["KEEP", "why values are written twice; the gate has to see a hex"],
  138: ["KEEP", "why the ratified hover hex is reused for dark brand-active"],
  139: ["POINTER", "the reason is stated at app/app.css:1169"],
  141: ["KEEP", "why all three declarations exist and are measured"],
  165: ["KEEP", "why the lamp's numbers are not in the colour blocks"],
  166: ["KEEP", "why light sits near the leading edge"],
  167: ["KEEP", "why dark sits further in and carries more"],
  168: ["KEEP", "at zero the gradient still renders; no second code path"],
  169: ["KEEP", "the narrow prefers-contrast tier and what the doc allows"],
  170: ["KEEP", "forced-colors: the palette yields entirely, nothing re-asserts brand"],
  171: ["KEEP", "why the admin edges are shadows; a border is subtracted from the height"],
  172: ["CUT", "bare label"],
  173: ["KEEP", "why the chip needs the forced outline"],
  174: ["KEEP", "why status dots need a forced border; the word was the real channel"],
  175: ["KEEP", "why selection is restated as an edge"],
  176: ["KEEP", "why the surface ladder collapses to one system Canvas"],
  177: ["KEEP", "border-style is the second channel and survives the mode"],
  178: ["KEEP", "why the edge is the only thing left holding the alert"],
  179: ["KEEP", "why both are shapes made of a background"],
  180: ["KEEP", "the shared inset declared once; amended 2rem to 1.5rem"],
  181: ["KEEP", "rule 2, grounded in CVD and Vienot rather than taste"],
  182: ["KEEP", "element-level so component headings still outrank it"],
  183: ["KEEP", "why the hero leaves room for header and footer"],
  184: ["KEEP", "why the affiliation is quieter than the role"],
  185: ["KEEP", "why the front door is in app.css and not route-split"],
  186: ["KEEP", "prohibition: no min-height 100dvh, with the reason"],
  187: ["KEEP", "why auto-fit with a floor and no breakpoint"],
  188: ["KEEP", "why the link carries value and label; accessible name"],
  189: ["CUT", "bare section label"],
  190: ["KEEP", "focus is an outline, never a box-shadow; forced-colors strips shadows"],
  191: ["KEEP", "why this one declaration is the dark-mode variant"],
  192: ["KEEP", "canonical: the import order is the cascade"],
  193: ["KEEP", "measured 109,318 built bytes before the admin split"],
};
